### ISSUE TITLE
Dot net 4.5 not supported?

### ISSUE THREAD

**Issue by vickyrathee** [sqlkata/querybuilder#1]
I am getting following error when installing from Nuget

PM> Install-Package SqlKata -Pre
Installing 'SqlKata 1.0.0-beta-32'.
Successfully installed 'SqlKata 1.0.0-beta-32'.
Adding 'SqlKata 1.0.0-beta-32' to QueryBuilder.
Uninstalling 'SqlKata 1.0.0-beta-32'.
Successfully uninstalled 'SqlKata 1.0.0-beta-32'.
Install failed. Rolling back...
Install-Package : Could not install package 'SqlKata 1.0.0-beta-32'. You are trying to install this package into a project that targe
ts '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with t
hat framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  SqlKata -Pre
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by ahmad-moussawi** [comment]
@vickyrathee yes currently it is supported on `netcoreapp1.0`, a new release will be published soon targeting net45

**Comment by ahmad-moussawi** [comment]
My current focus is to support the netstandard 2.0, I appreciate if anyone could help on this.

**Comment by kwaclaw** [comment]
Your library already works with netstandard2.0 projects.
But you could add net45 to the targetframeworks. I had to make these changes in the project file:
```
    <TargetFrameworks>netstandard1.3;net45</TargetFrameworks>
```
and had to add
```
  <ItemGroup Condition=" '$(TargetFramework)' == 'net45' ">
    <Reference Include="System" />
  </ItemGroup>
```
then it builds OK for me.

**Comment by ceastwood** [comment]
@ahmad-moussawi 
Submitted PR for net45 (net452 for tests due to xunit)

**Comment by SamarRizvi** [comment]
@ahmad-moussawi 
Since you have merged PR of @ceastwood , can you make a new release for net45

**Comment by ahmad-moussawi** [comment]
@SamarRizvi currently I don't have the needed env to test it for **net45** since I am using a mac device, what actually needed is to close this issue:
 - Make sure that the tests passes on this environment
 - Configure AppVeyor to build the nuget packages after pushing a valid commit on the master branch
 - Make sure that this new release will not affect netcore projects

I think that @ceastwood is the best one for now to deal with this, 
@ceastwood can you help in this ?

**Comment by ceastwood** [comment]
@ahmad-moussawi 

I'm not at my dev machine right now but I do have travis-ci and appveyor ready for this repo, I can complete the tests-- I have additional uncommitted unit tests add as well. I can complete those and build the nuget packages locally but not push to your feed.

This change won't affect other projects if everything passes, but the PR I have for renaming will. Let me know what you would like and I can complete.

**Comment by ahmad-moussawi** [comment]
@ceastwood many thanks, mm to support net45 we have to automate the build for windows, I will check how we can do it with AppVeyor, and hope we may find someone who have better knowledge than me :)

**Comment by ceastwood** [comment]
@ahmad-moussawi  

The appveyor image in use for this repo is hosted on Windows Server 2016; 
I've created a new branch update-build-scripts on my fork of the repo and started to complete the tasks. I prefer to use a slightly different (but msbuild native) way of handling semver so that change is there too.

The changed I have pushed up to now in that branch builds and packages everything fine. I will create a matching build/pack shells scripts for you since you mentioned your on mac before I submit the PR.

**Comment by eyedia** [comment]
I have net45 solution, not facing what @vickyrathee  had faced, but getting this:

> Additional information: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

`compiler.Compile(fastCarsQuery).Sql`

**Comment by ceastwood** [comment]
@eyedia 

Are you using the nuget package that is available? If so, that package states that it only supports netstandard1.3 as shown [here (under dependencies)](https://www.nuget.org/packages/SqlKata/1.0.0-beta-353)

Work is being done to update the build tooling for this project and when those changes are merged there should be a net45 nuget package available then.

**Comment by eyedia** [comment]
Thanks @ceastwood , I missed that. Yes, it worked.
Wow! it installed 285MB packages, we definitely need net45 nuget package.

I also wanted to know how can I contribute, I have a sample database with various types of joins(relationship). I can provide queries/scenarios,/troubleshoot. let me copy @ahmad-moussawi  here.

**Comment by ahmad-moussawi** [comment]
@ceastwood yes sure, I tried to mimic Dapper build script [build.ps1](https://github.com/StackExchange/Dapper/blob/master/build.ps1) but I've failed :s, I can add you as a member in AppVeyor if needed, I can help also in setting the shell script form my side

**Comment by ahmad-moussawi** [comment]
@eyedia your suggestions and contributions are always welcomed, currently as @ceastwood  mentioned we are focusing on targeting the 45 framework, 
You can check https://github.com/sqlkata/querybuilder/projects/1 for our backlog

**Comment by ceastwood** [comment]
@ahmad-moussawi  I have no problem with the shell script, I just have been caught up with work. But I think appveyor will auto build when we commit to master; so the only way I can push things is with write access to this repo or with you merging the PR.

**Comment by ceastwood** [comment]
@ahmad-moussawi  I should have the build tooling update & PR done very soon, and I also have the rename PR I will resubmit after the first merge

**Comment by ahmad-moussawi** [comment]
Ok waiting the awesomeness 👍

**Comment by ceastwood** [comment]
@ahmad-moussawi Sorry, I took a little but of a break since I had to travel, but I should finish up by tomorrow. Thanks

**Comment by ceastwood** [comment]
@vickyrathee 
@kwaclaw 
@eyedia 
@SamarRizvi 

v1.0.0-beta-357 is published and supports a target framework of net45

**Comment by eyedia** [comment]
Nice

**Comment by SamarRizvi** [comment]
@ceastwood Thanks a lot.
