### ISSUE TITLE
From Clause can't handle tablenames with space

### ISSUE THREAD

**Issue by Blanen** [sqlkata/querybuilder#100]
The From clause seems to interpret "Order Line AS OrderLine" as "Order AS [AS]"

**Example:**

`new Query("Order Line AS OrderLine");`

If you compile this to SQL-Server SQL you get:

`SELECT * FROM [ORDER] AS [AS]`

While it should be:

`SELECT * FROM [Order Line] AS [OrderLine]`

Looking at how this currently works:

https://github.com/sqlkata/querybuilder/blob/ea55996a503a8eb585078c10cc434f8513dbc275/QueryBuilder/Clauses/FromClause.cs#L29

Thinking there might just need to be a more explicit AS.

**Comment by ahmad-moussawi** [comment]
yes I see, thanks for reporting fixed now in the latest beta version
