### ISSUE TITLE
NuGet outdated?

### ISSUE THREAD

**Issue by uiii** [sqlkata/querybuilder#102]
Hi, why is the latest version in NuGet gallery `1.0.0-beta-484` while in MyGet is `1.0.0-beta-532`?

**Comment by ahmad-moussawi** [comment]
we decided to stop publishing unstable releases to NuGet, and nightly builds are automatically published to MyGet for easier public testing.

I will try to unpublish all unstable versions from NuGet, once publishing the first stable version.

**Comment by uiii** [comment]
Please give some visible info (on first sight) to readme and doc, because I missed it and was developing some time with the old version from nuget.

**Comment by ahmad-moussawi** [comment]
it's mentioned in the documentation site, I will make it more clearer, thanks for the feedback
