### ISSUE TITLE
CROSS/OUTER APPLY, LATERAL subqueries support

### ISSUE THREAD

**Issue by ahmad-moussawi** [sqlkata/querybuilder#104]

**Comment by PejmanNik** [comment]
Hi Ahmad. Do you have any proposal for it? I need outer apply and ready to implement it and make a PR. Thank you.

**Comment by SkutyKuba** [comment]
I added outer apply statment by using FromRaw method, but this is not elegant way. Could you consider adding JoinRaw method or something simillar?
`
var sql = db.Query("dgt").FromRaw("dgt outer apply (select case when exists(select id_dgt_zdarz from dgt_zdarz where dgt_zdarz.id_dgt = dgt.id_dgt) then 1 else 0 end as any_data)w")`

**Comment by WalkeR321** [comment]
More elegant option

```
var q = db
                .Query("TableA as A")
                .Join(db
                        .Query()
                        .From("TableB")
                        .WhereColumns("SomeColumnB", "=", "A.SomeColumnA")
                        .Where("SomeColumnB", "SomeValueB")
                        .Select("SomecolumnB")
                        .As("B"),
                    j => j,
                    "Outer Apply");
```

**Comment by ahmad-moussawi** [comment]
This can be closed since the "Join" overload is an acceptable working solution
