### ISSUE TITLE
Rename generated DLL to SqlKata.dll instead of QueryBuilder.dll

### ISSUE THREAD

**Issue by johnny551** [sqlkata/querybuilder#109]
QueryBuilder stopped working for me as it no longer supports .NET Framework 4.0.   My project cannot run .NET Framework 4.5 due using a legacy reference that doesn't support it.

**Comment by ahmad-moussawi** [comment]
Actually I can test this on environment, since using mac so I cannot target netfx frameworks, are you able to make a pull request addressing the needed changes ?

**Comment by johnny551** [comment]
Wow, that was a quick response.  I am unable to make a pull request, because I am unsure of what needs to be done :-S

**Comment by ceastwood** [comment]
@johnny551  

You're right, I had added net45 targeting this last time, and net40 was a while ago but had been removed at some point. 

You should be able to use the library with net40 as-is but you will likely need to add NetStandard.Library. I haven't tested this either.

@ahmad-moussawi  I will add targeting for net40 back to the project today

**Comment by ceastwood** [comment]
@johnny551  

I took a look, and net40 support will require a little more than just targeting. We had transitioned to using IReadonlyDictionary<Tk,Tv> which does not exist until net45. I would try to use the netstandard route for the moment.

**Comment by johnny551** [comment]
Oh my gosh.  I FIXED my issue.  I changed the project name from "QueryBuilder" to "QueryBuilderAbc" and rebuilt the project.  This created a QueryBuilder.dll which I imported into my app and BINGO, no more error in Crystal Reports.

I suspect that the "Query Builder" name is commonly used which is what caused the conflict.

**Comment by johnny551** [comment]
BINGO - I was right.   Crystal Reports has a "querybuilder.dll" in the following location: C:\Program Files (x86)\SAP BusinessObjects\SAP BusinessObjects Enterprise XI 4.0\win32_x86.

I would recommend changing the project name (or DLL name) to SQLKata.dll or something similar since it would more uniquely identify your DLL.

**Comment by ahmad-moussawi** [comment]
The assembly name was renamed to SqlKata.dll so I think we can close this
