### ISSUE TITLE
Rename project files and update namespaces?

### ISSUE THREAD

**Issue by ceastwood** [sqlkata/querybuilder#11]
Would you like me to commit a PR to rename QueryBuilder/QueryBuilder.Tests to SqlKata/Tests.SqlKata (incl. namespace updates) or let me know.

Thanks,

**Comment by ahmad-moussawi** [comment]
@ceastwood actually the namespaces should be renamed the QueryBuilder.Tests (the file names are correct), since am planning to add other db related projects under SqlKata, it would be great if you can help :) thanks

**Comment by ceastwood** [comment]
So would SqlKata.QueryBuilder for the project work?

**Comment by ahmad-moussawi** [comment]
yes true, the namespaces should be renamed from SqlKata.Tests to QueryBuilder.Tests

**Comment by ceastwood** [comment]
Sorry about the two references early this morning, I was merging changes I should be testing cross-platform first. This current PR is good to go.

**Comment by ceastwood** [comment]
@ahmad-moussawi Probably :)

**Comment by ahmad-moussawi** [comment]
:D thanks
