### ISSUE TITLE
Problem in updating with factory (query execution)

### ISSUE THREAD

**Issue by seantheyahn** [sqlkata/querybuilder#110]
When using UpdateAsync with QueryFactory:

Exception: System.NotSupportedException: Npgsql 3.x removed support for writing a parameter with an IEnumerable value, use .ToList()/.ToArray() instead

**Comment by ahmad-moussawi** [comment]
Could you post the full example, and the dotnet/npgsql versions that you are using ?

**Comment by seantheyahn** [comment]
This is an example (since the code has irrelevant parts):
`using Newtonsoft.Json.Linq;`
...
```
var j = JObject.FromObject(profile);
j.Remove("someField");
j.Remove("someOtherField");
var dct = new Dictionary<string, object>();
foreach (var item in j)
{
    dct.Add(item.Key, item.Value);
}
await db.Query("table").Where("id", id).UpdateAsync(dct);
```
I think the problem is using the JToken for this purpose and not explicitly casting to the relevant type in the dictionary. (Tried it with Dapper and still the problem exists)

**Comment by ahmad-moussawi** [comment]
I think the error is clearly from `Npgsql`, and state that you can't pass an `IEnumerable`, check the `item.Value` and make sure that isn't of type `IEnumerable`, I will close this issue since there is nothing to solve here.
