### ISSUE TITLE
SQLServerCompiler inserts a \n after the first join clause. Unexpected behavior?

### ISSUE THREAD

**Issue by Blanen** [sqlkata/querybuilder#115]
I noticed that after installing 1.0.x that my unittests were not working anymore.

After making the following test I discovered that SQLKata was inserted a newline character (\n) after the first join clause(or before the second, depends on how you see it).
```
var query = new SqlKata.Query("Product");
query.Join("x", "y", "z");
query.Join("a", "b", "c");
var compiler = new SqlKata.Compilers.SqlServerCompiler();
var sql = compiler.Compile(query).RawSql;
```

Expected result:

```
SELECT * FROM [Product] INNER JOIN [x] ON [y] = [z] INNER JOIN [a] ON [b] = [c]
```

Actual Result:

```
SELECT * FROM [Product] INNER JOIN [x] ON [y] = [z]
INNER JOIN [a] ON [b] = [c]
```

**I mainly want to know if this was the result of the author's 'vision' or that this is unintentional so I can adjust my unittests accordingly.**

If this is intentional then maybe a newline before each join is even better, like so:

```
SELECT * FROM [Product]
INNER JOIN [x] ON [y] = [z]
INNER JOIN [a] ON [b] = [c]
```

**Comment by Blanen** [comment]
@ahmad-moussawi I started on it.

Is https://github.com/sqlkata/querybuilder/blob/3331bfc752ad1693b5971e967e7409b43e9c8ab7/QueryBuilder/Compilers/Compiler.cs#L81 necessary? Shouldn't the compiling methods return correct strings anyway?

If I can just remove that and do this:

https://github.com/Blanen/querybuilder/blob/c64091aafd20563a3c4db5b62ec9aa68e7a6956c/QueryBuilder/Compilers/Compiler.cs#L435

I'll adjust the expected compile results in the unit tests accordingly. Maybe even add some for multiple joins, since they don't seem to be there yet.

**Comment by ahmad-moussawi** [comment]
yes you are right, I think there is no need for the `Trim` here, I merged the PR, thanks
