### ISSUE TITLE
Join On with SQL logic

### ISSUE THREAD

**Issue by imothep666** [sqlkata/querybuilder#117]
Hello,

I have a problem with the JOIN logic when I try to create a JOIN with replacement logic:

.Join(inner, j => j.On("isnull(t1.col, 1)", "t2.col"))

the column ("col") in t1 can be null but for the join i need a standard value.

thanks and regars

**Comment by imothep666** [comment]
SELECT * FROM t1
LEFT JOIN t2 on isnull(t1.col, 1) = t2.col;

**Comment by ahmad-moussawi** [comment]
The `On` is a syntactic sugar over the `Where` method, in your case you have to use the `XRaw` methods, so using:
```cs
new Query("t1").Join("t2", 
  j => j.WhereRaw("isnull([t1].[col], 1) = [t2].[col]")
);
```

will produce: 

```sql
SELECT * FROM [t1] INNER JOIN [t2] ON (isnull([t1].[col], 1) = [t2].[col])
```

**Comment by imothep666** [comment]
thanks for the quick response - problem solved
