### ISSUE TITLE
Unique alias generator 

### ISSUE THREAD

**Issue by tlaguz** [sqlkata/querybuilder#118]
There is need to generate unique aliases to use inside SQL queries.
This issue was created to continue discussion from #56  

It would be best if aliases inside each query was starting from constant number (0 or 1). It would make debugging a lot easier. Solutions 1 and 2 don't meet this.

## 1. Random Generator: 

```cs
public static class UniqueAliasGenerator 
{
    public static string GenerateAlias()
    {
        var rnd = new Random();
        return $"SqlKata_{rnd.Next()}__";
    }
}
```

## 2. Cyclic Generator: 
```cs
public static class UniqueAliasGenerator 
{
    public static uint Counter { get; private set; }
    
    public static string GenerateAlias()
    {
        return $"SqlKata_{Counter++}__";
    }
}
```

## 3. Generator in `Query` class: 

```cs
    public abstract class AbstractQuery
    {
        protected AbstractQuery Parent;
        
        public uint AliasCounter { get; protected set; }
        public string GetUniqueAlias => Parent != null ? Parent.GetUniqueAlias : $"SqlKata_{AliasCounter++}__";
    }
```
The problem is that, `Parent` is not copied by `Copy` method. 

## 4. `SqlResult` class

We can't place generator inside `SqlResult` class, because in nested query scenario it is not shared among all queries.

**Comment by ahmad-moussawi** [comment]
What is the difference between the 1st and the 2nd ?

**Comment by tlaguz** [comment]
I've edited my post.
In the 2nd option we could make `Counter` thread static to achieve thread-safety and have numbering starting from 0 at least within thread.

In the 4th we could pass current numbering somehow to subquery's SqlResult, but then we would have to update parent SqlResult numbering as well.
