### ISSUE TITLE
Report builder

### ISSUE THREAD

**Issue by UpretiLalit** [sqlkata/querybuilder#120]
Hi i want to build dynamic reporting tool with this help in c#.did you have some example of building dynamic query how it works

**Comment by ahmad-moussawi** [comment]
Please check the documentation, and if you have any question feel free to ask it on https://stackoverflow.com

**Comment by UpretiLalit** [comment]
Can I join three tables dynamic way (user will decide the table ) .BY
SQLKATA in c#.if yes could you please send some source code in c# for demo
