### ISSUE TITLE
No table is set Exception

### ISSUE THREAD

**Issue by PejmanNik** [sqlkata/querybuilder#123]
Hi 
We can have a query without 'from' like:

```sql
select '2' , '3'
````

https://github.com/sqlkata/querybuilder/blob/bd8aa437cdbbfccca38fd83a8671f1dc2624480d/QueryBuilder/Compilers/Compiler.cs#L415

**Comment by ahmad-moussawi** [comment]
Could you elaborate more on the use case where you want this ?

**Comment by ahmad-moussawi** [comment]
closing since long time with no reply, feel free to reopen if this still an issue for you

**Comment by mark-at-tusksoft** [comment]
@ahmad-moussawi 
Found my way here from a google search as I am running into this issue currently.

I am populating a model in the format
```csharp
public class SomeStatsObject {
    public int ThingsAlphaCount { get; set; }
    public int ThingsBetaCount { get; set; }
    public int ThingsGammaCount { get; set; }
    public int ThingsDeltaCount { get; set; }
}
```

that gets counts from a bunch of complex subqueries in the form of:

```sql
SELECT
    (SELECT ...) ThingsAlphaCount,
    (SELECT ...) ThingsBetaCount,
    (SELECT ...) ThingsGammaCount,
    (SELECT ...) ThingsDeltaCount,
```

I believe subqueries get what I need so my Sql Kata follows

```csharp
 var mainQuery = new Query()
    .Select(thingsAlphaCountSubQuery, nameof(SomeStatsObject.ThingsAlphaCount))
    .Select(thingsBetaCountSubQuery, nameof(SomeStatsObject.ThingsBetaCount))
    .Select(thingsGammaCountSubQuery, nameof(SomeStatsObject.ThingsGammaCount))
    .Select(thingsDeltaCountSubQuery, nameof(SomeStatsObject.ThingsDeltaCount));

var compiledQuery = new SqlServerCompiler().Compile(new[] { someRawQueryForParams, mainQuery });
```

Thus, I get the 'No table is set' exception.

**Comment by rfink** [comment]
Or when using "CROSS APPLY" for column reuse within the same query

**Comment by xavierzwirtz** [comment]
Similar issue as OP, would be nice to be able to run `select SERVERPROPERTY('productversion')`

**Comment by ahmad-moussawi** [comment]
@xavierzwirtz  `db.Select("select SERVERPROPERTY('productversion')")` is more appropriate here

**Comment by mark-at-tusksoft** [comment]
@ahmad-moussawi Could this be reopened? This is still an ongoing issue when compiling for SqlServer.

**Comment by mnsrulz** [comment]
> Or when using "CROSS APPLY" for column reuse within the same query

just curious if you able to tackle cross apply or outer apply with column reuse only

**Comment by mnsrulz** [comment]
> Guys, you can just inherit your copiler class eg. `SqlServerCompiler` and override `CompileFrom` method like that:
> 
> ```
> public override string CompileFrom(SqlResult ctx)
> {
>     if (!ctx.Query.HasComponent("from", EngineCode))
>     {
>         return null;
>     }
> 
>     return base.CompileFrom(ctx);
> }
> ```
> 
> now query: `new Query().Select("1 as Test");` won't throw any exception and returns `SELECT [1] AS [Test] `.

this is really great..
