### ISSUE TITLE
Bindings in oracle have different format

### ISSUE THREAD

**Issue by tlaguz** [sqlkata/querybuilder#126]
There is need to handle oracle bindings: `:p0` instead of `@p0`.

## Solution 1
40fd8a899a0ad5873ab8a294dd3deb04067d498f, then in type `OracleSqlResult` overload method `NamedBindingFormat`.

## Solution 2
Move NamedBinding mechanism to Compiler class.

## Solution 3
26536011de6a947faf68b0c74880ace929d7ea0b

Which one would you prefer?

**Comment by ahmad-moussawi** [comment]
I think the 2nd solution is more appropriate, leaving this to the compiler is easier to maintain and extend.

but I am thinking why this is not handled by Dapper?

**Comment by tlaguz** [comment]
> The SQL is passed through as-is, and must contain the correct :param1 or @param1 etc.

~Marc Gravell source: https://stackoverflow.com/questions/20962405/dapper-net-oracle-parameter

**Comment by tlaguz** [comment]
In `SqlResult` class there is `+` operator overload which, in compiler solution, is problematic. All solutions that come to my mind end up with storing db type information in `SqlResult`. In my opinion this is acceptable, because being created by db-specific compiler, `SqlClass` is by definition db-specific.

`+` operator implementation has to somehow regenerate named bindings. It can be done for example by concatenating `0` and `1` to the end of parameter names, but this will generate bad looking and unnecessary long names when summing many `SqlResult`s. Rewriting numbers inside names would be not efficient.

If we want to have single `SqlResult` class we could create `NamedBindingParameters` class to `SqlQuery` which different implementations would contain all logic required.

Considering all, I think that solution 1 is the most clean and easy one.

**Comment by ahmad-moussawi** [comment]
Ok go with it, if it's the most approachable way to do that.
Maybe this part need to be redesigned in a better approach, but this not a priority right now.

**Comment by tlaguz** [comment]
I tried to move binding mechanism to compiler, and adjust "+" operator. I had to move SqlResult combining logic to compiler as well.

Please look at commit fb08756b334073507ccffce7d7a32672c05b1854

**Comment by ahmad-moussawi** [comment]
@tlaguz, sorry for the late reply, but I was a bit overloaded, I still need some time to review it, I will get back to you the soonest.

**Comment by tlaguz** [comment]
@ahmad-moussawi Have you found time to review it? I would like to continue with oracle compiler

**Comment by ahmad-moussawi** [comment]
@tlaguz, sorry for the late reply, I agree going with the first option is acceptable, in 2.0 we can replan if there is a more appropriate choice.
