### ISSUE TITLE
Idea: Constructing WHERE filters from an expression.

### ISSUE THREAD

**Issue by Blanen** [sqlkata/querybuilder#127]
Currently, 
https://github.com/sqlkata/querybuilder/blob/master/QueryBuilder/Base.Where.cs#L124

Only accepts a delegate as argument.

I'm currently working on a delegate-builder that works on runtime, constructing the delegate from specifcations in json recursively. I got it working but it's not the easiest way to go about it.

For the developer in my situation it would be way simpler to work with a Expression tree instead or as an additional option. Like this:

`public Q Where(Expression<Func<Q, Q>>)`

Constructing the actual where filters wouldn't become harder, because walking through an Expression Tree is not that complicated.

Just a suggestion :) I might even make it sometime.

**Comment by ahmad-moussawi** [comment]
@Blanen, could you show me an example on what you want to achieve ?

**Comment by penCsharpener** [comment]
hey @ahmad-moussawi,
can we re-open this issue? I've been working on this a little and you find some first bare bone spagetti code examples in this repo of mine:

[MYaSyncQL.WhereExpressions](https://github.com/penCsharpener/MYaSyncQL/blob/master/src/MYaSyncQL.WhereExpressions/ExpressionParser.cs)

[UnitTests are passing](https://github.com/penCsharpener/MYaSyncQL/blob/master/src/MYaSyncQL.UnitTests/ExpressionTests/SimpleBoolTests.cs)

Please let me know if you are interested to have something like this. Parsing Expressions is tedious and is a lot of work but I think for some basic stuff it would be really useful. This also requires the attributes @mota57 is working on. In the code above I implemented my own version until sqlkata 1.1.8 is out.

**Comment by ahmad-moussawi** [comment]
@penCsharpener Supporting expressions is out of scope for now,
because it will add a lot of complexity to the core, I prefer to focus on enhancing what we have before releasing the 2.0 and keep things like this to the community.

Thanks for sharing, I will check it out to get an idea anyway.

**Comment by mota57** [comment]
@penCsharpener the attributes is complete.
