### ISSUE TITLE
Raw Option for Joins?

### ISSUE THREAD

**Issue by avlcodemonkey** [sqlkata/querybuilder#128]
Is there a way to do a raw join, like WhereRaw?  I'd like to be able to add a join specifying the entire predicate for the join instead of the exact columns to join on.  

Instead of:
`var query = new Query("Posts").Join("Authors", "Authors.Id", "Posts.AuthorId");`
Do this:
`var query = new Query("Posts").JoinRaw("Authors", "Authors.Id = Posts.AuthorId");`

**Comment by ahmad-moussawi** [comment]
yes you can use the same `WhereRaw` in the lambda overload

```cs
query.Join("Table", j =>  j.WhereRaw(""));
```

**Comment by avlcodemonkey** [comment]
Excellent.  I'll give that a try.  Thanks.
