### ISSUE TITLE
bug: SqlServer pagination on page 2 and after that

### ISSUE THREAD

**Issue by PejmanNik** [sqlkata/querybuilder#13]
Thanks for your great project.
In SqlServer when using pagination on page 2 and after that SQL throw exception for the compiled query.

I think there is 2 **bug**:

1. when transforming the query to subquery there is a control for existence column in the query and add a '*' to column clause but column clause has component name 'select' not 'columns'. with change it an extra '*' will be removed 

2. the subquery should have name (alias) in Sql Server

**Comment by ahmad-moussawi** [comment]
@PejmanNik  thanks for your support, fixed on the https://www.nuget.org/packages/SqlKata/1.0.0-beta-354 package
