### ISSUE TITLE
Multi Mapping 

### ISSUE THREAD

**Issue by abannsunny** [sqlkata/querybuilder#131]
Dapper has the ability to do multi mapping in a scenario like this(from their official docs):

Dapper allows you to map a single row to multiple objects. This is a key feature if you want to avoid extraneous querying and eager load associations.

Example:

Consider 2 classes: Post and User

```cs
class Post
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }
    public User Owner { get; set; }
}

class User
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

Now let us say that we want to map a query that joins both the posts and the users table. Until now if we needed to combine the result of 2 queries, we'd need a new object to express it but it makes more sense in this case to put the User object inside the Post object.

Solution is:

```cs
var sql =
@"select * from #Posts p
left join #Users u on u.Id = p.OwnerId
Order by p.Id";

var data = connection.Query<Post, User, Post>(sql, (post, user) => { post.Owner = user; return post;});
var post = data.First();
```

Is there a way to do this in sqlKata?

Thank you,
Abann

**Comment by ahmad-moussawi** [comment]
Hi Abann, no currently there is no way to do it in SqlKata, at the time being you could use SqlKata to build the Sql for you, then use the underlying connection to execute with Dapper.
a quick example could be:

```cs
var usersQuery = db.Query("Posts").Join("Users", "Users.Id", "Post.UserId");
var xQuery = usersQuery as XQuery;
var compiler = xQuery.Compiler;
var connection = xQuery.Connection;

var compiled = compiler.Compile(usersQuery);
var data = connection.Query<Post, User, Post>(compiled.Sql, compiled.Bindings, (post, user) => {...});
```

**Comment by absid89** [comment]
i like that the query results to be elegantly and quickly converted into objects in a couple of lines of code

Sorry for a stupid question, but I don’t understand the construction of the code, why such a sequence "<Post, User, Post>" is indicated in brackets, which section с# I need to study.

**Comment by ahmad-moussawi** [comment]
@absid89 here is a **generic function** with three **type parameters**, read more about the generic explanation in C#, in the example above, it's a function related to https://github.com/StackExchange/Dapper

**Comment by absid89** [comment]
thanks, I already found the answer, I did not understand why 3 parameters(Post, User, Post) and not 2 (Post, User), it turns out that the last one is the type of resulting list. Right?

**Comment by ahmad-moussawi** [comment]
@absid89, sorry for the late reply, yes your assumption is correct.

**Comment by ansarizafar** [comment]
Joins are everywhere, Multi mapping is a very important feature and currently its difficult to map multiple models. 

In my opinion, amazing SqlKata should somehow do it automatically.
@ahmad-moussawi Please except it as feature request.

**Comment by nathanpovo** [comment]
> Hi Abann, no currently there is no way to do it in SqlKata, at the time being you could use SqlKata to build the Sql for you, then use the underlying connection to execute with Dapper.
> a quick example could be:
> 
> ```cs
> var usersQuery = db.Query("Posts").Join("Users", "Users.Id", "Post.UserId");
> var xQuery = usersQuery as XQuery;
> var compiler = xQuery.Compiler;
> var connection = xQuery.Connection;
> 
> var compiled = compiler.Compile(usersQuery);
> var data = connection.Query<Post, User, Post>(compiled.Sql, compiled.Bindings, (post, user) => {...});
> ```

For anyone else that stumbles onto this issue, I had to modify the code as follows:

```cs
IDbConnection db = new SqlConnection(connectionString);
SqlServerCompiler compiler = new SqlServerCompiler();

Query query = new Query("Table1")
    .Select("col1", "col2", "col3", "col3")
    .Join("Table2", "col1", "columnFromTable2ThatShouldBeEqualTocol1")
    .Where(new
    {
        col2 = 25,
        col3 = "someStringValue"
    });

SqlResult sqlResult = compiler.Compile(query);

Post post = db.Query<Post, User, Post>(sqlResult.Sql, (p, u) => {...},
    param: sqlResult.NamedBindings).SingleOrDefault();

**Comment by Aruinerk** [comment]
> Joins are everywhere, Multi mapping is a very important feature and currently its difficult to map multiple models.
> 
> In my opinion, amazing SqlKata should somehow do it automatically.
> @ahmad-moussawi Please except it as feature request.

I would also consider this as a mvp feature for sqlkata. 
I tried to use sqlkata for these kind of mapping too.

This could be implemented by sqlkata-team doing something like that: (Pseudo code)
```csharp
public static T InjectOther<T>(T instance)
        {
            foreach (PropertyInfo property in typeof(T).GetProperties())
            {
                if (property.PropertyType.IsClass)
                {
                    var childInstance = Activator.CreateInstance(property.PropertyType);
                    
                    // Set joined properties here with kind of join mapping
                    
                    property.SetValue(instance, childInstance);
                }
            }

            return instance;
        }
```

**Comment by ahmad-moussawi** [comment]
Guys, have you checked the `Include` and `IncludeMany` functionality?
it seems more appropriate for these kind of operations
