### ISSUE TITLE
Splitting values in join should only be done with the last occuring period character.

### ISSUE THREAD

**Issue by Blanen** [sqlkata/querybuilder#132]
https://github.com/sqlkata/querybuilder/blob/edfe05512da11a50ba3fceb3124132c9d29ad92a/QueryBuilder/Compilers/Compiler.cs#L628 splits by every period character.

I don't think there's ever a occurrence where, for example in sql server, `[a].[b].[c]`would be valid.

This should only split by the last found `.` so you get `[a.b].[c]`

Could be done with `String.LastIndexOf` and `SubString`.

```
if (value.Contains("."))
{
    var i = value.LastIndexOf('.');
    var strings = new string[] {WrapValue(value.Substring(0,i)), WrapValue(value.SubString(i+1))]}
    return string.Join(".", strings)
}
```

There's probably a nicer way to do this but this should work.

Tell me if there's actually a situation where that's valid in any RDBMS. Maybe it should allow escaped periods?

I sadly need period characters in names(aliases)

**Comment by ahmad-moussawi** [comment]
No actually sometimes you need to include the schema name, for example 

```sql
select sys.time_zone_info.name from sys.time_zone_info;
```
or 
```sql
select dbo.products.name, stock.products.name from ....
```
If you have few cases use the `Raw` family, like `FromRaw`, `WhereRaw` etc ..
or you can simply make your own compiler and override the `Wrap` method to fit your need

**Comment by Blanen** [comment]
Oh, ofcourse... Schema's Hmm.

I'm building a generic GUI-based query-builder so the cases are actually... infinite?

But the building-your-own-compiler thing might actually work. Thanks.

**Comment by ahmad-moussawi** [comment]
yes exactly, for the raw join check #128
