### ISSUE TITLE
Query.AsCount() not cumulative?

### ISSUE THREAD

**Issue by mrkvw** [sqlkata/querybuilder#135]
We are using version 1.0.0-beta-467 and have found an issue with the `AsCount()` method. When we call `Query.AsCount()`, subsequent calls to `Query.SelectRaw()` are not added to the `SELECT` statement. Is this by design?

Thanks!
Mark

**Comment by ahmad-moussawi** [comment]
@mrkvw I highly recommend to update to the latest version, 
yes this is by design, since aggregation query cannot return more than one value.

if you want to get other values use the normal selectRaw to build the count statement

```cs
db.Query("Users")
   .SelectRaw("Count(*) as count")
   .SelectRaw("other columns")
```

**Comment by mrkvw** [comment]
Great, thanks for the quick response!
