### ISSUE TITLE
Using AsUpdate method with nullable properties

### ISSUE THREAD

**Issue by mrkvw** [sqlkata/querybuilder#142]
Hi, we are trying to use `AsUpdate()` with a class that has nullable properties so we only update columns that have changed. This doesn't seem to be supported as it we get an `InvalidOperationException`. Is there plans to support this in the future?

Thanks!
Mark

**Comment by mrkvw** [comment]
Closing - it was a simple as adding a getter/settter to the class properties 👍

**Comment by ahmad-moussawi** [comment]
Hi Mark, could you give me more details about this case ?, even if you solved it
