### ISSUE TITLE
Extra space character appeared before JOINs.

### ISSUE THREAD

**Issue by springjazzy** [sqlkata/querybuilder#143]
Hi!

Thanks for great library. I had v.1.0.4 installed and after upgrade to 1.1.2 version several of my tests failed. I've noticed that extra space appeared before JOIN statements which didn't exists before. Since SqlKata is Sql Query Builder library I think that it is quite natural that there many tests that compare expected syntax to actual.

You can check it:
```
[TestMethod]
public void LeftJoinTest()
{
	Query query = new Query("test");
	query.LeftJoin("A", "test.FK", "A.PK");
	query.LeftJoin("B", "A.FK", "B.PK");
	Compiler c = new SqlServerCompiler();
	var sqlResult = c.Compile(query);

	var res = Regex.Replace(sqlResult.Sql, @"\r\n?|\n", " ");
	Console.WriteLine(res);
	Assert.IsFalse(res.Contains("  "));
}

[TestMethod]
public void JoinTest()
{
	Query query = new Query("test");
	query.Join("A", "test.FK", "A.PK");
	query.Join("B", "A.FK", "B.PK");
	Compiler c = new SqlServerCompiler();
	var sqlResult = c.Compile(query);

	var res = Regex.Replace(sqlResult.Sql, @"\r\n?|\n", " ");
	Console.WriteLine(res);
	Assert.IsFalse(res.Contains("  "));
}
```

BTW is there any change log?

Thanks!

**Comment by ahmad-moussawi** [comment]
@springjazzy yes actually some changes have been applied to the sql format, to make it easier to read especially for long queries.

At the moment we don't have a precise change log, you can check the commit diff as alternative.

**Comment by springjazzy** [comment]
It seems it is "as designed". I'm closing the issue.
