### ISSUE TITLE
After execute "InsertAsync" different values

### ISSUE THREAD

**Issue by PiotrFerenc** [sqlkata/querybuilder#145]
After execute "InsertAsync" 
![obraz](https://user-images.githubusercontent.com/30370747/46228307-f9809e00-c361-11e8-87e0-527ab31d056c.png)

![obraz](https://user-images.githubusercontent.com/30370747/46228320-030a0600-c362-11e8-868d-9a20244657a8.png)

Works when i comment this           
`  form["Owner"] = owner.Id;`

**Comment by ahmad-moussawi** [comment]
It would be very helpful if you can post the version, and the generated SQL, 
https://sqlkata.com/docs/execution/logging

**Comment by PiotrFerenc** [comment]
DB: MySql
SqlKata: 1.1.2
SqlKata.Execution 1.1.2
ASP Core 2.0
logging:
 ` INSERT INTO `animals` (`Name`, `Hair`, `Sex`, `Tattoo`, `ChipNumber`, `NumberVaccination`, `DateBirth`, `Width`, `AnimalTypeId`, `Breed`, `Marks`, `Owner`) VALUES ('', 123, 1, 1, '', '', '', '', 0, '', '', 'dff73a85-3a3c-42b6-899a-7ecaeacb0a50')`

**Comment by ahmad-moussawi** [comment]
It seems that the query is build correctly, could you share a code that contains a reproducible issue ?

**Comment by ahmad-moussawi** [comment]
closing since there is no reproducible case, please feel free to reopen if you have any news.
