### ISSUE TITLE
SQL Command compiler

### ISSUE THREAD

**Issue by chernihiv** [sqlkata/querybuilder#146]
I love this library, but it has lack of features (e.g. create/alter/drop table, columns, etc..)
Are you planning it on the roadmap?
Thank you.

**Comment by ahmad-moussawi** [comment]
Hi @chernihiv, no currently there is no near plan to support this, our focus is to sharp the querying features for the moment.

maybe we will address this in 2.0
#2 #138

**Comment by julian-di** [comment]
Any updated for this?

**Comment by ahmad-moussawi** [comment]
No not yet, I've found this library didn't try it personally https://fluentmigrator.github.io, but it seems it covers what needed here

**Comment by julian-di** [comment]
thanks i will look into it!
