### ISSUE TITLE
Need help converting many Dapper rows to List<IDictionary<string, object>>

### ISSUE THREAD

**Issue by MelroyBritto** [sqlkata/querybuilder#148]
Hello, 
I am trying to convert List of Dapper Rows to `List<IDictionary<string, object>>`  So while `(IDictionary<string, object>)query.Get().FirstOrDefault()` works perfectly fine,
`(List<IDictionary<string, object>>)query.Get();` fails with an exception _"Value cannot be null.
Parameter name: key"_, for testing purpose two records are returned and both the records are same with no nulls returned from the DB.  What am i doing wrong...

**Comment by MelroyBritto** [comment]
Sorry forgot to mention, I tried multiple approaches

FAILED
```
 var items = query.Get().Select(r => new { r.Key, r.Value }).ToDictionary(r => r.Key, r => r.Value);
 var Items1 = (from r in query.Get()
                      select new Dictionary<string, object>(r.Key, r.Vaue)).ToList();
```
So for now I am doing...
```
List<IDictionary<string, object>> dbItems = new List<IDictionary<string, object>>();
foreach (var dapperRow in query.Get())
{
     dbItems.Add((IDictionary<string, object>)dapperRow);
}
```
Is there a better way to achieve this.

**Comment by ahmad-moussawi** [comment]
You can use the `QueryFactory.GetDictionnary(Query query)` method, check https://github.com/sqlkata/querybuilder/blob/master/SqlKata.Execution/QueryFactory.Extensions.cs#L21-L26

**Comment by MelroyBritto** [comment]
Perfect!! Thanks for your help!!
