### ISSUE TITLE
SqlKata sends columns tagged as ReadOnly or DatabaseGenerated during the insert

### ISSUE THREAD

**Issue by aabragan** [sqlkata/querybuilder#149]
Currently I am sending my object into the insert. It works ok if I don't have any read only or generated columns. If I add a readonly or generated column then sql still sends it and the insert fails. I am using postgres connection (npgsql) and postgres compiler. Is there any way to do this? I tried using an expandoobject with only the properties i wanted to insert and I also tried a dictionary<string, object> but I get the following error. 

> column \"tenantuid\" is of type uuid but expression is of type text"

which tells me that it is not doing the order of the properties correctly for some reason. Any ideas?

**Comment by aabragan** [comment]
> One or more errors occurred. (42804: column "tenantid" is of type uuid but expression is of type text): AggregateException
> at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
> at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
> 
> at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
> at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
> at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
> at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
> at SqlKata.Execution.QueryExtensionsAsync.InsertAsync(Query query, IReadOnlyDictionary`2 values) in C:\projects\querybuilder\SqlKata.Execution\Query.Extensions.Async.cs:line 157
> at Platform.Data.Provider.Implementation.SqlDataProvider.Create[T](Object record, ILambdaContext context, IPlatformLogger logger) in D:\eci_source\MFG\Server\Projects\Platform.Data.Provider.Implementation\SqlDataProvider.cs:line 61
> at Platform.Data.Provider.Lambda.Function.InvokeDataProviderMethod(String operation, Type type, Object data, ILambdaContext context, IDataProvider dataProvider, IPlatformLogger logger) in D:\eci_source\MFG\Server\Projects\Platform.Data.Provider.Lambda\Function.cs:line 193
> at CallSite.Target(Closure , CallSite , Object )
> at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
> at Platform.Data.Provider.Lambda.Function.FunctionHandler(DataOperationRequest input, ILambdaContext context) in D:\eci_source\MFG\Server\Projects\Platform.Data.Provider.Lambda\Function.cs:line 118

**Comment by aabragan** [comment]
Sample data object (converted to json for easy reading)

```
{
    "jobcode": "22345-67-89",
    "partcode": "AB1000",
    "partdescription": "Complete Test Part",
    "tenantuid": "70efb023-992d-4532-9f9b-ac7adba5bd59"
}
```

**Comment by ceastwood** [comment]
@aabragan Could you please provide the query object you build and pass to sqlkata at 

Platform.Data.Provider.Implementation.SqlDataProvider.Create[T](Object record, ILambdaContext context, IPlatformLogger logger) in D:\eci_source\MFG\Server\Projects\Platform.Data.Provider.Implementation\SqlDataProvider.cs:line 61

**Comment by ceastwood** [comment]
@aabragan 

Aside from a couple of other things, 
I believe you may be sending a string representation of the Guid to the database instead of an actual Guid. Please see the below code which shows a working insert, and a failing insert with the same exception that you are having.



            var conn = new NpgsqlConnection(cs);
            conn.Open();

            var dict = new Dictionary<string, object>();
            dict.Add("cooluuid", Guid.NewGuid());
            
            var compiler = new PostgresCompiler();
            var factory = new QueryFactory(conn, compiler);
            var query = factory.Query("some_table");
            var affected = query.Insert(dict);
            //yay the above works

            //now we change the value to a string representation of a guid.
            var stringGuid = Guid.NewGuid().ToString();
            dict["cooluuid"] = stringGuid;
            affected = query.Insert(dict); //fails on this line, type uuid but expression is of type text

**Comment by aabragan** [comment]
The Json above is a representation of the data I am sending. It is sent in as IReadOnlyDictionary<string, object>

here is an article I found about this issue 
https://github.com/npgsql/npgsql/issues/1304

**Comment by aabragan** [comment]
Here is the insert method
```
public async Task<dynamic> Create<T>(IReadOnlyDictionary<string, object> record, ILambdaContext context, IPlatformLogger logger)
{
	var uid = GetUid(record);
	if (uid == Guid.Empty)
	{
		return null;
	}

	using (var dbConnection = new NpgsqlConnection(_connectionString))
	{
		dbConnection.Open();
		await logger.Log(LogLevel.Debug, "Data: Connected to SQL instance");
		await SetDatabaseSchema(dbConnection);
		await logger.Log(LogLevel.Debug, $"Data: Schema changed to {_schema}");
		var query = GenerateBaseQuery<T>(dbConnection, logger);
		await logger.Log(LogLevel.Debug, $"Data:  {JsonConvert.SerializeObject(record)}");
		await query.InsertAsync(record);
		await logger.Log(LogLevel.Debug, "Data: Record inserted");
		dbConnection.Close();
	}

	return record;
}
```

**Comment by aabragan** [comment]
> @aabragan
> 
> Aside from a couple of other things,
> I believe you may be sending a string representation of the Guid to the database instead of an actual Guid. Please see the below code which shows a working insert, and a failing insert with the same exception that you are having.
> 
> ```
>         var conn = new NpgsqlConnection(cs);
>         conn.Open();
>         
>         var compiler = new PostgresCompiler();
>         var factory = new QueryFactory(conn, compiler);
>         var query = factory.Query("some_table");
> 
>         var dict = new Dictionary<string, object>();
>         dict.Add("cooluuid", Guid.NewGuid());
>         var affected = query.Insert(dict);
>         //yay the above works
> 
>         //now we change the value to a string representation of a guid.
>         var stringGuid = Guid.NewGuid().ToString();
>         dict["cooluuid"] = stringGuid;
>         affected = query.Insert(dict); //fails on this line, type uuid but expression is of type text
> ```

Thanks! I will play around with the deserializer to see if there is something funky going on.

**Comment by ahmad-moussawi** [comment]
@aabragan is this still an issue for you ?
