### ISSUE TITLE
N Prefix for SQL Server

### ISSUE THREAD

**Issue by calvinxli** [sqlkata/querybuilder#154]
Is there currently support for the N prefix? Something like the example below:
`INSERT INTO [Example] ([name]) VALUES (N'example')`

If not, is there any plans to add support for this feature?

**Comment by ahmad-moussawi** [comment]
for more info https://stackoverflow.com/questions/144283/what-is-the-difference-between-varchar-and-nvarchar

**Comment by ceastwood** [comment]
@calvinxli @ahmad-moussawi 

I've been behind so sorry about my timeliness on this--

- All strings in c#/.net are unicode.
- If you inline (literal) your value, then you would be responsible for designating the N' prefix or not.
- When using the execution library, Dapper, or many if not all of the other ORM's out there, the string values are parameterized-- thus ending up at the server with the N' prefix.

A small example below with trace captured in Sql Profiler--

Code portion:
```var compiler = new SqlServerCompiler();
var query = new Query("dbo.Matter")
    .Select("*")
    .Where("MatterNumber", "1234.9876123-01");
var result = compiler.Compile(query);
var connectionString = "Data Source=xxxxxx;Integrated Security=True;Initial Catalog=xxxxx";
using (var sql = new SqlConnection(connectionString))
{
    sql.Query(result.Sql, result.NamedBindings);
}
```

Sql Profiler trace:
`exec sp_executesql N'SELECT * FROM [dbo].[Matter] WHERE [MatterNumber] = @p0',N'@p0 nvarchar(4000)',@p0=N'1234.9876123-01'`

So, unless you were to manually add a SqlParameter and designate the parameter be sent as varchar, it's already going as unicode.

**Comment by ahmad-moussawi** [comment]
@ceastwood thanks for the feedback, so we can close this issue since there is nothing to do from our side, right ?

**Comment by ceastwood** [comment]
@ahmad-moussawi  yes sir, it's the program implementers side.

**Comment by ahmad-moussawi** [comment]
Thanks for the helpful input !
