### ISSUE TITLE
Using function instead of Tablename

### ISSUE THREAD

**Issue by punssoma** [sqlkata/querybuilder#156]
For SqlServerCompiler, How to create query for fetching data using user defined functions like

`SELECT  [ItemName], [ParentItem], [NetQuantity], FROM GetBomData ('ABC','100')`

I tried something like this 

`var query = new Query("GetBomData ('ABC','100')").Select("ItemName", "ParentItem", "NetQuantity")`

which generates query like
`SELECT  [ItemName], [ParentItem], [NetQuantity], FROM [GetBomData ('ABC','100')]` 

i.e function name within square brackets which is not a valid query and gives an error
`Invalid object name 'GetBomData ('ABC','100')'.`

**Comment by ahmad-moussawi** [comment]
Use `FromRaw` https://sqlkata.com/docs/from#from-a-raw-expression
