### ISSUE TITLE
add strong name

### ISSUE THREAD

**Issue by InvalidCast44** [sqlkata/querybuilder#158]
hi! i really would like to use your library, but i can't, as ours are strong named, so they need to use strong named libraries.

would you mind doing it?

thanks

**Comment by InvalidCast44** [comment]
i just saw dapper is not strong named...
i guess i just have to find another library 
thanks

**Comment by InvalidCast44** [comment]
and i just saw that dapper has a strong named version, also available on nuget.org :-)
AFAIK, it's official

so what i've done for the moment is:
- cloning your repo
- replacing dapper nuget reference by the signed one
- signing the assemblies
- putting resulting nuget packages in our feed (above nuget.org in our nuget.config)

so it works, and we will be able to get pack to official packages as soon as you signed your assemblies :-)

**Comment by aydjay** [comment]
Just use the strong namer nuget package: https://www.nuget.org/packages/strongnamer

**Comment by InvalidCast44** [comment]
you're the man!
it works well
the 2 assemblies in the nuget cache are still not signed (that's normal) but the 2 in the output folder of my app are signed!
the key used to sign seems to be the same for everay assembly, but that does not really matter :-)

thank you so much

**Comment by ahmad-moussawi** [comment]
That's great, so I think we can close this issue now, right ?

**Comment by InvalidCast44** [comment]
done :-)
