### ISSUE TITLE
MySQL Last Insert Id

### ISSUE THREAD

**Issue by cwsterling** [sqlkata/querybuilder#164]
Hello,

I'm having an issue with the Last Insert ID with mysql.  The error I'm getting is: MySqlException: Unknown column 'last_insert_id' in 'field list'.

I'm running .net core, MySql.Data version is 8.0.13. The query itself is running as the record in the DB is being created.  The command I'm running is:

`var result = db.Query(TableName).InsertGetId<int>(dict);`

where dict is a IReadOnlyDictionary of the column name and the value. Is there anything more I can get to help debug this problem?

**Comment by ahmad-moussawi** [comment]
#165

**Comment by cwsterling** [comment]
I'll grab the nightly build this evening when I"m working on my code and let you know if I run into anything else!

I did find one more bug where it mentions an invalid number of parameters. When I can get more info on how to debug and a stacktrace, I'll submit another ticket. Thank you SO much for this project.

**Comment by ahmad-moussawi** [comment]
Thanks for your feedback, yes please fill another issue so we can track it better, thanks !

**Comment by cwsterling** [comment]
I'm going to close this. I validated the fix
