### ISSUE TITLE
Skip-Take problem

### ISSUE THREAD

**Issue by saeidjoker** [sqlkata/querybuilder#166]
This first query:
`SELECT TOP (15) * FROM [AirlineLookups] ORDER BY [airlineId]`
is built using:
`new Query("Airlines").OrderBy('airlineId').Skip(0).Take(15)`

And this is the result-set:
![11111111111111](https://user-images.githubusercontent.com/20520614/48699755-73653300-ebff-11e8-9750-df8cbe0fd1fd.png)

This second query:
`SELECT * FROM (
	SELECT *, ROW_NUMBER() OVER (ORDER BY [airlineId]) AS [row_num] FROM [AirlineLookups]
) AS [results_wrapper] 
WHERE [row_num] BETWEEN 16 AND 30`
is built using:
`new Query("Airlines").OrderBy('airlineId').Skip(15).Take(15)`

And this is the result-set:
![2222222222222](https://user-images.githubusercontent.com/20520614/48699814-9bed2d00-ebff-11e8-8d0b-66e595aa9208.png)

As you can see, the record with ABY in its Value column is in both result-sets.
But the value is unique and I wanted to report this issue, because I'm really interested in this library.

**Comment by ahmad-moussawi** [comment]
Hi @saeidjoker, the query is compiled as expected, and the problem here is you are not choosing the correct columns for the `order by` clause. using another column would avoid this.
