### ISSUE TITLE
skip-take with joined tables

### ISSUE THREAD

**Issue by saeidjoker** [sqlkata/querybuilder#167]
When we use 
`
new Query("Airways")
                  .Join(new Query("Airports").As("f"), a => a.On("f.Id", "Airways.FromId"))
                  .Join(new Query("Airports").As("t"), a => a.On("t.Id", "Airways.ToId"))
                  .Select("Airways.*", "f.*", "t.*");
`
to build a query, then using Skip() and Take() on it throws the following exception:

> SqlException: The column 'Id' was specified multiple times for 'results_wrapper'.

**Comment by ahmad-moussawi** [comment]
Check 
https://stackoverflow.com/questions/1058606/sql-2005-the-column-was-specified-multiple-times
and 
https://dba.stackexchange.com/questions/190279/the-column-was-specified-multiple-times

**Comment by saeidjoker** [comment]
The problem is with the Skip and Take. Skip and Take does not operate with Multiple Ids in the query

**Comment by ceastwood** [comment]
@saeidjoker can you please send a repro of the query that faults? I'm not sure I see what you mean

**Comment by ceastwood** [comment]
The one in the OP is because you are likely selecting multiple columns named 'Id' which is a SQL issue before this lib
