### ISSUE TITLE
OrWhereXX genrerates AND condition

### ISSUE THREAD

**Issue by for7raid** [sqlkata/querybuilder#170]
db.Query("Users").WhereFalse("IsActive").OrWhereNull("LastActivityDate");
produced
SELECT * FROM [Users] WHERE [IsActive] = 0 AND [LastActivityDate] IS NULL

but shoud by OR

the same for OrWhereFalse/true

db.Query("Users").WhereFalse("IsActive").OrWhereTrue("LastActivityDate");
produced
SELECT * FROM [Users] WHERE [IsActive] = 0 AND [LastActivityDate] = 1.

But 
db.Query("Users").WhereFalse("IsActive").OrWhere("LastActivityDate", 10);
gets good query
SELECT * FROM [Users] WHERE [IsActive] = 0 OR [LastActivityDate] = 10.

**Comment by ahmad-moussawi** [comment]
Thanks for reporting, could you submit a failed unit test PR ?

**Comment by for7raid** [comment]
update: OrWhereNull works fine
OrWhereTrue/OrWhereFalse - fails

**Comment by for7raid** [comment]
[Fact]
        public void OrWhereFalse()
        {
            var query = new Query("Table").Where("MyCol", "abc").OrWhereFalse("IsActive");

            var c = Compile(query);

            Assert.Equal("SELECT * FROM [Table] WHERE [MyCol] = 'abc' OR [IsActive] = cast(0 as bit)", c[0]);

            Assert.Equal("SELECT * FROM \"Table\" WHERE \"MyCol\" = 'abc' OR \"IsActive\" = false", c[2]);

        }

        [Fact]
        public void OrWhereTrue()
        {
            var query = new Query("Table").Where("MyCol", "abc").OrWhereTrue("IsActive");

            var c = Compile(query);

            Assert.Equal("SELECT * FROM [Table] WHERE [MyCol] = 'abc' OR [IsActive] = cast(1 as bit)", c[0]);

            Assert.Equal("SELECT * FROM \"Table\" WHERE \"MyCol\" = 'abc' OR \"IsActive\" = true", c[2]);

        }

        [Fact]
        public void OrWhereNull()
        {
            var query = new Query("Table").Where("MyCol", "abc").OrWhereNull("IsActive");

            var c = Compile(query);

            Assert.Equal("SELECT * FROM [Table] WHERE [MyCol] = 'abc' OR [IsActive] IS NULL", c[0]);

            Assert.Equal("SELECT * FROM \"Table\" WHERE \"MyCol\" = 'abc' OR \"IsActive\" IS NULL", c[2]);

        }

**Comment by ahmad-moussawi** [comment]
Fixed now, you can get the latest package from the nightly build, or wait for the next release on nuget.
Thanks
