### ISSUE TITLE
Oracle?

### ISSUE THREAD

**Issue by jeffdoolittle** [sqlkata/querybuilder#171]
How close is the Oracle version to being complete and included in an updated Nuget package?

**Comment by ahmad-moussawi** [comment]
Hi jeff, the release is pretty ready, but i am still validating some stuff, hopefully in the beginning of the next year it will be ready.
You can always use the nightly feed, it already contains the Oracle Compiler.
https://sqlkata.com/docs/#nightly-builds

**Comment by alexeynovitskiy** [comment]
Hi @ahmad-moussawi . I am trying to use sqlkata for Oracle too.

When I use your current git repository it works for me so far.

`        private class OracleSqlServerCompiler : SqlServerCompiler
        {
            public OracleSqlServerCompiler()
            {
                this.parameterPlaceholderPrefix = ":p";
            }

            public override string WrapValue(string value)
            {
                return value;
            }
        }
`

But when I use your nuget 1.1.3 build the parameterPlaceholderPrefix field is not accessible from the class inherited from SqlServerCompiler.

Any idea why?

Thanks,
Alexey

**Comment by ahmad-moussawi** [comment]
HI @alexeynovitskiy, please use the nightly build feed to get the master branch package
```
Install-Package SqlKata -Version 1.1.3 -Source https://www.myget.org/F/sqlkata/api/v3/index.json
```
A side question why you want to access the `parameterPrefixPlaceholder` ?

**Comment by alexeynovitskiy** [comment]
Hi @ahmad-moussawi , thanks for the quick response.
I want to use : instead of @ since Oracle has a different syntax for parameters.

**Comment by ahmad-moussawi** [comment]
In the latest version, it's already using the `:` as prefix, so no need to change it by yourself.

**Comment by alexeynovitskiy** [comment]
I just pulled the latest repository and checked it using the master branch.
The following unit test failed.

```
        [Fact]
        public void OracleMyTest()
        {
            var compiler = new SqlServerCompiler();
            var query = new Query("Users").Where("Id", 1).Where("Status", "Active");
            var result = compiler.Compile(query);
            Assert.Contains(":p", result.Sql);
        }

```

What branch do you use to release the nightly build?

**Comment by ahmad-moussawi** [comment]
Off course it will fail since naming the method "Oracle" is not sufficient :), you should use the Oracle compiler instead of SqlServer one :)

**Comment by alexeynovitskiy** [comment]
I didn't expect that naming the method "Oracle" is sufficient. I didn't know you'd already supported oracle.
This is why I wanted to write my class inherited from SqlServerCompiler and make it work for Oracle.
You should update your git description.
 
![image](https://user-images.githubusercontent.com/19430324/50443794-92956580-090d-11e9-985d-c3a4cc941386.png)

 Btw, do you think you need to use `"` for OpeningIdentifier and ClosingIdentifier?

This query
`var query = new Query("Users").Where("Users.Id", 1).Where("Users.Status", "Active");`
will be compiled to
`SELECT * FROM "Users" WHERE "Users"."Id" = :p0 AND "Status" = :p1`

Will the result sql statment get executed sucessfully ?

**Comment by ahmad-moussawi** [comment]
ohh sorry, I thought you made it by mistake, yes Oracle compiler was supported by @tlaguz and another version by @mathijs-dumon and they will be available in 2019.

**Comment by alexeynovitskiy** [comment]
No problem. What about using " for OpeningIdentifier and ClosingIdentifier?
When I use database or table alias to build a query I get a query that's not executed successfully by Oracle.
I can solve this problem by creating my class and override Compiler.WrapValue, but it would be much better if I could use without customization.

@tlaguz , @mathijs-dumon any help? maybe I do something wrong?

**Comment by tlaguz** [comment]
Which version of Oracle do you use?

> `SELECT * FROM "Users" WHERE "Users"."Id" = :p0 AND "Status" = :p1`
> 
> Will the result sql statment get executed sucessfully ?

Yes. How does your schema look like? Regarding double quotation marks: https://stackoverflow.com/questions/563090/what-exactly-do-quotation-marks-around-the-table-name-do
I believe it's expected to use them in case the tables were created with "TableName" syntax. You have to remember about proper capitalization though.

**Comment by ahmad-moussawi** [comment]
Oracle uses the `"` as keyword identifier, so no need to change it, check https://stackoverflow.com/a/1162391/1104402 for more info.
If the problem persist, I prefer if you can open a new issue for it, so we can track it better.

**Comment by alexeynovitskiy** [comment]
@ahmad-moussawi , @tlaguz  thank you, it works, capitalization was the reason.
Do you have any more precise than the 2019 year estimation when it is going to come out?

**Comment by ahmad-moussawi** [comment]
Version 1.1.4 is now released and available on NuGet.
