### ISSUE TITLE
The type or namespace name 'Execution' does not exist in the namespace 'SqlKata'

### ISSUE THREAD

**Issue by collinoswalt** [sqlkata/querybuilder#177]
I'm trying to use SqlKata.Execution to access the QueryFactory. However, I get the error `The type or namespace name 'Execution' does not exist in the namespace 'SqlKata'` when I attempt to do `using SqlKata.Execution;`. What is the correct namespace for the QueryFactory class?

**Comment by ceastwood** [comment]
@collinoswalt

QueryFactory is definitely in the SqlKata.Execution namespace (https://github.com/sqlkata/querybuilder/blob/master/SqlKata.Execution/QueryFactory.cs)[link]

Can you confirm the installed versions of SqlKata and SqlKata.Execution packages for your project. Have you done a 'dotnet restore' (if .net core/standard) as well?
