### ISSUE TITLE
Unnecessary brackets in query

### ISSUE THREAD

**Issue by avlcodemonkey** [sqlkata/querybuilder#178]
This issue is somewhat related to #128 and #132.  I'm writing queries for MS SQL server, trying to use fully qualified names with square brackets since I'm querying multiple schemas.  Using the raw function variants seem to work as expected (ie `.FromRaw`).  However, I'm running into issues when using the non-raw versions (ie `.From`)

Let's say we're querying tables named `[dbo].[OrderItem]` and `[ref].[Product]`.  Based on the docs, I would expect the compiler to see that square brackets are correct for MS SQL server.  

The code is something like this. I'm paraphrasing so syntax may not be perfect.
```
Query.From("[dbo].[OrderItem]");
Query.Join("[ref].[Product]", j => j.WhereRaw("[dbo].[OrderItem].[ProductID] = [ref].[Product].[ID]"), "INNER JOIN")
```

So I would expect:
```
SELECT ... FROM [dbo].[OrderItem]
INNER JOIN [ref].[Product] ON [dbo].[OrderItem].[ProductID] = [ref].[Product].[ID]
```
but instead it creates
```
SELECT ... FROM [[dbo]]].[[OrderItem]]]
INNER JOIN [[ref]]].[[Product]]] ON [dbo].[OrderItem].[ProductID] = [ref].[Product].[ID]
```
The WhereRaw does not change the brackets in the ON predicate.  But the Join and From do change the values incorrectly.  I can use a FromRaw to avoid that one issue, but for Join there isn't a way to specify the table name in a raw way.

Any suggestions?

**Comment by ceastwood** [comment]
@avlcodemonkey

On my phone at the moment, but at first glance try 

Query.Join("Product AS ref", j => ...

**Comment by ahmad-moussawi** [comment]
Yes this is by design, you don't have to pass the keyword identifiers (square brackets for sql server) when using non raw methods

**Comment by ceastwood** [comment]
@avlcodemonkey 

Just threw this together, so sorry if there are any small typo's or anything but:

[Here is a .NET fiddle](https://dotnetfiddle.net/iJdDd0)

**Comment by avlcodemonkey** [comment]
Thanks for the rapid response guys.  Sounds like I was misunderstanding proper usage.  I'll adjust my code accordingly.
