### ISSUE TITLE
Invalid SQL when using COUNT with DISTINCT

### ISSUE THREAD

**Issue by asyncerror** [sqlkata/querybuilder#186]
Invalid SQL is generated when using COUNT in conjunction with DISTINCT for MSSQL.

For Instance code:
`q.From("my_table").Distinct().AsCount()`

Will generate:
`SELECT COUNT(DISTINCT *) AS [count] FROM [my_table]`

I would be grateful if you could prioritize a fix.

**Comment by JordiPerello** [comment]
Same issue that [#185](https://github.com/sqlkata/querybuilder/issues/185)

**Comment by ahmad-moussawi** [comment]
We will use this approach when selecting `*` or `multiple columns` or when we have a group by in the query.

**Comment by asyncerror** [comment]
@ceastwood Valuable information about the Count, thanks.

But, my query is more complex than the example, I'm using INTERSECT for multiple results, then it also has a JOIN. I also use the same query for Paginate and ForPage. I'm having difficulty adapting it to the example you provided, but I'll keep trying until have a fix.

**Comment by ceastwood** [comment]
@asyncerror  I am also going to try to put together an example for with the Paginate and ForPage

**Comment by ceastwood** [comment]
@asyncerror  
I've tried to show a contrived example of how to make things work for now-- and if you would still like to provide the structure of your query I can help try and adapt it. That being said, the workaround isn't exactly clean 😄.  Personally, on queries like this I would be generating a temp table with a sort key and query the pagination from that table.

The following example should return 2 rows as-is, and if you uncomment the where statement on the distinctQuery it will reduce to 1, showing the join and where filter.  The overall of the filtering is to find rows that start with c and end with n with their ColumnA existing in ColumnATypes

Lastly, I wrote out the queries a little verbosely to try and show the pieces.

SQL Test Schema & Data:
```
USE [scratch]; --need to update for your test database
SET NOCOUNT ON;

IF OBJECT_ID('[dbo].[BaseTable]') IS NULL
BEGIN

CREATE TABLE [dbo].[BaseTable] (BaseTableId int PRIMARY KEY IDENTITY(1,1), ColumnA int, ColumnB int, ColumnC nvarchar(50))

INSERT INTO [dbo].[BaseTable] (ColumnA, ColumnB, ColumnC) VALUES (10, 100, 'Red') --1
INSERT INTO [dbo].[BaseTable] (ColumnA, ColumnB, ColumnC) VALUES (10, 101, 'Maroon') --2
INSERT INTO [dbo].[BaseTable] (ColumnA, ColumnB, ColumnC) VALUES (10, 102, 'Scarlet') --3
INSERT INTO [dbo].[BaseTable] (ColumnA, ColumnB, ColumnC) VALUES (10, 103, 'Crimson') --4
INSERT INTO [dbo].[BaseTable] (ColumnA, ColumnB, ColumnC) VALUES (10, 103, 'Crimson') --5 --this duplicate is on purpose to show the distinct filtering

INSERT INTO [dbo].[BaseTable] (ColumnA, ColumnB, ColumnC) VALUES (20, 100, 'Blue') --6
INSERT INTO [dbo].[BaseTable] (ColumnA, ColumnB, ColumnC) VALUES (20, 101, 'Cobalt') --7
INSERT INTO [dbo].[BaseTable] (ColumnA, ColumnB, ColumnC) VALUES (20, 102, 'Cyan') --8
INSERT INTO [dbo].[BaseTable] (ColumnA, ColumnB, ColumnC) VALUES (20, 103, 'Teal') --9

END

IF OBJECT_ID('[dbo].[ColumnATypes]') IS NULL
BEGIN
	CREATE TABLE [dbo].[ColumnATypes] ([ColumnA] int NOT NULL, [Description] nvarchar(50))
	INSERT INTO [dbo].[ColumnATypes] VALUES (10, 'Reds')
	INSERT INTO [dbo].[ColumnATypes] VALUES (20, 'Blues')
END
```

The (not-so-pretty) query setup:
```
IDbConnection conn = new SqlConnection("Data Source=xxxSomeDatabaseServerxxx;Integrated Security=True;Initial Catalog=scratch");
var qf = new QueryFactory(conn, new SqlServerCompiler());

var filterQuery = new Query("dbo.BaseTable")
    .Select("ColumnA", "ColumnB")
    .Intersect(with => with.Select("ColumnA", "ColumnB")
        .From("dbo.BaseTable")
        .WhereLike("ColumnC", "C%"))
    .Intersect(with => with.Select("ColumnA", "ColumnB")
        .From("dbo.BaseTable")
        .WhereLike("ColumnC", "%n"));
                

var distinctQuery = new Query()
    .From(filterQuery, "source")
    .Select("source.ColumnA","source.ColumnB")
    .Join("dbo.ColumnATypes", "source.ColumnA", "ColumnATypes.ColumnA")
        //.Where("ColumnATypes.Description", "Blues") //uncomment to bring total count to 1, removes the 'Reds' result
    .Distinct();

var workaroundQuery = new Query()
    .Select("*")
    .From(distinctQuery, "workaround");

var xquery = qf.FromQuery(workaroundQuery);
var result = xquery.Paginate(1, 1);
```

Tested against a live sql2016 server

**Comment by asyncerror** [comment]
@ceastwood I appreciate your dedicated time in trying a solution, it worked perfectly.

I was not understanding how I could do this, and this last part was decisive to make my queries work.
```
var workaroundQuery = new Query()
    .Select("*")
    .From(distinctQuery, "workaround");
```

Thanks man.

I'm passionate about how this library works. 
I can not imagine ever dealing with huge string of queries again.
