### ISSUE TITLE
Extension points?

### ISSUE THREAD

**Issue by johnknoop** [sqlkata/querybuilder#187]
Do you provide any extension points for people to write plugins? What I would love to do is taking some inspiration from the MongoDB C# library in terms of updates.

```csharp
db.Query<User>("Users")
  .Where(u => u.Id == 3)
  .Update(x => x
    .Set(u => u.Name, "My new name")
    .Increase(u => u.Score, 5)
);
```
This would yield the following SQL
```sql
UPDATE Users SET Name = 'My new name', Score = Score + 5 WHERE Id = 3
```

Also, are you planning to add async versions of Get/Update/Delete/Insert?

**Comment by ahmad-moussawi** [comment]
Interesting, however I am trying to avoid the generic support at this phase, 
Something like this would be really interesting 

```cs
db.Query("Users").Where("Id", 3)
  .Update(q => 
       q.Set("Name", "New Name")
          .Increments("Score")
  )
```

You can always write your extensions methods, and use the **internal** (but public) like `AddComponent()` method to add/modify query clauses, check the current source code for more details.

Async version is already supported.

**Comment by johnknoop** [comment]
Yeah, I think I agree with keeping the generic bit out of this, because mapping property names to column names isn't really what this library focuses on.

I'll have a look at AddComponent and see what I can do with it.

Thanks
