### ISSUE TITLE
Oracle compiler - Remove sealed modifier

### ISSUE THREAD

**Issue by Thowk** [sqlkata/querybuilder#188]
That's great SqlKata is moving forward with Oracle support.

I would like to ovveride **CompileInserQuery**, using **OracleCompiler** in my project. Currently it is not possible because class is marked as **sealed**.

`namespace SqlKata.Compilers
{    public sealed class OracleCompiler : Compiler`

Is there any good reason to use sealed there? I think it's too restrictive right now.

**Comment by ahmad-moussawi** [comment]
No I don't think there is a valid reason, @tlaguz can you confirm please ?

Just for curiosity what is the purpose for the override, happy to get more feedback about that.

**Comment by tlaguz** [comment]
There is no reason. If it wasn't sealed we wouldn't get this feedback. It should be fixed in the compiler itself.

**Comment by ceastwood** [comment]
@ahmad-moussawi  I looked into this, and I think I can resolve the issue and clean up the CompileInsertQuery method (looks like it could use some help 😄).

@tlaguz @Thowk 
Is there any preference whether we should just work out the from dual union all, or should this condition transform into a

[Insert ALL statement](https://www.techonthenet.com/oracle/questions/insert_rows.php)

**Comment by Thowk** [comment]
@tlaguz OK. But then, why **SqlServerCompiler** is NOT marked as **sealed**? 😄
Still I think it should be allowed to inherit from this classes.

Thank you all, for replies.

**Comment by ceastwood** [comment]
@Thowk  I'm going to close this issue and create a new one to track the issue with the generated insert.
