### ISSUE TITLE
OracleCompiler generates invalid multiple row insert

### ISSUE THREAD

**Issue by ceastwood** [sqlkata/querybuilder#192]
Given the query
```cs
db.Query(string table).AsInsert(IEnumerable<string> columns, IEnumerable<IEnumerable<object>> valuesCollection, bool returnId = false);
```
Compiles to invalid sql for oracle
```sql
INSERT INTO "mtable" ("one", "two") VALUES (3348, 0), (3348, 1), (3348, 2)
```

Implement using [from dual union all](https://stackoverflow.com/questions/39576/best-way-to-do-multi-row-insert-in-oracle).

**Comment by ceastwood** [comment]
@tlaguz @thowk

If either of you have a chance, please take a look at branch issue-192
[issue-192 tree](https://github.com/sqlkata/querybuilder/tree/issue-192)

Not done with refactoring I don't think but the concept is there and the unit test (checked the sql in sql fiddle for oracle) passes.

Thanks.

**Comment by ceastwood** [comment]
Once I get a chance, I may boot up a docker container and test-- but that may not be right away

**Comment by mathijs-dumon** [comment]
Also just needed this, so bumping this. I didn't check the issue list first and I actually created my own tests+fix for this.

could I assist in getting this accepted?

**Comment by mathijs-dumon** [comment]
@ahmad-moussawi ping

**Comment by mathijs-dumon** [comment]
I created a new PR with my approach (slightly different) as the branch proposed here is rather old.
