### ISSUE TITLE
SQLite compiler generates invalid UNION statement

### ISSUE THREAD

**Issue by andrejpanjan** [sqlkata/querybuilder#194]
For this example
```
var phones = new Query("Phones");
var laptops = new Query("Laptops");
var mobiles = laptops.Union(phones);
```
SQLite compiler generates

`SELECT * FROM "Laptops" UNION (SELECT * FROM "Phones")`

which is not valid SQLite statement. A valid one is without parentheses

`SELECT * FROM "Laptops" UNION SELECT * FROM "Phones"`

**Comment by ceastwood** [comment]
@andrejpanjan  I believe that @ahmad-moussawi has committed a fix for this-- I'm about to add just one or two Assert statements for Sqlite in the tests as well.

You should be able to utilize the updated version from MyGet.

**Comment by andrejpanjan** [comment]
It works. Thanks.
