### ISSUE TITLE
.Net Core Support

### ISSUE THREAD

**Issue by Omzig** [sqlkata/querybuilder#197]
Please consider .net core support.

**Comment by tlaguz** [comment]
Library already supports

> .NETStandard 1.0
NETStandard.Library (>= 1.6.1)

**Comment by vip32** [comment]
netstandard 2.0 ist the way to go, also for the coming .net 5
any reason why netstandard 2.0 is not the target framework and 1.0 is still being used?

**Comment by ahmad-moussawi** [comment]
isn't all netstandard1.0 packages are also supported in netstandard2.0 too?

**Comment by vip32** [comment]
that's right, but please consider this MS recommendation:
'targeting lower .NET Standard versions introduces a number of support
dependencies. If your project targets .NET Standard 1.x, we recommend that
you *also* target .NET Standard 2.'

or this one
'Use netstandard2.0 to share code between .NET Framework and all other
implementations of .NET.'

from https://docs.microsoft.com/en-us/dotnet/standard/net-standard

by switching to 2.0 you will be safe and probably it is just a change in
the targetframework (no code)
