### ISSUE TITLE
Mixing `SUM` with other columns

### ISSUE THREAD

**Issue by Sharparam** [sqlkata/querybuilder#203]
It doesn't seem possible to have a `SUM` in a `SELECT` column list together with other columns (unless you hardcode it with `SelectRaw`), is this correct?

Consider this query:

```sql
SELECT GroupId, SUM(Age)
FROM People
GROUP BY GroupId
```

I can only find `AsSum` on the query object, but this makes it *only* select a `SUM`, and discards any other columns that have been selected with `Select()`.

It also requires an alias on the `SUM`, but that's a minor thing.

[Here's](https://sqltest.net/#464240) an example in MySQL.

**Comment by ceastwood** [comment]
@Sharparam  

at present-- [SqlKata Documentation](https://sqlkata.com/docs/select), about half-way down the page look for the header 'Raw'. 

```csharp
var query = new Query("People")
                .Select("GroupId")
                .SelectRaw("SUM(Age)")
                .GroupBy("GroupId");
```
Produces 
```sql
SELECT `GroupId`, SUM(`Age`) FROM `People` GROUP BY `GroupId`
```

**Comment by Sharparam** [comment]
Yeah, anything can be done with `Raw` functions of course. But this foregoes the reason you'd be using SqlKata in the first place rather than writing raw SQL queries: automatically adapting to the target SQL server and whatnot. Backticks won't work in MSSQL for example (by default anyway).

**Comment by SilentLux** [comment]
@Sharparam I agree with you that the main aggregate functions should be implemented inside SqlKata. But as long as we have to use SelectRaw, at least the string you pass here will also be resolved by the engine and any part enclosed in brackets [] will be translated into implementation specific identifiers. See https://sqlkata.com/docs/select#identify-columns-and-tables-inside-raw

**Comment by ahmad-moussawi** [comment]
Really nice idea, we are working on a template parser that can help in many situations, like date time manipulation, string functions and many more, we can implement this once the parser will be ready.

**Comment by asherber** [comment]
I'm interested in this as well. The more I can do without `SelectRaw`, the happier I am.

Like the OP, I would love to do something like:

```csharp
var q = new Query("foo")
    .Select("bar")
    .AsMax("baz")
    .GroupBy("bar");

// SELECT [bar], MAX([baz]) AS [max] FROM [foo] GROUP BY [bar]
```

**Comment by ahmad-moussawi** [comment]
Now you can use the `SelectAggregate` #617
