### ISSUE TITLE
Support for `CASE`

### ISSUE THREAD

**Issue by Sharparam** [sqlkata/querybuilder#204]
It would be nice to have support for writing `CASE` clauses in queries. In select statements for example:

```sql
SELECT
  CASE type_id
  WHEN 0 THEN 'some value'
  WHEN 1 THEN 'some other value'
  ELSE 'a default value' END
```

and:

```sql
SELECT
  CASE
  WHEN type_id = 0 THEN 'type is 0'
  WHEN other_thing = 'foo' THEN 'some other condition is true'
  ELSE 'default value again' END
```

Not sure how much work it would be to add it, I might try to look into how it could be added if I have some free time.

Maybe with syntax such as:

```csharp
new Query("Table")
  .SelectCase(
    "type_id",
    cb => cb.When(0, "some value").When(1, "some other value").Else("a default value"))
```

and:

```csharp
new Query("Table")
  .SelectCase(cb => cb
    .When("type_id", 0, "type is 0")
    .When("other_thing", "foo", "some other condition is true")
    .Else("default value again"))
```

(Where `cb` above is some kind of `CaseBuilder` or similar with methods like `When(string column, object comparisonValue, object trueValue)` and `When(object comparisonValue, object trueValue)`)

The syntax above doesn't feel exactly right/fitting with other SqlKata syntax, there is probably a nicer way to incorporate that but I'm not sure what would work/look best.

**Comment by ceastwood** [comment]
@Sharparam I'll let @ahmad-moussawi stop by with his preference on the syntax, but at present you can use the same solution I commented on #203 with for this as well 😄

**Comment by Sharparam** [comment]
Yep, that's what I do currently, but it gets ugly if still wanting to do parameterization to avoid injection vulnerabilities. Especially when there is a variable number of `WHEN` clauses. And as mentioned in #203 it means having to hand-code the `CASE` for each kind of SQL server when their syntax differs.

**Comment by ahmad-moussawi** [comment]
I implemented this in a previous draft version, it seems interesting, but I think we should stick to a common level, or the library will go to much opinionated, these additional sugar should be added as an extension package.

We can open an issue to track what we need to add, and then we will implement this in a separate package.
What do you think?

**Comment by Sharparam** [comment]
That sounds like a good idea.

**Comment by ahmad-moussawi** [comment]
#209
