### ISSUE TITLE
New feature for Compiler Class?

### ISSUE THREAD

**Issue by fulviocanducci** [sqlkata/querybuilder#21]
**Example:**

```
var compiler = new MySqlCompiler();

Query q1 = new Query("people");
q1.Insert(new Dictionary<string, object>
{
	["name"] = "Peter",
	["created"] = DateTime.Now.AddDays(-2)
});

SqlResult r1 = compiler.Compile(q1);

var q2 = q1.NewQuery()
	.From("people")
	.Select("*");

SqlResult r2 = compiler.Compile(q2);

System.Console.WriteLine(r1);
System.Console.WriteLine(r2);
```

Result Correct:
![abc1](https://user-images.githubusercontent.com/25593291/31455747-fb9fe698-ae8e-11e7-9137-4790220851fb.png)

I would like to create a code in the `Compiler` class where it would leave the same class as if it were a new instance without doing the `NewQuery` Command?

**Example**
```
var compiler = new MySqlCompiler();

Query q1 = new Query("people");
q1.Insert(new Dictionary<string, object>
{
	["name"] = "Peter",
	["created"] = DateTime.Now.AddDays(-2)
});

SqlResult r1 = compiler
  .Compile(q1);  //After this line q1 is at its default and initial value without new instance

var q2 = q1
	.From("people")
	.Select("*");

```    

Having a single instance generating SQL that from compiling the same class could generate new SQL without the intervention of the `NewQuery()` method!

**Comment by ahmad-moussawi** [comment]
First thanks for your suggestion :), the best appropriate approach to your case is to use the `Clone` method

```
var baseQuery = new Query("People");

var q1 = baseQuery.Clone();
// some code here

var q2 = baseQuery.Clone();
// some code here
```

I don't see this would be really helpful since 1) the compiler should not change/modify the query in any way, 2) such implicit way would really confuse developers

for example, what if I want to compile the same query against multiple compilers ?

**Comment by fulviocanducci** [comment]
Good as I had already reported, I am making a package by joining with your package (which is fantastic), it is already in the nuget as beta:

- https://www.nuget.org/packages/Canducci.SqlKata.Dapper/1.0.0-beta-1
- https://www.nuget.org/packages/Canducci.SqlKata.Dapper.MySql/1.0.0-Beta-2

I saw this need at the time of calling with Dapper, maybe solve this differently, if not every time we have to do it like this:

```
string cns = "Server=localhost;Database=testdb;Uid=root;Pwd=senha;SslMode=none";
MySqlConnection connection = new MySqlConnection(cns);

var log = connection.Build()
	.From("people")
	.Insert(new Dictionary<string, object>
	{
		["name"] = "Pedro c",
		["created"] = DateTime.Now.AddDays(-2)
	})
       .Execute();

var result = connection.Build()
	.NewQuery()
	.Select("*")
	.From("people")
	.Query();

```

The `connection.Build()` always creates a new instance, I wish it did not happen.

That is, this gives problem in the second execution

```
build
	.From("people")
	.Insert(new Dictionary<string, object>
	{
		["name"] = "Pedro c",
		["created"] = DateTime.Now.AddDays(-2)
	})
	.Execute(); // ok 

build
	.Select("*")
	.From("people")
	.Query(); // problem ...
```
I accept suggestions. !!!

**Comment by fulviocanducci** [comment]
Has the project stopped?

**Comment by ceastwood** [comment]
@fulviocanducci no sir, @ahmad-moussawi has been making regular commits and merges but the updates are on the myget feed. I have been tied up with work for a while but catching back up.

I'm sure we will work out a push to nuget soon

**Comment by fulviocanducci** [comment]
@ceastwood and @ahmad-moussawi 

What would be the command to restart the `class Query`?

That?

```
public override Query NewQuery()
{
            return new Query().SetEngineScope(EngineScope);
}
```

**Comment by fulviocanducci** [comment]
For some time this issue has been open, but has not yet been solved, and versions and versions have been released, I ask:

- Do you think this should not be done?

- Do you think that putting a method to leave the class at a default value for the generation of a new SQL would not be valid?

- I would like to have an answer on the issue, so I can make decisions about a package I develop on top of that!

Thank you

**Comment by fulviocanducci** [comment]
I'm waiting for this is a pull request about recovering the inserted record!

**Comment by ahmad-moussawi** [comment]
@fulviocanducci, I've already suggested that you can use the `Clone` method for such cases. 
Could you please elaborate more why this approach does not help in your case ?
