### ISSUE TITLE
No Logger for Pagination query

### ISSUE THREAD

**Issue by jasonycw** [sqlkata/querybuilder#210]
We are using SqlKata for some query only API and found that only `.PaginateAsync` cannot log our raw sql properly.

https://github.com/sqlkata/querybuilder/blob/master/SqlKata.Execution/Query.Extensions.Async.cs

It appears that Get, Insert, Update, Delete all got `xQuery.Logger(compiled);` while Pagination do not

**Comment by ahmad-moussawi** [comment]
As a quick look no need for it in the `Paginate` methods, it uses Get and Count under the hood, so they should take care of the logging. 
Could you elaborate more on it, what is the expected log and what you get?

**Comment by jasonycw** [comment]
I made a query with PaginateAsync and it just do not show the log for the raw sql
I copied the query and instead of `.PaginateAsync` at the end, I use `.GetAsync` and the log show up properly for the `.GetAsync` one

**Comment by jasonycw** [comment]
FYI, we created a `QueryFactoryProvider` for DI and set it to log the raw sql in debug level
``` C#
public QueryFactory Get() => new QueryFactory(_connection, new SqlServerCompiler())
{
     Logger = r => _logger.LogDebug(r.RawSql)
};
```
Then I just tried the following 
``` C#
var test1 = await _provider.Get().Query("tableName").GetAsync();
var test2 = await _provider.Get().Query("tableName").PaginateAsync<Model>(1, 10);
```
`test1` returns the following log
```
{
	"@t": "2019-03-13T07:15:09.1443685Z",
	"@mt": "SELECT * FROM [dbo].[tableName]",
	"@l": "Debug",
	....
}
```
While `test2` has no log

**Comment by ahmad-moussawi** [comment]
Thanks for reporting, fixed now you can get the nightly build from https://www.myget.org/F/sqlkata/api/v3/index.json
