### ISSUE TITLE
Is it possible to use expression for queries?

### ISSUE THREAD

**Issue by wireless90** [sqlkata/querybuilder#214]
If I have an employee class, is it possible to do this.
emp => emp.ID == "1"

`IDbConnection sqlConnection = new SqlConnection(ConfigurationManager.ConnectionStrings["MyConnection"].ToString());`
            
            var db = new QueryFactory(sqlConnection, new SqlServerCompiler());
            
            var query = db.Query<Employee>().From("Employees")
                .Where(emp => emp.ID == "1").Get();

            return query;`

**Comment by ahmad-moussawi** [comment]
No it's not within the scope, maybe it can be later, check https://github.com/sqlkata/querybuilder/pull/183 for an example provided by @senkadir

**Comment by senkadir** [comment]
Hi Ahmad , I wish I have time to complete this feature. But i will try at first chance.
