### ISSUE TITLE
Ability to pass raw string expressions in insert/delete statements

### ISSUE THREAD

**Issue by ghost** [sqlkata/querybuilder#221]
I'm using SqlKata to generate non-parameterized Oracle insert statements by using ToString() on Compile() output.

This works well, but I want dates to be inserted with Oracle's TO_DATE function.

So I convert my .Net DateTime to a string, e.g. "TO_DATE('2019/03/19 09:03:47', 'yyyy/mm/dd hh24:mi:ss')". Because it's a string, SqlKata wraps it in single quotes, which doesn't work in Oracle.

Can we have a way to not wrap some strings in quotes?

**Comment by ahmad-moussawi** [comment]
It's not supported now, if `insert into select` could be an option you can use the `Insert(columns, query)`overload.

```cs
var select = new Query("AnyTable").SelectRaw("1 as Id, TODATE('2019/03/19 09:03:47') as Date");
var query = db.Query("TableToInsert").AsInsert(new [] {"name", "date"}, select );
``` 

check:
https://sqlkata.com/docs/execution/update#insert-from-existing-query
https://docs.oracle.com/cd/E17952_01/mysql-5.6-en/insert-select.html

**Comment by ElevenBillionCactusPincushionIdeas** [comment]
Thanks Ahmad. Unfortunately the insert does not include a select.
