### ISSUE TITLE
Inserting value of type byte[]

### ISSUE THREAD

**Issue by pwkdouglas** [sqlkata/querybuilder#223]
When building an insert statement with a value of type byte[], the resulting binding values exceed the designated columns. How should I be inserting a byte array into a varbinary(max) column or is this an issue? The mapping type appears to be correct according to https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-data-type-mappings

Thank you

**Comment by ceastwood** [comment]
@pwkdouglas  Please use the myget nightly-- I had came across this and committed a fix #74e62659698fdfbe38f6c5bf0a7bd2927a43f3fd

**Comment by pwkdouglas** [comment]
Awesome. Thanks @ceastwood!

**Comment by pwkdouglas** [comment]
Added the nightly to my nuget.config, uninstalled & reinstalled sqlkata package via NuGet Package Manager (Wednesday, March 20, 2019 | Source: https://www.myget.org/F/sqlkata/api/v3/index.json), tested a query build and I am still getting more values than columns. I'm probably doing something wrong. I'll have to try again tomorrow.

**Comment by ceastwood** [comment]
@pwkdouglas I'll double check that build later today

**Comment by ceastwood** [comment]
@pwkdouglas  Just checked, and it looks like somehow the last CI build that ran did not run against the most recent commit when it ran. The packaged .dll is missing some of the most recent changes.

**Comment by pwkdouglas** [comment]
@ceastwood Thanks for looking into this. I really appreciate it!

**Comment by ceastwood** [comment]
@pwkdouglas 

I've made some quick changes and pushed package 1.1.8-ci-673 to MyGet as a prerelease. That package does show that it handles the byte[].

![image](https://user-images.githubusercontent.com/222618/55036493-294aee80-4ff1-11e9-84cd-6e3a47191427.png)

**Comment by pwkdouglas** [comment]
@ceastwood 
Just tested that prerelease package and it works perfectly. Thanks a lot!
