### ISSUE TITLE
Building join queries failed on some Cultures due to ToUpper conversion of Join.Type

### ISSUE THREAD

**Issue by gongun** [sqlkata/querybuilder#224]
Some Cultures produce invalid join syntax when coverted to upper case by **ToUpper** because it converts **i** to uppercase dotted **I**. Changing it to **ToUpperInvariant** solves the issue. 

``` csharp
public class Join : BaseQuery<Join>
{
  protected string _type = "inner join";
  
  public string Type
  {
    get
    {
    	return _type;
    }
    set
    {
    	_type = value.ToUpper(); // resolved by changing value.ToUpperInvariant()
    }
  }
```

**Comment by ceastwood** [comment]
@gongun  There have been a few culture-specific issues recently.

I've just replaced all ToUpper() calls with ToUpperInvariant(). The build should be on MyGet as a pre-release.

Added #225 for reviewing culture-specific issues.
