### ISSUE TITLE
Timeout Expired during Query

### ISSUE THREAD

**Issue by lilasquared** [sqlkata/querybuilder#227]
Ran into query execution timing out when trying to run some long running aggregate queries.  I think I narrowed it down to QueryTimeout not being passed in this method.

https://github.com/sqlkata/querybuilder/blob/957a6ffffcf476c32723b7339d8d6011d05b676d/SqlKata.Execution/QueryFactory.Extensions.cs#L18

`IDbConnection.Query` has an overload for commandTimeout that maybe should be used?  I can submit a pr but wanted to see if maybe I was doing something wrong.

**Comment by ceastwood** [comment]
@lilasquared

I believe there is a QueryTimeout property on the QueryFactory object, but will have to look again when I am on a computer

**Comment by lilasquared** [comment]
Yeah there is, and in other methods it is passed to dapper. But it doesn’t look like it is for this one

**Comment by ahmad-moussawi** [comment]
Thanks for reporting, fixed now you can get the nightly build from https://www.myget.org/F/sqlkata/api/v3/index.json
