### ISSUE TITLE
DROP OWNED BY

### ISSUE THREAD

**Issue by FunkyLambda** [sqlkata/querybuilder#228]
I couldn't find this in the documentation. Does SqlKata support this? If not, can it be added as an enhancement in a future version?

**Comment by ahmad-moussawi** [comment]
@FunkyLambda, SqlKata doesn't support DDL query at the moment, for this kind of queries you can use the db.Statement() generic method
check https://sqlkata.com/docs/execution/fetching-records#execute-raw-statements
