### ISSUE TITLE
With (NOLOCK) on joining table.

### ISSUE THREAD

**Issue by MadOnProgramming** [sqlkata/querybuilder#229]
During joining, While selecting from first table, i can acheive with (nolock) using new Query().FromRaw("Table1 WITH (NOLOCK)").
But how can i achieve the same in subsequent tables. 
Because we dont have an option to give raw values in in join.Kindly suggest

I need a output like this:-
Select a.column1, b.column2 from Table1 as a WITH(NOLOCK)
inner join
Table2 as b WITH(NOLOCK)
on a.column1 = b.column1

**Comment by ahmad-moussawi** [comment]
Currently, there is no option to enter a raw expression in the join table field,
You have two options:
1. write the join manually using the `FromRaw`. `FROM [Table1] with(nolock) join [Table2] with(nolock)`

2. or, use the subquery (or CTE) approach, it will output a different query but I think it will lead to the same behavior

```cs
db.Query().FromRaw("[Table1] as [a] WITH(NOLOCK)")
.Join(
    new Query().FromRaw("[Table2] WITH(NOLOCK)").As("b"),
    j => j.Where("b.Id", "a.Id")
);
```

**Comment by jcaballero-overactive** [comment]
I was able to generate the desired output extending the compiler and overriding the method `WrapValue`

**Comment by ahmad-moussawi** [comment]
@jcaballero-overactive 
This way you are open to SQL injection

**Comment by jcaballero-overactive** [comment]
@ahmad-moussawi do you recommend any function already included in the library to sanitize the value?

**Comment by dodevs** [comment]
For anyone that have the same problem, I created a extension method for LeftJoin with nolock
```cs
public static Query LeftJoinNolock(this Query queryBase, string table, Func<Join, Join> callback)
{
    Join withNolock = callback(new Join().AsLeft()).FromRaw($"[{table}] WITH(NOLOCK)");
    return queryBase.AddComponent("join", new BaseJoin
    {
        Join = withNolock
    });
}
```
And use like this
```cs
.LeftJoinNolock(Tables.YOURTABLE, join => join.On(Cols.YOURTABLE_ID, Cols.OTHERTABLE_YOURTABLEID));
```
