### ISSUE TITLE
Getting an Syntax error try limit offset on SQL Server

### ISSUE THREAD

**Issue by sbur74** [sqlkata/querybuilder#23]
Hi! Nice Project! 

I'm on the start with sqlkata and I step in to a probelm with ms sql server (2012).

I was try your doc example for limit and offset with a northwind db :

SELECT * FROM (SELECT *, ROW_NUMBER() OVER (ORDER BY [OrderID]) AS [row_num] FROM [Orders Qry]) WHERE [row_num] BETWEEN 35 AND 48

The SqlServer don't except the **_row_num_** from the inner select. It them to need something like this:

SELECT * FROM (SELECT *, ROW_NUMBER() OVER (ORDER BY [OrderID]) AS [row_num] FROM [Orders Qry])As **rowsorder** WHERE [**rowsorder**]._row_num_ BETWEEN 35 AND 48

Don't know if I did something wrong. Can you please check, if the compiler works correctly? 
Tanks!

Sorry, for my bad English. hope you get the sense out of it!

Greetings from Germany

sascha

**Comment by ahmad-moussawi** [comment]
Hi thanks for your feedback, yes this already mentioned in #13, it will get fixed this weekend hopefully :)

**Comment by ahmad-moussawi** [comment]
Closing it, since fixed on the https://www.nuget.org/packages/SqlKata/1.0.0-beta-354 package

**Comment by sbur74** [comment]
Hi, I have testet the Solution and it works fine, but why do you not use OFFSET FETCH NEXT, like this:
"SELECT * FROM [dbo].[Products] ORDER BY ProductID ASC OFFSET @offset ROWS FETCH NEXT @next ROW ONLY"

Maybe you get a Performance issue with your Solution. 

tanks

sascha

**Comment by ahmad-moussawi** [comment]
@sbur74, because this will not work on the old version of SqlServer `<2012`, maybe we can add a new compiler to target the modern SqlServer engines

**Comment by sbur74** [comment]
@ahmad-moussawi: 
Hi, thanks a lot for you explanation, is it possible to write an extension for is or is it necessary to write a completely new compiler?

tanks and regards

sascha

**Comment by ahmad-moussawi** [comment]
@sbur74 yes you should write a new compiler for this, one way to do this, is to extend the current SqlServerCompiler class and override the following methods `OnBeforeSelect`, `CompileColumns`, `CompileLimit` and `CompileOffset`, check https://github.com/sqlkata/querybuilder/blob/master/QueryBuilder/Compilers/SqlServerCompiler.cs#L24-L135, we would be happy if you contribute back to this project :)

**Comment by sbur74** [comment]
@ahmad-moussawi: thanks a lot for you invention. 
I'll try my best to make a running complier.

**Comment by xgwssab** [comment]
@ahmad-moussawi : i have to place this "OFFSET {0} ROWS FETCH NEXT {1} ROWS ONLY" clause after ORDER BY 

I thought i'll could do this with a RawCondition:
query.Clauses.Insert(query.Clauses.Count, new RawCondition
				{
					Component = "",
					Engine = EngineCode,
					Bindings = new object[] { limitOffset.Offset, limitOffset.Limit },
					Expression = "OFFSET {0} ROWS FETCH NEXT {1} ROWS ONLY"
				});

but this has no impact on the SqlResult.
any idea why this could be?
