### ISSUE TITLE
Add an .Escape(char escapeChar) method to allow escaping wildcards for the .WhereLike clause family 

### ISSUE THREAD

**Issue by mathijs-dumon** [sqlkata/querybuilder#237]
When building SELECT queries with a LIKE where clause (e.g. WhereLike, WhereStarts, ...) it should be possible to escape wildcard characters. ANSI SQL has the ESCAPE clause for this - for example in oracle this could be (taken from https://docs.oracle.com/cd/B13789_01/server.101/b10759/conditions016.htm):
```
SELECT last_name 
    FROM employees
    WHERE last_name LIKE '%A\_B%' ESCAPE '\';
```

**Comment by ahmad-moussawi** [comment]
I think this should be a configuration setting for the compiler, rather than adding it to the query builder class

**Comment by mathijs-dumon** [comment]
That would work as well

Op za 20 apr. 2019 09:20 schreef Ahmad Moussawi <notifications@github.com:

**Comment by mathijs-dumon** [comment]
Since we're getting renewed interest from our client I'm coming back to this

**Comment by mathijs-dumon** [comment]
you proposed to add the escape clause as a compiler option, however, it's more complex than this. we don't want to add the escape clause to every query - only those queries that need it for their LIKE statements

so it should really be tied to using any WhereLike, WhereContains, WhereStarts etc. method

what I propose is to add a field to the BasicStringCondition called EscapeCharacter (a string)
by default it would be null or empty in which case the behavior stays as it is
if it is set (e.g. by passing the character to one of the WhereLike methods) and the compiler supports the ESCAPE clause (all of the db's currently supported do so it can be added to the base compiler) it's added to the where query

what are your thoughts?

**Comment by ahmad-moussawi** [comment]
@mathijs-dumon I think we can close this now right?

**Comment by mathijs-dumon** [comment]
Yes indeed, happy new year!

**Comment by ahmad-moussawi** [comment]
Thanks Happy new year for you too :)
