### ISSUE TITLE
.ForXxx doesn't work with From()

### ISSUE THREAD

**Issue by asherber** [sqlkata/querybuilder#239]
If I want, for example, to use a different table name in different databases:

```csharp
var query = new Query()
    .Select("Id", "Title")
    .ForPostgreSql(q => q.From("Foo"))
    .ForSqlServer(q => q.From("Bar"));
```
This will produce `FROM Foo` (with proper escaping) regardless of which compiler I use -- even if I use a compiler other than Postgres or SQL Server.

**Comment by asherber** [comment]
Looks like the issue is that `FromClause.Clone()` doesn't preserve the Engine.

**Comment by asherber** [comment]
Arggh, nevermind, I was working from my fork, which is out of date. This works fine in latest NuGet.

**Comment by asherber** [comment]
Sorry for the confusion, but I'm going to reopen this. The test case I have above actually does **not** work in latest NuGet. When I had success last night, it was with a slightly different version. 

The issue seems to be reproducible with some test cases but not others. For example, if the first `.ForXxx()` has a `FromRaw` instead of `From`, then the code behaves as expected. But if the first one is `From` and the second is `FromRaw`, then both compilers use the first one. 

I'll do some more testing and debugging and report back.

**Comment by ahmad-moussawi** [comment]
@asherber ok that's great if you need any help please let me know
