### ISSUE TITLE
Problem SqlResult Property Bindings?

### ISSUE THREAD

**Issue by fulviocanducci** [sqlkata/querybuilder#24]
**Example:**
1. Problem

> ![bind1](https://user-images.githubusercontent.com/25593291/31917950-fce1a8ee-b838-11e7-9d21-42dd180afd3d.png)

### It was to have 2 parameters !!!!!

2. Problem

> ![bind2](https://user-images.githubusercontent.com/25593291/31918087-97710eea-b839-11e7-9e30-a2876b02c979.png)

### Problem resulting in ordering the parameters go wrong !!!

Code:

https://github.com/sqlkata/querybuilder/blob/4e5030da774e048115461226ca0cd4dedbc32d6a/QueryBuilder/BaseQuery.cs#L46
```
var bindings = Get(item, engine)
                    .SelectMany(clause => clause.GetBindings(engine))
                    .Where(x => x != null);
```

**Comment by ahmad-moussawi** [comment]
I don't know if I can skip checking for `!=null` in the bindings, so maybe I should finding another way to deal with null values in `insert` and `update` queries like replacing the null with another temporary values, then replace it back when compiling the query

**Comment by ceastwood** [comment]
@ahmad-moussawi 

I had come across this myself in my local dev branch before and I ended up replacing c# null's for parameter assignments with DBNull.Value. It seems like the only real way to be able to use a parameter for the value but still assign a NULL value.

The only issue here is that netstandard1.6 will then require a dependency on System.Data.Common for the type DBNull but from what I know; it works with the PgSql driver and MySql driver. The type is included in the netstandard2.0 framework by default and of course netfx.

**Comment by ahmad-moussawi** [comment]
@ceastwood thanks for the info, actually no need to use this specific type, we can use any other type just to simulate this, I already started to work on this, I will push my commits the soonest

**Comment by ahmad-moussawi** [comment]
Fixed in https://github.com/sqlkata/querybuilder/commit/868057145a91ca7bd5e91ed6c81285270d646a3f, I will publish a new package tonight, let me know if you have any tought about it, thanks

**Comment by fulviocanducci** [comment]
@ahmad-moussawi in test, example:

```
SqlServerCompiler s = new SqlServerCompiler();
MySqlCompiler m = new MySqlCompiler();
PostgresCompiler p = new PostgresCompiler();

Query qInsert = new Query("Owe");
qInsert.Insert(new Dictionary<string, object>
{
	["Name"] = "Nome1",
	["Created"] = null
});


Query qUpdate = new Query("Owe");
qUpdate
	.Where("Id", 1)
	.Update(new Dictionary<string, object>
	{
		["Name"] = "Nome1",
		["Created"] = null
	});



var ssInsert = s.Compile(qInsert);
var mmInsert = m.Compile(qInsert);
var ppInsert = p.Compile(qInsert);

var ssUpdate = s.Compile(qUpdate);
var mmUpdate = m.Compile(qUpdate);
var ppUpdate = p.Compile(qUpdate);

Console.WriteLine("[INSERT]");
Console.WriteLine("=========================================================================");
Console.WriteLine(ssInsert); Console.WriteLine(ssInsert.Sql); Console.WriteLine(ssInsert.RawSql);
Console.WriteLine();
Console.WriteLine(mmInsert); Console.WriteLine(mmInsert.Sql); Console.WriteLine(mmInsert.RawSql);
Console.WriteLine();
Console.WriteLine(ppInsert); Console.WriteLine(ppInsert.Sql); Console.WriteLine(ppInsert.RawSql);
Console.WriteLine();

Console.WriteLine("[UPDATE]");
Console.WriteLine("=======================================================================");
Console.WriteLine(ssUpdate); Console.WriteLine(ssUpdate.Sql); Console.WriteLine(ssUpdate.RawSql);
Console.WriteLine();
Console.WriteLine(mmUpdate); Console.WriteLine(mmUpdate.Sql); Console.WriteLine(mmUpdate.RawSql);
Console.WriteLine();
Console.WriteLine(ppUpdate); Console.WriteLine(ppUpdate.Sql); Console.WriteLine(ppUpdate.RawSql);
Console.WriteLine();
```

Ouput
```
[INSERT]
===========================================================================
INSERT INTO [Owe] ([Name], [Created]) VALUES ('Nome1', NULL) (First)
INSERT INTO [Owe] ([Name], [Created]) VALUES (@p0, @p1)
INSERT INTO [Owe] ([Name], [Created]) VALUES (?, ?)

INSERT INTO `Owe` (`Name`, `Created`) VALUES ('Nome1', NULL) (First)
INSERT INTO `Owe` (`Name`, `Created`) VALUES (@p0, @p1)
INSERT INTO `Owe` (`Name`, `Created`) VALUES (?, ?)

INSERT INTO "Owe" ("Name", "Created") VALUES ('Nome1', NULL) (First)
INSERT INTO "Owe" ("Name", "Created") VALUES (@p0, @p1)
INSERT INTO "Owe" ("Name", "Created") VALUES (?, ?)

[UPDATE]
============================================================================
UPDATE [Owe] SET [Name] = 'Nome1', [Created] = NULL WHERE [Id] = 1 (First)
UPDATE [Owe] SET [Name] = @p0, [Created] = @p1 WHERE [Id] = @p2
UPDATE [Owe] SET [Name] = ?, [Created] = ? WHERE [Id] = ?

UPDATE `Owe` SET `Name` = 'Nome1', `Created` = NULL WHERE `Id` = 1 (First)
UPDATE `Owe` SET `Name` = @p0, `Created` = @p1 WHERE `Id` = @p2
UPDATE `Owe` SET `Name` = ?, `Created` = ? WHERE `Id` = ?

UPDATE "Owe" SET "Name" = 'Nome1', "Created" = NULL WHERE "Id" = 1 (First)
UPDATE "Owe" SET "Name" = @p0, "Created" = @p1 WHERE "Id" = @p2
UPDATE "Owe" SET "Name" = ?, "Created" = ? WHERE "Id" = ?
```

I could see that it is to use the first solution for Dapper?

**Comment by ahmad-moussawi** [comment]
@fulviocanducci the `SqlResult.ToString()` is used only for debugging purposes, so it should not used to execute queries directly, for Dapper you should use the `SqlResult.Sql` property, and it's Dapper's responsibility to take care on how to pass null parameters, check https://stackoverflow.com/a/21638928/1104402 from the Owner of Dapper

**Comment by fulviocanducci** [comment]
@ahmad-moussawi Ok

Are you planning a new nuget package with this modification?

**Comment by ahmad-moussawi** [comment]
@fulviocanducci, it's solved now, and published on nuget under beta-355, thanks for reporting!
