### ISSUE TITLE
.Where does not fail or return none when column doesn't exist

### ISSUE THREAD

**Issue by asd424** [sqlkata/querybuilder#242]
Excuse me if this has been asked before, but I could not find a similar question. I am new to SQLKata, but have run across the scenario where using the `db.Query("Users").Where("qwerty", "qwerty").Select("id").Get()` will return a collection of the `id` for all records in `Users` even though "qwerty" does not exist as a column in the table. I would have expected an error, or at least no rows returned. 

Is this the intended behavior of `Where()`? If so, is there a recommended workaround to ensure no records are returned in this scenario?

**Comment by ahmad-moussawi** [comment]
the `Where` method simply add the SQL `WHERE` clause so no records should be returned, sharing your code sample will help us to investigate

**Comment by ahmad-moussawi** [comment]
I will close this, since no further updates, if the problem persists feel free to reopen. Thanks.
