### ISSUE TITLE
WhenAll method - requires an open Connection

### ISSUE THREAD

**Issue by Sodininkas** [sqlkata/querybuilder#248]
Getting error: BeginExecuteReader requires an open and available Connection. The connection's current state is connecting

When using async code like this:
something1 = DbKata.Query().FirstOrDefaultAsync<test>();
something2 =  DbKata.Query().FirstOrDefaultAsync<test>();
await Task.WhenAll(something1, something2)

**Comment by ahmad-moussawi** [comment]
could you post how you've created the `DbKata` instance?

**Comment by papakonstantinouko** [comment]
Hello, I get this error as well, is it resolved by now? This is how i register the queryfactory

```
services.AddTransient(provider =>
            {
                var connection = new SqlConnection(Configuration.GetConnectionString("DefaultConnection"));
                var compiler = new SqlServerCompiler();
                var queryFactory = new QueryFactory(connection, compiler);
                queryFactory.Logger = compiled => Console.WriteLine(compiled.ToString());
                return queryFactory;
            });
```
