### ISSUE TITLE
Automate build and nuget publishing in AppVeyor

### ISSUE THREAD

**Issue by ahmad-moussawi** [sqlkata/querybuilder#25]
Packages building process should be automated and published automatically on Nuget for both `netfx` and `netcore` frameworks

**Comment by ceastwood** [comment]
@ahmad-moussawi  This is part of the PR that we have spoken about in the ticket [#1](https://github.com/sqlkata/querybuilder/issues/1)

**Comment by ahmad-moussawi** [comment]
@ceastwood, yes actually I've opened a new thread since the problem now is to automate build and not on the net45 support.

**Comment by ceastwood** [comment]
Merged and working
