### ISSUE TITLE
SqlKata IncludeMany Problem

### ISSUE THREAD

**Issue by aboah** [sqlkata/querybuilder#250]
I have the below code snippnet

db.Query("dbo.SummaryCtor").
 IncludeMany("Discrepant", q => q.From("dbo.OffDiscrepant").WhereColumns("SummaryCtor.OffloadingId", "=", "OffDiscrepant.ReceiptID"));

This results in Error as follows
Error	CS1061	'Query' does not contain a definition for 'IncludeMany' and no extension method 'IncludeMany'  accepting a first argument of type 'Query' could be found (are you missing a using directive or an assembly reference?)	QueryBuilder

**Comment by aboah** [comment]
Can anyone be of help

**Comment by ahmad-moussawi** [comment]
The **Include** function is not released yet in the stable version, to use it now use the nightly build instead. 
check this for more details https://sqlkata.com/docs#nightly-builds
