### ISSUE TITLE
Column name as Attribute

### ISSUE THREAD

**Issue by Hotrunner** [sqlkata/querybuilder#261]
Our column names are not very nice and thus I don't want to name my properties after them.

I have the following idea:
```
public class TestData
{
    [SqlColumnName("NotSoNiceAndFarTooLongSqlColumnNameXYZ")]
    public string NicePropertyName{ get; set; }
}
```
By adding attributes to the properties you could map them in your class.

**Comment by mota57** [comment]
That feature is already implemented. You can use the Column attribute pass the name and that's it.

**Comment by Hotrunner** [comment]
Awesome, thank you. That should be added to the documentation!
