### ISSUE TITLE
Insert Get Id does not work for sqlite

### ISSUE THREAD

**Issue by andrejpanjan** [sqlkata/querybuilder#266]
`db.Query("shift").InsertGetId<object>(new { code = "abc", name = "qwe" })` always returns `0`. On the other hand, the `db.Query("shift").SelectRaw("last_insert_rowid()").FirstOrDefault<int>()` called after the above statement returns a correct result.

**Comment by ahmad-moussawi** [comment]
Thanks for reporting, fixed in #271
