### ISSUE TITLE
Documentation on how `Get<T>` and `GetAsync<T>` work?

### ISSUE THREAD

**Issue by romatthe** [sqlkata/querybuilder#273]
This seems like a very pleasant library to use, but so far I've been unable to make the `.Get<T>` and `.GetAsync<T>` calls to work.

For example:

Here's my POCO:
```csharp
public class SchemaColumn
{
    public string Name { get; set; }
    public int Position { get; set; }
    public string Type { get; set; }
    public int MaxCharLength { get; set; }
    public string DataType { get; set; }
    public bool IsIdentity { get; set; }
}
```

The following query simply returns `null`.

```csharp
 var result = db.Query("information_schema.columns")
                .Select(
                    "column_name", 
                    "ordinal_position", 
                    "data_type", 
                    "character_maximum_length", 
                    "udt_name", 
                    "is_identity")
                .Where("table_name", "=", tableName)
                .OrderBy("ordinal_position")
                .Get<SchemaColumn>()
```

The same for the one below:

```csharp
 var result = db.Query("information_schema.columns")
                .Select(
                    "column_name as Name", 
                    "ordinal_position as Position", 
                    "data_type as Type", 
                    "character_maximum_length as MaxCharLength", 
                    "udt_name as DataType", 
                    "is_identity as IsIdentity")
                .Where("table_name", "=", tableName)
                .OrderBy("ordinal_position")
                .Get<SchemaColumn>()
```

How exactly does this mapping work? Is there any documentation on how these methods work?

**Comment by ahmad-moussawi** [comment]
The second example should actually work, and `.Get<SchemaColumn>` should be `.Get<SchemaColumn>()`. If the problem persist please share a project that reproduce the error.

**Comment by romatthe** [comment]
Sorry about the lack of `()`, made a slight mistake there. Currently I haven't been able to get it to work. If I still can't make it work later today I'll quickly throw up a repo on Github that reproduces my problem.

Also, I probably should have pointed out that I'm using the latest version of your library, `1.1.7`.

**Comment by romatthe** [comment]
After fiddling around with this some more, I've managed to make this work. I'm not 100% sure what I did wrong previously.

I still think it might be helpful to add a few lines of documentation for this functionality though, as I'm still not sure what the exact requirements are.

Sorry for wasting your time with this though, and thanks for maintaining this cool library.

**Comment by ahmad-moussawi** [comment]
@romatthe great it worked, I will take this into consideration, feel free to open an issue here https://github.com/sqlkata/docs if you find something specific that can be improved.
