### ISSUE TITLE
How should I insert array into column in postgresql?

### ISSUE THREAD

**Issue by mifopen** [sqlkata/querybuilder#274]
For code
``` c#
query.AsInsert(new {
    id = "1",
    name = "some",
    ids = new [] { "1", "2", "3" }
})
```
I get
``` sql
INSERT INTO "entities"
("id", "name", "ids")
VALUES
($1, $2, $3,$4,$5) -- yes, just without spaces
```
and
`Npgsql.PostgresException (0x80004005): 42601: INSERT has more expressions than target columns`

**Comment by ahmad-moussawi** [comment]
Currently SqlKata doesn't handle non-primitive types on insert/update operations,
adding the ability for RawExpressions can help in this case.

A side question, how are you getting the compiled SQL, since SqlKata doesn't generate symbols like these ones: $1, $2 etc ....

**Comment by mifopen** [comment]
That was a log from Npgsql

**Comment by ahmad-moussawi** [comment]
Could you please post the log generated from the QueryFactory class https://sqlkata.com/docs/execution/logging?

**Comment by mifopen** [comment]
Of course:
``` sql
INSERT INTO "tablename" ("id", "name", "ids") VALUES ('1784d656-ce06-4114-b7c3-c86b899ff5de', 'some', '8d8b8ef4-7ba0-49cb-835f-2f40ba56d626','5194ccb5-00b7-4137-9c97-de07bc706d03','15e99f59-cd7c-4ca4-81e8-61ed0b7b0d44')
```

**Comment by ahmad-moussawi** [comment]
@mifopen could you please submit a PR with a failed unit test, or post the steps to reproduce the issue, like the create table statement, insert table statement etc... + the Postgres version you are using.
Thanks

**Comment by ahmad-moussawi** [comment]
as per pgdoc 
You can insert it as a string enclosed by `{}` so this should work.

```
var query = new Query("Table").AsInsert(new {
    Id = "1",
    Values = "{1,2,3}"
});
```
