### ISSUE TITLE
Bad column with dot wrapping

### ISSUE THREAD

**Issue by borile91** [sqlkata/querybuilder#276]
When a column name contains dots, compiler fails to wrap with square brackets, breaking query command text.
Verified with `SqlServerCompiler`.

For example, this code:
```cs
Query query = new Query("dbo.TestView");
query.WhereNull("Column. With. Dots."); // column name in a view containing dots
SqlResult compiled = new SqlServerCompiler().Compile(query);
Console.WriteLine(compiled.Sql);
```
generates this:
`SELECT * FROM [dbo].[TestView] WHERE [Column].[ With].[ Dots].[] IS NULL`

Problem is generated by the `Wrap` method in `Compiler.cs`, row 772.

**Comment by ahmad-moussawi** [comment]
Ignoring the automatic dot separation will make the developer experience harder, for this reason SqlKata consider the **.** as identifier separator.

If we get more feedback about this (from other developers) we have to find a way such escaping the dot for example it could be passing two dots **..** to instruct the compiler to keep it as is.

As a quick fix, you can extend the current compilers and override the **Wrap** method to handle such cases something similar to #51

**Comment by borile91** [comment]
Understood.
I fixed overriding Wrap method and passing column names with brakets:
```cs
public override string Wrap(string value)
        {
            if (value.StartsWith(OpeningIdentifier) && value.EndsWith(ClosingIdentifier))
            {
                string v = value.TrimStart(Convert.ToChar(OpeningIdentifier)).TrimEnd(Convert.ToChar(ClosingIdentifier));
                if (!v.Contains(OpeningIdentifier) && !v.Contains(ClosingIdentifier))
                {
                    return value;
                }
            }

            return base.Wrap(value);
        }
```

Working for me.
Thanks
