### ISSUE TITLE
Square brackets in json expressions are mistakenly trimmed out

### ISSUE THREAD

**Issue by klym1** [sqlkata/querybuilder#277]
I have `where` statement which uses Mysql's built-in json funcs:

```csharp
var q = new Query();
q.WhereRaw($"json_contains(column1->>$[*].id, json_array('1', '2', '3'))");
```

and final query misses '[', ']' characters (even in *Raw methods)
How to mitigate this behavior?

**Comment by ahmad-moussawi** [comment]
You have to escape the `[]` characters
```cs
q.WhereRaw($"json_contains(column1->>$\\[*\\].id, json_array('1', '2', '3'))");
```
related to #235.
I think we should mention that in the docs also.

**Comment by klym1** [comment]
No, it doesn't work. 
For this
```csharp
q.WhereRaw($"json_contains(column1->>$\\[*\\].id, json_array('1', '2', '3'))");
```

I get:

```sql
json_contains(column1->>$\`*\`. id, json_array('1', '2', '3')) 
```

**Comment by ahmad-moussawi** [comment]
which version are you using ?

**Comment by klym1** [comment]
1.1.7

**Comment by ahmad-moussawi** [comment]
Could you try the nightly build maybe this fix was not provided in the latest stable version.
https://sqlkata.com/docs/#nightly-builds

**Comment by klym1** [comment]
ok, 1.1.8-ci-705 seems to be working fine. Thanks for the help @ahmad-moussawi

**Comment by klym1** [comment]
... and thanks for the fast reply

**Comment by ahmad-moussawi** [comment]
Glad it helped, I will release a stable version soon that includes all these fixes
