### ISSUE TITLE
Missing parenthesis for nested where clause

### ISSUE THREAD

**Issue by klym1** [sqlkata/querybuilder#278]
I'm trying to use 'Nested conditions and grouping' feature from the docs 
https://sqlkata.com/docs/where#nested-conditions-and-grouping

but for 
```csharp
.When(p.items?.Length == 2, r => r
                    .Where(q =>
                    {
                        return q.WhereStarts("item", p.items[0])
                            .OrWhereStarts("item", p.items[1]);
                    }))
```

i'm getting:

```sql
... AND LOWER(`item`) like @p5 OR LOWER(`item`) like @p6 AND ...
```

instead of 

```sql
... AND (LOWER(`item`) like @p5 OR LOWER(`item`) like @p6) AND ...
```

**Comment by klym1** [comment]
I'm using version 1.1.8-ci-705

**Comment by klym1** [comment]
This is exactly what I need https://github.com/sqlkata/querybuilder/issues/46

**Comment by ahmad-moussawi** [comment]
Yes it seems this is affected in a recent commit, I've validated the issue,
you can use the 1.1.8-ci-707 build that solve this

**Comment by klym1** [comment]
I've almost made a fixed version:
```
protected override string CompileNestedCondition<Q>(SqlResult ctx, NestedCondition<Q> x)
        {
            var baseResult = base.CompileNestedCondition(ctx, x);
            return "(" + baseResult + ")";
        }
```
:)

Yes, 707 build seems to be working correctly. Many thanks for such quick help.
