### ISSUE TITLE
Should we change ToUpper-ToLower methods as ToUpperInvariant-ToLowerInvariant methods

### ISSUE THREAD

**Issue by kucukf** [sqlkata/querybuilder#281]
Hello,

We start using SqlKata in out project. I faced an issue in development. My computer's language is English but culture is Turkish. In my machine if i use query.WhereStarts or query.WhereEnds it throws error that "The operator 'lıke' cannot be used. Please consider white listing it before using it". My machine culture is caused it. I can change my machine culture but in production i can't as all customers to change their culture. Although i need their cultures to show datetimes, decimals, floats as their culture settings. Because, you know, EVERY SINGLE COUNTRY uses different date formats (sorry but since the day that i met with datetime object, i'm little angry about this 😄)

If we use ToLowerInvariant(), ToUpperInvariant() in compiler, it wont depend machine culture. Should we change them to invariants?

https://github.com/sqlkata/querybuilder/blob/5d64310c6d0faaaae647fd0d0c8eb30df9fede06/QueryBuilder/Compilers/Compiler.cs#L743

**Comment by hussamelvani** [comment]
Hey, When will the next minor realease happen?

**Comment by ahmad-moussawi** [comment]
@hussamelvani we have some conflicts that affected the release, but you can always get the pre-release version that include all theses updates.
check out https://www.myget.org/feed/sqlkata/package/nuget/SqlKata.Execution/1.1.8-CI-720 and https://sqlkata.com/docs#nightly-builds
