### ISSUE TITLE
invalid inner join key ? >>> "İNNER JOİN"

### ISSUE THREAD

**Issue by mummyildiz** [sqlkata/querybuilder#282]
The query sent to the database contains invalid sql keywords in its sentence. how we can edit.
(dBase.DbProvider.SqlCompilerProvider() = SqlKata.Compilers.OracleCompiler(), it is inherited)

(PC language/Country: Turkey)

![sqql](https://user-images.githubusercontent.com/5136066/63532743-fc552600-c513-11e9-9d69-f7709d82a357.png)

**Comment by ahmad-moussawi** [comment]
related to #281 and #205

**Comment by mummyildiz** [comment]
op = op.ToLower();

table and field names are corrupted at this time.

select dıstınct "kardıyolojı_tanım"."t_tanım"
from "kardıyolojı_tanım" 
inner join .......
