### ISSUE TITLE
 how do i connect to firebird?

### ISSUE THREAD

**Issue by curruwilla** [sqlkata/querybuilder#283]
how do i connect to firebird?

**Comment by ahmad-moussawi** [comment]
Install the Firebird ADO.net provider see instructions here https://firebirdsql.org/en/net-provider/

and follow the instructions here https://sqlkata.com/docs/execution/setup#queryfactory
off course replace the `MySqlConnection` with `FbConnection` class

**Comment by curruwilla** [comment]
> Install the Firebird ADO.net provider see instructions here https://firebirdsql.org/en/net-provider/
> 
> and follow the instructions here https://sqlkata.com/docs/execution/setup#queryfactory
> off course replace the `MySqlConnection` with `FbConnection` class

`var connection = new FbConnection(
                $"character set=NONE;initial catalog={_path};user id={_user};data source={_host};user id={_db};Password={_pass};Pooling=true;Dialect=3"
            );

            var compiler = new FirebirdCompiler();

            return new QueryFactory(connection, compiler);`


I'm a layman, is giving error in new QueryFactory

**Comment by curruwilla** [comment]
How does auto increment work?

Seems not to be auto incrementing
