### ISSUE TITLE
How to use [Ignore] in property?

### ISSUE THREAD

**Issue by curruwilla** [sqlkata/querybuilder#284]
How do I leave a property outside the insert?

how do I ignore a column in the insert?

**Comment by ahmad-moussawi** [comment]
The latest prerelease https://www.nuget.org/packages/SqlKata/1.1.8-ci-712
Allows you to use the `[Ignore]` annotation on the class properties.

**Comment by curruwilla** [comment]
> The latest prerelease https://www.nuget.org/packages/SqlKata/1.1.8-ci-712
> Allows you to use the `[Ignore]` annotation on the class properties.

Omg, I was all day yesterday trying to solve this haha
Thank you very much @ahmad-moussawi
