### ISSUE TITLE
InsertGetId always returns 0

### ISSUE THREAD

**Issue by myargeau** [sqlkata/querybuilder#289]
We are using SQL Server. The row is inserted correctly, but from our C# code the id returned is 0.

**Comment by ahmad-moussawi** [comment]
Could you please provide more info about:
- The SqlKata version used
- The SqlServer version
- The Sql output https://sqlkata.com/docs/execution/logging

**Comment by myargeau** [comment]
The logged query:
`INSERT INTO [DispatchHistory] ([Action], [Source], [Status], [Dispatch_Counter], [Information], [IntervenerType], [IntervenerCode], [Note], [DispatchList], [DeclineReason]) VALUES ('{', 'O', '[', '6046', '', '1', '1', '', '6046', '');SELECT scope_identity() as Id`

We tried with SqlKata 1.1.7 and 1.1.8-ci-712 on SQL Server 2016 (SP2-CU7)

I talked to our DBA, and it seems we have a trigger `ALTER TRIGGER [Internal].[DispatchHistory_PartitionSequenceHandler_tg] ON [Internal].[DispatchHistory] INSTEAD OF INSERT` that might be the cause.

**Comment by myargeau** [comment]
Finally, this seems to be it. even running the query directly in Microsoft SQL Server Management Studio return a NULL id.

`INSERT INTO DispatchHistory ("Status") VALUES('2'); SELECT scope_identity() as Id;`

**Comment by stephengreenfield** [comment]
@ahmad-moussawi   I'm having the same issue as described. I'm using:
```
Npgsql version 4.0.10
SqlKata version 1.1.7
```
Here is the query:
```
INSERT INTO themes
(name, url, description, themetypeid, minparticipants, maxparticipants, teamsingularnoun, teampluralnoun, iscustom, bggid, creatorparticipantid)
VALUES
('abc', NULL, NULL, 2, 1, 20, NULL, NULL, true, NULL, 1);
SELECT lastval();
```
When I run it in the db directly, it returns the next `Id` correctly. But when I run it in code, it returns zero:
```
var themeId = new QueryFactory(GetConnection(), new PostgresCompiler())
	.Query("themes")
	.InsertGetId<int>(new
	{
		name = theme.Name,
		url = theme.Url,
		description = theme.Description,
		themetypeid = (int) theme.ThemeType,
		minparticipants = theme.MinParticipants,
		maxparticipants = theme.MaxParticipants,
		teamsingularnoun = theme.TeamSingularNoun,
		teampluralnoun = theme.TeamPluralNoun,
		iscustom = theme.IsCustom,
		bggid = theme.BggId,
		creatorparticipantid = theme.CreatedByParticipantView?.Id
	});
```

**Comment by for7raid** [comment]
Do you have any triggers on your table?
We had similar specific issue.
`lastval()` returns value of last affected sequence. If you have trigger on primary table, that write logs to another table, so `lastval()` returns last log_id, not id of primary table. 
The best way to use `returns id` where `id` primary key name, but in this case developer have to provide to sqlkata name of primary key column, but this is overhead for sqlkata I expect.
Please, look around of tables. Also provide result of query compilation of this query.

**Comment by stephengreenfield** [comment]
Thanks for the response. Yes, I do have triggers on the table to auto-populate some fields on insert. It makes sense that this could cause an issue. I ended up solving this by using `.AsInsert()` and then running the sql from that.
