### ISSUE TITLE
Oracle Compiler Where Clause Generates ?

### ISSUE THREAD

**Issue by senkadir** [sqlkata/querybuilder#293]
Hi,

We have faced strange issue with OracleCompiler.

We have simple where clause, when we compile query with compiler, ToString() and RawSql generates different results.

Is it normal?

We did not try it with different compilers!

I've added pictures.

<img width="315" alt="katabugquery" src="https://user-images.githubusercontent.com/10263337/64617053-64e24500-d3e6-11e9-8ac9-0b584bfcf2bd.png">
<img width="491" alt="katabugqueryresult" src="https://user-images.githubusercontent.com/10263337/64617054-657adb80-d3e6-11e9-92b8-0929452d8cec.png">

**Comment by for7raid** [comment]
Yes, it is fully normal behavior.
.ToString() uses just for visualization query in debug(not for production using), it replaces command parameters with its string representation.
.RawSql - it is raw internal sql command wich will be translated to RDBMS command with specific DB parameter placeholder, all parameters should be send as command parameters

Use code from documentation, Sql and Binding properties
```
using SqlKata;
using SqlKata.Compilers;

// Create an instance of SQLServer
var compiler = new SqlServerCompiler();

var query = new Query("Users").Where("Id", 1).Where("Status", "Active");

SqlResult result = compiler.Compile(query);

string sql = result.Sql;
List<object> bindings = result.Bindings; // [ 1, "Active" ]
```
