### ISSUE TITLE
error in multi thread queries...

### ISSUE THREAD

**Issue by iiiohsen** [sqlkata/querybuilder#294]
If we try to run queries at once we get this error:
There is already an open DataReader associated with this Connection which must be closed first.
What is the solution to this problem?

**Comment by ahmad-moussawi** [comment]
Could you please share your code so it help us investigate the issue.

**Comment by mifopen** [comment]
Most db drivers aren't thread-safe. For example, if I share the same NpgsqlConnection to multiple threads and execute multiple queries at the same time then I get an error about it.
Docs contain "// You can register the QueryFactory in the IoC container"
but then it is too easy to have the same DbConnection in multiple threads.

**Comment by iiiohsen** [comment]
for example:

for (int i = 0; i < 1000; i++)
{
	new Thread(() => {
		try {
			dB.Query("cars").Where("id", 0).Update(new { id=0 }) ;
		}
		catch (Exception ex) { Console.WriteLine(ex); }
		Thread.Sleep(100);
	}).Start();
}
dB.Query("cars").Where("id", 0).Update(new { id = 0 });

**Comment by iiiohsen** [comment]
Do you have a solution?
MARS is not supported with mysql

**Comment by ceastwood** [comment]
@iiiohsen I believe that you should not be using the same connection for all those threads. This is the reason ADO.NET implements connection pooling. MySql ADO.Net driver even has a page about this

[Connector/NET Connection Pooling](https://dev.mysql.com/doc/connector-net/en/connector-net-programming-connection-pooling.html)

In particular, refer to these blocks of text:

> To work as designed, it is best to let the connection pooling system manage all connections. Do not create a globally accessible instance of MySqlConnection and then manually open and close it. This interferes with the way the pooling works and can lead to unpredictable results or even exceptions.
