### ISSUE TITLE
Compiling INSERT query with FromRaw throws exeption

### ISSUE THREAD

**Issue by KRperm** [sqlkata/querybuilder#295]
If table name of INSERT query was defined with `FromRaw` function, then, during compilation, `System.InvalidCastException` is thrown. It cannot cast from `SqlKata.RawFromClause` to `SqlKata.FromClause`.

Use code below to reproduce error.
```
var name = "[z_odv_17.02.2018]";
var sql = new Query()
.FromRaw(name)
.AsInsert(new
{
    Val1 = 1,
    Val2 = true
});

var mssql = new SqlServerCompiler();

var mssqlResult = mssql.Compile(sql);

var mssqlText = mssqlResult.Sql;
```

**Comment by ahmad-moussawi** [comment]
Uploaded a hotfix could you try to get the latest build from the nightly build feed.
https://www.myget.org/F/sqlkata/api/v2/package
for more details check https://sqlkata.com/docs/#nightly-builds

**Comment by KRperm** [comment]
@ahmad-moussawi On 1.1.8-0-714 it works fine. Thank you very much!
