### ISSUE TITLE
Let .Limit() accept other types of numeric values

### ISSUE THREAD

**Issue by KRperm** [sqlkata/querybuilder#298]
Trying to pass `long` value to `.Limit()`, but, sadly, it accept only `int`. It would be nice if I can pass different types of numeric to this function.

**Comment by ahmad-moussawi** [comment]
the maximum value of the int datatype in csharp is: `Int.MaxValue` which is `(2 ^ 32)/2 - 1 == 2,147,483,647`
which is sufficient in most cases, I don't see the real need of using long here.
let me know your feedback.

**Comment by KRperm** [comment]
@ahmad-moussawi I agree that integer is enought in most cases. Limiting rows to more than couple of billions rows is quite rare. But I think that sqlkata shouldn't restrict user from doing that if there is no constraints in sql engine itself.

**Comment by ahmad-moussawi** [comment]
Since there is no real need for this now, I will close it, we can reopen if circumstances change later on
