### ISSUE TITLE
Collation Support?

### ISSUE THREAD

**Issue by KRperm** [sqlkata/querybuilder#299]
It would be nice, if sqlkata would support collation in WHERE and ORDER BY clauses.
For example, it should generate something like this:
```sql
SELECT [Column] FROM [Table] 
WHERE [CallName] COLLATE Cyrillic_General_CS_AS = @CallName
```

**Comment by ahmad-moussawi** [comment]
Currently there is no plan to support engine specific expressions, 
so you can build your own extension method for that (something similar to the below), I will close this for now and watch for other developers feedback, feel free to reopen if you have any input.

```cs
public static WhereCollate(this Query query, string column, string collation, object value)
{
  return query.WhereRaw("... = ?", value);
}
```
