### ISSUE TITLE
how to distinguish 'schema' in DeepJoin  method ?

### ISSUE THREAD

**Issue by wddpct** [sqlkata/querybuilder#3]
such as the flowing code

```
var q6 = new Query().From("streets").Select("test.cities.id","test.cities.name").DeepJoin("cities.countries.continents");
      var c6 = new Compiler().Compile(q6.Clone()).ToString();
````

if the table city,the table country,the table continent were exsited in diffrent schema, how could I build the query sql string, thanks for your help.

actually, I took the method that using  `set search_path to myschema,public` in database's configuration level(I use postgresql), it help to avoid write specific schema name, but if your project could provider some elegant method……
Very grateful to you!

**Comment by ahmad-moussawi** [comment]
Currently DeepJoin is limited to specific use cases.
Do you have any suggestions ? maybe using `->` instead of `.`, am trying to keep it neat and simple

**Comment by wddpct** [comment]
yes, I agree with you, '.' symbol sometimes makes me confused, and it is also a important symbol. This is a little overkill for '.'

**Comment by ahmad-moussawi** [comment]
Closing since this feature is not supported anymore
