### ISSUE TITLE
support UPDATE from one table to another table.

### ISSUE THREAD

**Issue by KRperm** [sqlkata/querybuilder#300]
Other feature that would be useful is generating script that copy content of one table to another.
Sqlkata should generate something like this: 
```sql
UPDATE dest
SET 
    dest.[Date]=src.[Date]
FROM [sourceBulkTable] src INNER JOIN [destinationTable] dest
    ON src.[ID] = dest.[ID];
```

**Comment by NicolasMalo** [comment]
In the same line, it would be useful to be able to update with a join. 

```c#
new Query("table1 AS t1")
    .Join("table2 AS t2", "t1.id", "t2.fk_t1_id")
    .AsUpdate(new {
        col1 = "myNewValue"
    })
    .Where("t2.id", 10)
```

I would have expected the query to compile to (postgres syntax)

```sql
UPDATE table1 AS t1
SET col1 = 'myNewValue'
FROM table2 AS t2
WHERE t1.id = t2.fk_t1_id AND t2.id = 10

```

**Comment by andreisctendava** [comment]
Hi, 

Any update on this issue?

@NicolasMalo , @KRperm  - any workarounds for this scenario?

Thx in advance.

**Comment by ahmad-moussawi** [comment]
duplicates of #182, I will close this, please continue the discussion their
