### ISSUE TITLE
Write large strings

### ISSUE THREAD

**Issue by cunnpole** [sqlkata/querybuilder#301]
Hi, SqlKata is an awesome project, however I've been having a few issues with some update queries that appear to be related to the use of Dapper. Everything works fine until my string gets above 4000 characters. At this point, via both Sql Kata and Dapper, the query never reaches the Sql Server (I'm watching the profiler). 

I can mitigate this in Dapper using DynamicParameters:

var args = new DynamicParameters(new { });
		args.Add("ActionDate", DateTime.Now);
		args.Add("Structure", structure, size:Int32.MaxValue); //<-Very big string
		args.Add("Id", 1);

But I dont seem to be able to do similar via Kata. Is there a better way to handle this?

The default max string length in Dapper dapper appears to be here, but I can't see how to override this with Kata:
https://github.com/StackExchange/Dapper/blob/4e62055c5775aced61b848282ed180de0ab62161/Dapper/DbString.cs#L21

**Comment by ahmad-moussawi** [comment]
I think you can pass the DbString directly as parameter in SqlKata.

```cs
var rows = db.Query("Table").Where("Name", new DbString { 
  Value = "abcde",
  IsFixedLength = true,
  Length = 10,
  IsAnsi = true
}).Get();
```
off course change the options as per your need.

**Comment by ahmad-moussawi** [comment]
@cunnpole does the suggested solution (DbString) work for you?
