### ISSUE TITLE
Manually mapping column names to object properties

### ISSUE THREAD

**Issue by joaokanta** [sqlkata/querybuilder#307]
There is a [question on SO](https://stackoverflow.com/questions/8902674/manually-map-column-names-with-class-properties)  for the same issue with Dapper, which has already been answered. 
How can I do this with sqlkata?

**Comment by ahmad-moussawi** [comment]
Why not using alias?
```
class User
{
  public string UserName {get; set;}
}

var users = db.Query("Table").Select("user_name as UserName").Get<User>();
```
