### ISSUE TITLE
SqlKata -v 1.0.0-beta-357  What has changed?

### ISSUE THREAD

**Issue by fulviocanducci** [sqlkata/querybuilder#31]
What were the new features or was it only fixes ?

**Comment by ceastwood** [comment]
@fulviocanducci 

I believe just net45 support and working ci build config, but there was a pull request accepted for paging I believe.

You can probably review the issues closed/pr closed/commit messages for a more accurate chancellor.

Thanks

**Comment by ahmad-moussawi** [comment]
Yes no new features in this release, only devops things to build and publish nuget packages automatically, off course thanks for ceastwood for this push, I will close it now, feel free to reopen if you need to add something else
