### ISSUE TITLE
Change states after method calling

### ISSUE THREAD

**Issue by qq831799** [sqlkata/querybuilder#314]
Hi
I like this project and use in my job.
But I can't figure out why the original object states will change after method be called.
Ex
``` C#
var query = new Query("Books");
query.Where("name","book1");
```
The ` query.Where` will return a Query object
But the original query object will also be added a new clauses

That make if I want to query same table with different condition
I need to re new a Query object

Is that I mistake something or there is a reason need to change original object

Sorry for my poor English, but this interest me

**Comment by ahmad-moussawi** [comment]
same as #176, in short use the `Clone()` method when you want to get a copy from an existing query.

```cs
var baseQuery = new Query("Books");
var query1 = baseQuery.Clone().Where("name","book1");
```

**Comment by qq831799** [comment]
Oops I didn't find this.
Thank you for your response
