### ISSUE TITLE
Overload InsertGetId to accept dictionary or real type with exclusion

### ISSUE THREAD

**Issue by danielklecha** [sqlkata/querybuilder#317]
Hello,
I have a table in database with auto increment column.
I want to insert into this table instance of my class, but skip this particular column and obtain new id.
I saw that you added a method InsertGetId but I can't use my class because it contains this problematic column.
Is there a solution for this or could you add new overload for this method?
Thanks for help!

I can add class without id and derived class with id but it is not ideal solution.

Working part
```c#
//this is working with anonymous type
var newId = db.Query("MyTable").InsertGetId<int>(new { Name = "abcd" });
//this is working with instance but I can't obtain new id
var inst = new MyClass { Name = "abcd" };
var dict = typeof(MyClass)
   .GetProperties()
   .Where(x => x.Name != "Id")
   .ToDictionary(x => x.Name, x => x.GetValue(inst));
var count = db.Query("MyTable").Insert(dict);
```
Proposed changes
```c#
//I can't do this - it should accept dictionary
var inst = new MyClass { Name = "abcd" };
var dict = typeof(MyClass)
   .GetProperties()
   .Where(x => x.Name != "Id")
   .ToDictionary(x => x.Name, x => x.GetValue(inst));
var count = db.Query("MyTable").Insert(dict);
var newId = db.Query("MyTable").InsertGetId<int>(dict)
//I can't do this - exclude column in InsertGetId (or IEnumerable<string> parameter)
var inst = new MyClass { Name = "abcd" };
var newId = db.Query("MyTable").InsertGetId<int>(inst, "Id")
```

**Comment by ahmad-moussawi** [comment]
You can benefit from the **ColumnAttribute** and **KeyAttribute** https://github.com/sqlkata/querybuilder/blob/master/QueryBuilder/ColumnAttribute.cs in such case.

for example:

```cs
class User {
 [Key]
 public int Id {get; set;}

[Column("username")]
 public string Name {get; set;}

[Ignore]
public string ThisColumnIsIgnored {get; set;}
}
```
then SqlKata will ignore this column automatically you can use also the `[Ignore]` attribute if you want to ignore some columns

**Comment by danielklecha** [comment]
I had a problem to find it but I realized that this is in prerelease.
Anyway, **it's working**.
Thanks for quick response!
