### ISSUE TITLE
How do you write it?

### ISSUE THREAD

**Issue by Sabirjan** [sqlkata/querybuilder#320]
update  callinfo set err_count=err_count+1  where id=1;

thanks .

**Comment by Sabirjan** [comment]
db.Statement("update callinfo set err_count=err_count+1 where id=1;");
OK ?

**Comment by jeremyalan** [comment]
Similar question here:
https://github.com/sqlkata/querybuilder/issues/159

It looks like the solution posted is the accepted approach for now.
