### ISSUE TITLE
SemVer?

### ISSUE THREAD

**Issue by Sharparam** [sqlkata/querybuilder#322]
Between versions 1.1.0 and 1.1.7 there was a breaking change introduced in `SqlResult`.

In 1.1.0, `NamedBindings` was a property (get-only):

https://github.com/sqlkata/querybuilder/blob/v1.1.0/QueryBuilder/SqlResult.cs#L25-L38

In 1.1.7, it's a public field:

https://github.com/sqlkata/querybuilder/blob/v1.1.7/QueryBuilder/SqlResult.cs#L14

This is a breaking change and should've bumped the version of SqlKata to 2.0.0. It caused some minor headaches with `MissingMethodException` being thrown since we had a library using 1.1.0 and an app pulling in 1.1.7, according to SemVer that should be fine but due to the above breaking change it was not.

Is this project using SemVer, or does every version change have the possibility of being a breaking change? Given that the version number looks like SemVer I just assumed it was.

**Comment by ahmad-moussawi** [comment]
@Sharparam Yes you are right the project should be bumped to 2.0.0, I am working on a set of features/enhancements that should be pushed together soon
