### ISSUE TITLE
SQLite Unsupported Keywords

### ISSUE THREAD

**Issue by hussamelvani** [sqlkata/querybuilder#326]
When calling ".First" or ".FirstOrDefault" (and thier async versions) using SQLite compiler, an exception gets thrown from SQLite that a "Top" keyword is not available.
-In SQLite it should be "LIMIT" instead of Top

Also when calling InsertGetId (and its async version) an exception gets thrown from SQLite that a "SCOPE_IDENTITY()" keyword is not available.
-In SQLite it should be " sqlite3_last_insert_rowid()" instead of Top

As a work around I used this (bellow) for the first problem
`return (await sqlKataDB.Query("XXX").Select("Column").Where("Column", ColumnValue).GetAsync<Model.ClassName>()).AsEnumerable().FirstOrDefault();`

As a work around I used this (bellow) for the second problem
After a successful insert I called
`await sqlKataDB.SelectAsync<int>("sqlite3_last_insert_rowid()");`

**Comment by ahmad-moussawi** [comment]
Can you share the code that creates the QueryFactory class, since It seems you are using the SqlServerCompiler instead of the SqliteCompiler

**Comment by hussamelvani** [comment]
That was a very rookie mistake, I guess that what happens when you copy and paste form your other projects :).
I appologize for wasting your time. Have a good day.

**Comment by ahmad-moussawi** [comment]
No worries at all :)
