### ISSUE TITLE
I can't insert multiple records

### ISSUE THREAD

**Issue by curruwilla** [sqlkata/querybuilder#332]
Hello everyone

I am trying to insert multiple records from a local database, to an online database, the local database is firebird, and the other one is mysql, I tried this:

`var baseQuery = connect.Query();

var data = baseQuery.Clone().From("CAIXA");

connectOnline.Query("CAIXA").Insert(data);`

connectOnline = online database connection
connect = local database

the tables are the same, the only difference is that the online database table has one more column called id_on

Can someone help me?

I would need to do this with update too

**Comment by ahmad-moussawi** [comment]
To late to reply, but the best way to do it is to loop to the result then fill the needed columns on a dictionary then update the target db.
