### ISSUE TITLE
XQuery: Add support for Exists() and DoesntExist() 

### ISSUE THREAD

**Issue by ahmad-moussawi** [sqlkata/querybuilder#334]
Currently if I want to check only for the existence of some records, I have to fetch the records and test the count, while we can do the check directly on the db and save some network traffic.

Suggestion:
var isFound = db.Query("Table").Where("Some Conditions here").Exists();
var isNotFound = db.Query("Table").Where("Some Conditions here").DoesntExist();

Similar to https://laravel.com/docs/6.x/queries#aggregates

**Comment by kidmar** [comment]
It would be nice
Please also consider to add a WhereExists(Query) / WhereNotExists(Query) method to be able to add exist clause to the query

**Comment by ahmad-moussawi** [comment]
@kidmar `WhereExists` and `WhereNotExists` already exists in the Query class

**Comment by kidmar** [comment]
Thanks, didn't notice :)

**Comment by ahmad-moussawi** [comment]
Feature shipped we can close this now :)
