### ISSUE TITLE
Sqlite: no such function: TOP

### ISSUE THREAD

**Issue by OfficialHisha** [sqlkata/querybuilder#335]
Hello,
I'm not sure if I'm doing something wrong, but I tried to follow the documentation from https://sqlkata.com/docs to get some user data but I keep getting the following error.
![image](https://user-images.githubusercontent.com/1457902/72209958-efca6d80-34b4-11ea-97a7-b1292420c6f6.png)

The code I'm using is as follows
```
        static SQLiteConnection connection = new SQLiteConnection(@"URI=file:.\data.db");
        static SqlServerCompiler compiler = new SqlServerCompiler();

        static QueryFactory db = new QueryFactory(connection, compiler);

        public static string TestGetUser()
        {
            var user = db.Query("users").Select("username").Where("username", "Hisha").First();
            string name = user.username.ToString();
            return name;
        }
```

I have confirmed that the names of tables and fields are correct.

Thanks in advance.

**Comment by ahmad-moussawi** [comment]
Hello, you are using the wrong compiler, you need the **SqliteCompiler** here

**Comment by OfficialHisha** [comment]
Ah! Gotcha.
Works now, thanks.
That one slipped my sight..
