### ISSUE TITLE
Changes in 2.0

### ISSUE THREAD

**Issue by asherber** [sqlkata/querybuilder#338]
Is there a changelog somewhere to show what's new in 2.0?

**Comment by lbguilherme** [comment]
I couldn't find it either.

This is the closest info on the reason 2.0 was released I could find: https://github.com/sqlkata/querybuilder/issues/322

cc @ahmad-moussawi

**Comment by mark-at-tusksoft** [comment]
Definitely need this. I can't just pull in arbitrary updates w/o knowing what potential effect it will have. Certainly there would be mention if the API surface has been altered.

**Comment by toburger** [comment]
As a workaround: If you need info about API changes you can use FuGet: https://www.fuget.org/packages/SqlKata/2.2.0/lib/netstandard1.0/diff/1.1.8-ci-712/
But it is not really a replacement for a changelog.

**Comment by ahmad-moussawi** [comment]
No change log at the moment, will try to find a way to automate this for future release, due to limited time/resource to support this.

**Comment by asherber** [comment]
If you're not familiar with it, takes a look at https://www.conventionalcommits.org/en/v1.0.0/

If you follow a pattern with your commit messages, it's easier to parse them and automatically maintain release notes.
