### ISSUE TITLE
Prevent database generated columns from being inserted.

### ISSUE THREAD

**Issue by grounzero** [sqlkata/querybuilder#339]
[IgnoreAttribute] is great at preventing database generated columns from being added to the insert list but it prevents the column from populated during a Get and irt appears `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` is not recognised.

How can I work around this?

**Comment by hussamelvani** [comment]
I was looking for a solution like this as well. +1

**Comment by abravodev** [comment]
Not sure whether this can help you, but you can use [Dapper.Contrib](https://dapper-tutorial.net/dapper-contrib), which has an [Insert method](https://dapper-tutorial.net/insert) and you can use [attributes](https://dapper-tutorial.net/dapper-contrib#data-annotations) ([Key], [Computed]...) that will prevent properties to be added to the insert query (it also works for update queries).

I've realized that the query builder lacks some of the features I need, but with the [QueryFactory ](https://github.com/sqlkata/querybuilder/blob/master/SqlKata.Execution/QueryFactory.cs) you can get the IDbConnection and then use any of the Dapper methods.

**Comment by lesair** [comment]
@abravodev Yes Dapper.Contrib has a Key attribute to decorate your POCOs properties as a column whose value is generated by the database, however I noticed that SqlKata too has a [Key] attribute. I thought it would work the same as Dapper's but it didn't. Do you know what is SqlKata [Key] attribute for?

**Comment by lesair** [comment]
@grounzero  and @abravodev, I decorated my POCO with the [Ignore] SqlKata key attribute and it worked for insertions, SqlKata no longer includes the decorated column in the INSERT statement, but it includes it in SELECT statements, so it works for me.

**Comment by ahmad-moussawi** [comment]
The `[Key]` and the `[Ignore]` attributes prevent the columns from being inserted/updated in the insert/update query, and they don't do anything more than that.

The select query is not affected at all.
