### ISSUE TITLE
Limit/Offset alters select statement by adding row_num

### ISSUE THREAD

**Issue by mark-at-tusksoft** [sqlkata/querybuilder#340]
Using SqlServerCompiler and running queries against SqlServer2017 (composing queries then feeding resulting queries as sql to EF context).

When I compile a query using `.ForPage()`, it wraps my intended query as a subquery with an extra ROW_NUMBER() column for ordering and the outer query uses a `select *` which brings along that extra `row_num` column. Since I have to specify the structure returned (in this case `long` because I am only selecting Ids) this extra column mutates the expected structure.

If this is intended behavior, that's fine, but it needs to be in bold, red font on the [docs for Limit and Offset](https://sqlkata.com/docs/limit) because this is an unexpected side-effect.

Edit: It appears that this happens with Limit().Offset() as well.

**Comment by mark-at-tusksoft** [comment]
Fixing this with yet _another_ sub-query

```
var pagedQuery = new Query().From(query.ForPage(request.Page, request.PageSize).Select("pg.Id"), "out");
var compiledQuery = _compiler.Compile(pagedQuery.Select("out.Id"));
```

**Comment by jongibler** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/3208745/77603924-df803700-6ed6-11ea-8185-9592d321c4d5.jpg)
If you set that to TRUE it will use offset

**Comment by ahmad-moussawi** [comment]
I will close this now, since setting `UseLegacyPagination = false` will help in this case, if this still an issue for you, feel free to reopen
