### ISSUE TITLE
Version greater than 1.1.7 marked as prerelease in Nuget

### ISSUE THREAD

**Issue by b-twis** [sqlkata/querybuilder#348]
Hi,

Is there a reason that the latest versions are marked as prerelease in Nuget?

Only up to 1.1.7 is listed as stable. 

Thanks,
Basil

**Comment by Workshop2** [comment]
Agreed, adding `cli` is causing the package to be listed as pre-release

**Comment by viveks7** [comment]
Can someone please clarify this? Are all releases marked in GitHub release section stable releases?

**Comment by ahmad-moussawi** [comment]
Official release is available now.
