### ISSUE TITLE
How to connect from SqlKata to postgras database?

### ISSUE THREAD

**Issue by nadia-am** [sqlkata/querybuilder#350]
I can't connect it to my postgras data base.

var connection = new SqlConnection("Data Source=localhost;User Id=postgres;Password=3228;Database=TimeManagment");

but it return error "A network-related or instance-specific error occurred while establishing a connection to SQL Server..."

**Comment by eglauko** [comment]
try use Npgsql
https://www.npgsql.org/doc/index.html

**Comment by nadia-am** [comment]
@eglauko  I install postgras with Npgsql and it works correctly but after I install sqlkata I can not connect to postgrase (which is installed with Npgsql) database with sqlkata! and i diddn't find any documentation about it! How can i connect sqlkata to my postgrase database, I want to query it with sqlKata

**Comment by ahmad-moussawi** [comment]
Could you share the part of your code, where you create the connection using Npgsql?

**Comment by nadia-am** [comment]
that is my Npgsql connection , I made a table with pgAdmin 
` using (var connection2 = new NpgsqlConnection("Host=localhost;Username=postgres;Password=3228;Database=TimeManagment"))
            {
                connection2.Open();
                connection2.Execute("Insert into Employee (first_name, last_name, address) values ('Nicolas', 'sdsf', '23434');");
                var value = connection2.Query<string>("Select first_name from Employee;");
                foreach (var eachOne in value)
                {
                    Console.WriteLine(eachOne);
                }
            }`
instead of useing `connection2.Query<string>("Select first_name from Employee;");` i want to use sqlkata query

**Comment by nadia-am** [comment]
I also try to connect to my postgras sql with sqlkata connection but it returns error:

`A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - The specified network name is no longer available.)
`

the code is :
`try
            {
                var connection = new SqlConnection("Data Source=tcp:localhost,5432;User Id=postgres;Password=3228;Database=TimeManagment");
                // "Server=tcp:localhost,1433;Initial Catalog=Lite;User ID=sa;Password=P@ssw0rd"
                var compiler = new SqlServerCompiler();
                var db = new QueryFactory(connection, compiler);
                var user = db.Query("Employee").Get();//.Where("Id", 1).First();
                Console.WriteLine(user);
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.WriteLine(e);
                System.Diagnostics.Debug.WriteLine(e.Message);
            }`

**Comment by eglauko** [comment]
SqlConnection is a class for SqlServer driver, you must use NpgsqlConnection to connect into postgre.
try the code:
```
    try
    {
        var connection = new NpgsqlConnection("Host=localhost;Username=postgres;Password=mypass;Database=TimeManagment");
        var compiler = new PostgresCompiler();
        var db = new QueryFactory(connection, compiler);

        var user = db.Query("Employee").Get();
    }
    catch (Exception e)
    {
        System.Diagnostics.Debug.WriteLine(e); System.Diagnostics.Debug.WriteLine(e.Message);
    }
```

**Comment by nadia-am** [comment]
@eglauko
it return error ,it seems it connect correctly to data source but it can't find my table!
![sqlkata-Npgsql](https://user-images.githubusercontent.com/11175468/75351862-0d656200-58be-11ea-8c90-2204e69430bd.jpg)
but i have a Employee table with data in it.
![pgadmin](https://user-images.githubusercontent.com/11175468/75351978-38e84c80-58be-11ea-8cfc-954794753aad.jpg)

**Comment by eglauko** [comment]
The problem is in the generation of the table name. Double quotes are being added.
See the query below:
`var q = new Query("employee").Where("name", "=", value);`

The following sql is generated:
`SELECT * FROM "employee" WHERE "name" = ?`

To solve this problem, you can inherit the PostgresCompiler class and override some methods, as an example below:
```
public class MyPostgresCompiler : PostgresCompiler
{
    public MyPostgresCompiler()
    {
        OpeningIdentifier = string.Empty;
        ClosingIdentifier = string.Empty;
    }

    public override string WrapValue(string value)
    {
        return value;
    }
}
```

The sql will look like this:
`SELECT * FROM employee WHERE name = ?`

Try running the example below and see the result
```
string value = "John";
var q = new Query("employee").Where("name", "=", value);

var compiler = new PostgresCompiler();
var sql = compiler.Compile(q);
Console.WriteLine(sql.RawSql);

compiler = new MyPostgresCompiler();
q = new Query("employee").Where("name", "=", value);
sql = compiler.Compile(q);
Console.WriteLine(sql.RawSql);
```

**Comment by nadia-am** [comment]
@eglauko thanks a lot that's works .

**Comment by ahmad-moussawi** [comment]
@nadia-am I don't think the correct way is to remove the keyword identifiers, most probably you are are writing the table name incorrectly, most probably the table name is "employee" and not "Employee", check the https://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive for more info

**Comment by nadia-am** [comment]
@ahmad-moussawi I solve the problem with creating custom compiler https://github.com/sqlkata/querybuilder/issues/350#issuecomment-591966860
