### ISSUE TITLE
Mapping table columns with spaces in the names

### ISSUE THREAD

**Issue by saephraim** [sqlkata/querybuilder#353]
Is there any way to map query results (in this case SQL Server) with columns that have spaces in the names to class properties which can't have properties in the names?

Example From Table:
```
CREATE TABLE [dbo].[MyData](
	[ID] [int] NOT NULL,
	[Column With Space] [nvarchar](20) NOT NULL
) ON [PRIMARY]
GO
```

Example To POCO Class:

```
public class MyData
    {
        public int ID { get; set; }

        public string ColumnWithSpace { get; set; }
    }
```
I know that I could probably write a raw query returning columns with out spaces and pass it into SqlKata, or return 'List&lt;dyanmic&gt;' and do something with that, but was hopping for an easier way to handle this since I run into this quite a bit in my current environment.  Thanks!

**Comment by ahmad-moussawi** [comment]
@saephraim no actually there is no such thing, and I think there is no plan to support it, the only option is to use aliases as you have suggested.
I will close this ticket for now, feel free to reopen it if you want to add anything else.
