### ISSUE TITLE
JSON_VALUE in WHERE condition 

### ISSUE THREAD

**Issue by brgrz** [sqlkata/querybuilder#358]
There seems to be an issue with generated SQL if I use .Where with JSON_VALUE function

`query.Where($"JSON_VALUE(PropertiesJson, '$.{filter.Key}')", filter.Value)`

produces

`SELECT * FROM [schema].[Table] WHERE [JSON_VALUE(PropertiesJson, '$].[slug')] = 'culture'`

but it should produce this

`SELECT * FROM [schema].[Table] WHERE JSON_VALUE(PropertiesJson, '$.slug') = 'culture'`

I use the resulting sql to feed it to .FromSqlRaw() of EF Core and obviously if fails.

**Comment by ahmad-moussawi** [comment]
While we have plans for JSON support, for now you can use `WhereRaw(rawStringHere)`
but make sure to protect against SQL injection

**Comment by brgrz** [comment]
If I used WhereRaw it would defeat the reasons why I'd use Sqlkata in the first place because what I wanted was to use the WhereIn, WhereNot and other fluent methods. Instead of using WhereRaw I might just as well use StringBuilder and not add dependency on Sqlkata to my project at all.

**Comment by brgrz** [comment]
After further trial&error I was able to do what I wanted with Sqlkata, WhereRaw and OrderByRaw actually do help.

Like this

			var qb = new Query($"{query.SchemaName}.ContentInCategories ");
			qb = qb.WhereIn("CategoryVariantId", query.CategoryVariantsFilter);
			qb = qb.Where("Active", query.ActiveFilter.ToString()).Where("Publish", query.PublishedFilter.ToString());
			qb = qb.OrderByRaw(query.OrderBy);

This covers 90% of my use cases.
