### ISSUE TITLE
Using COUNT in Select

### ISSUE THREAD

**Issue by fairking** [sqlkata/querybuilder#359]
SqlKata: v.1.1.7
Environment: Asp.Net Core 3.1

I cannot figure out if there is any way to write a general query (Not Raw) with count.
My example:
```
var query = new Query("core_user_groups as ug")
    .Select(new[] { "ug.name", "count(u.id) as user_count" })
    .LeftJoin("core_user_groups_members as ugm", "ug.id", "ugm.user_group_id")
    .LeftJoin("core_users as u", "ugm.user_id", "u.id")
    .GroupBy(new [] { "ug.name" });
```
Gives me the following result:
```
SELECT
  [ug].[name],
  [count(u].[id)] AS [user_count]
FROM
  [core_user_groups] AS [ug]
  LEFT JOIN [core_user_groups_members] AS [ugm] ON [ug].[id] = [ugm].[user_group_id]
  LEFT JOIN [core_users] AS [u] ON [ugm].[user_id] = [u].[id]
GROUP BY
  [ug].[name]
```
I saw an example in the documentation where there was SelectRaw used. As I understand in this case I have to write two separate queries (SelectRaw) for SQL and Postgres databases.

The question is is there any way to use most of the agregation functions without need to use SelectRaw?
For example something like this:
```
var query = new Query("core_user_groups as ug")
    .Select(new[] { "ug.name" })
    .SelectCount("u.id as user_count") // .SelectAvg(), .SelectMax(), etc..
    .LeftJoin("core_user_groups_members as ugm", "ug.id", "ugm.user_group_id")
    .LeftJoin("core_users as u", "ugm.user_id", "u.id")
    .GroupBy(new [] { "ug.name" });
```

Or maybe there is already a solution which is not documented yet.

Thanks for the wonderful project guys.

**Comment by ahmad-moussawi** [comment]
As I understand that you are targeting both Sql Server and Postgres, 
the short answer is no, currently there is no other way to achieve this, you have to use the `SelectRaw` in this case.
and AFAK there is no difference in the syntax between Postgres and SqlServer except for the keyword identifiers `[]` for SqlServer and the quotes for Postgres `""`,
using the brackets will automatically translate to quotes if you are using Postgres even in Raw expressions.

![image](https://user-images.githubusercontent.com/2517523/78680021-a216a300-78f3-11ea-8a6a-f6924fa62791.png)
![image](https://user-images.githubusercontent.com/2517523/78680092-bc508100-78f3-11ea-80f0-49e9747c034e.png)

[Postgres Example on PlayGround](https://sqlkata.com/playground/pgsql?code=var%20query%20%3D%20new%20Query(%22Users%22)%0A%20%20%20%20.Select(%22CountryId%22)%0A%20%20%20%20.SelectRaw(%22count(1)%20as%20%5BCount%5D%22)%0A%20%20%20%20.GroupBy(%22CountryId%22))

[SqlServer Example on PlayGround](https://sqlkata.com/playground/sqlserver?code=var%20query%20%3D%20new%20Query(%22Users%22)%0A%20%20%20%20.Select(%22CountryId%22)%0A%20%20%20%20.SelectRaw(%22count(1)%20as%20%5BCount%5D%22)%0A%20%20%20%20.GroupBy(%22CountryId%22))

**Comment by fairking** [comment]
Thanks for the answer. I am probably going to write my helper extensions myself. So I can add another db compatibility if needed. There also other extensions I need to write eg. CASE, COALESCE, IIF, ISNULL, CONCAT, DATEDIFF, DATEADD, DATEPART. I am using strong type sintax in my all queries within NHibernate.

Please feel free to close the ticket. Thanks for the great project.

**Comment by fairking** [comment]
My query with count looks like this:
```C#
var dep = Db.CreateSqlAlias<Department>("dep");
var adr = Db.CreateSqlAlias<Address>("adr");
var staff = Db.CreateSqlAlias<Staff>("staff");
var bean = BeanAliasWithBaseColumns<DepartmentVm, Department>(dep)
	.WithSelect(x => x.Name, dep.Col(x => x.Name))
	.WithSelect(x => x.Description, dep.Col(x => x.Description))
	.WithSelect(x => x.AddressId, adr.Col(x => x.Id))
	.WithSelect(x => x.AddressName, adr.Col(x => x.AddressLine1))
	.WithCount(x => x.MemberNumber, staff.Col(x => x.Id));

var rootQuery = Db.Query(dep)
	.Select(bean)
	.GroupBy(bean)
	.LeftJoin(adr.TableNameWithAlias, dep.Col(x => x.Address), adr.Col(x => x.Id))
	.LeftJoin(staff.TableNameWithAlias, staff.Col(x => x.Department), dep.Col(x => x.Id))
	.Where(dep.Col(x => x.IsDeleted), false)
	.Where(staff.Col(x => x.IsDeleted), false);
```
