### ISSUE TITLE
Inserting multiple rows in one query

### ISSUE THREAD

**Issue by csantero** [sqlkata/querybuilder#36]
I expected the following code:

```
    var query = new Query("table")
        .Insert(new Dictionary<string, object>
        {
            ["Col1"] = 3,
            ["Col2"] = "blue"
        })
        .Insert(new Dictionary<string, object>
        {
            ["Col1"] = 4,
            ["Col2"] = "red"
        });
```

to yield the following SQL for `ToString()`:

```
INSERT INTO [table] ([Col1], [Col2]) VALUES (3, 'blue'), (4, 'red')
```

but instead it yields:

```
INSERT INTO [table] ([Col1], [Col2]) VALUES (4, 'red')
```

Only the final call to `Query.Insert` has any effect. I'm happy to submit a PR for this feature if you're interested.

**Comment by ahmad-moussawi** [comment]
Hello nice idea!, but I think it's better if the insert method will have an overload that takes list of dictionaries, since the insert is an action method (where it should execute and finalize the query), in the coming version the insert method will execute the query and insert the records in the db, this why I've introduced the `AsInsert` method (still in dev branch)

**Comment by PejmanNik** [comment]
Hi 
Is there any progress on `AsInsert` overload for accepting multi-row insert?
can I help? like Laravel we can accept an array as parameter

**Comment by ahmad-moussawi** [comment]
@PejmanNik can you submit a pull request for it?

**Comment by PejmanNik** [comment]
@ahmad-moussawi Yes of course

**Comment by ahmad-moussawi** [comment]
That's great am ready to merge when ready

**Comment by PejmanNik** [comment]
@ahmad-moussawi  Thanks.
You prefer to add multiple `insert` component to the query or change `InsertClause` class?

**Comment by ahmad-moussawi** [comment]
yes you are right, adding multiple component is a better option 👍

**Comment by PejmanNik** [comment]
Thanks, I am working on it.

**Comment by ahmad-moussawi** [comment]
docs updated, thanks for your support
https://sqlkata.com/docs/update#insert-many
https://sqlkata.com/docs/execution/update#insert-multiple-record

**Comment by PejmanNik** [comment]
Great 👍 
Thank you for this awesome project

**Comment by PejmanNik** [comment]
@ahmad-moussawi  What do you think about to accept query object in the list for support subquery inserting in multi-record?

**Comment by ahmad-moussawi** [comment]
@PejmanNik sorry I didn't catch it, do you mean passing multiple queries on insert ?

**Comment by PejmanNik** [comment]
Thank you, Ahmad.
No. I mean something like this:

```c#
var cols = new [] {"Name", "Price"};
var subQuery = new Query("Price").Select("Amount").Limit(1);

var data = new [] {
    new object[] { "A", subQuery.Clone().Where("Name","A") },
    new object[] { "B", subQuery.Clone().Where("Name","B") },
    new object[] { "C", subQuery.Clone().Where("Name","C") },
};

var query = new Query("Products")
    .AsInsert(cols, data);
```

**Comment by ahmad-moussawi** [comment]
mm and how it will get translated to SQL ?

**Comment by PejmanNik** [comment]
something like this:

```sql
INSERT INTO [Products] ([Name], [Price]) 
VALUES 
 ('A', (select Top 1 Amount from Price where [Name] = 'A') ) 
, ('B', (select Top 1 Amount from Price where [Name] = 'B')),
, ('C', (select Top 1 Amount from Price where [Name] = 'C'))
```

It can be useful for an insert with value to foreign keys ( get from sub query )

**Comment by ahmad-moussawi** [comment]
I think it's about a very specific case, and maybe developers will get confused about it's usage, a better solution would be generating a single query that retrieve the correct results and using it once.

```sql
INSERT INTO [Products] ([Name], [Price])
SELECT [Name], [MaxPrice].[Amount] FROM [Price] JOIN [MaxPrice] ....
```

anyway thanks for you suggestion :)

**Comment by PejmanNik** [comment]
You are right. I'll think of other ways to do it.
but when we talk about foreign keys (unlike to my example) it needs subquery (multi tiple fields from multi tiple table).

Thank you.
