### ISSUE TITLE
SqlKata.Executable and QueryFactory after installing SqlKata 1.1.7 using NuGet 

### ISSUE THREAD

**Issue by paultipper** [sqlkata/querybuilder#366]
I've just installed SqlKata 1.1.7 using NuGet to start experimenting with its capabilities. I'm trying to get started with the examples shown in https://sqlkata.com/docs/, specifically:

```
using SqlKata;
using SqlKata.Execution;
using System.Data.SqlClient; // Sql Server Connection Namespace

// Setup the connection and compiler
var connection = new SqlConnection("Data Source=MyDb;User Id=User;Password=TopSecret");
var compiler = new SqlServerCompiler();

var db = new QueryFactory(connection, compiler);

// You can register the QueryFactory in the IoC container

var user = db.Query("Users").Where("Id", 1).Where("Status", "Active").First();
```

When I try entering the new QueryFactory statement, Visual Studio Pro tells me that it cannot be found. I tried adding the using SqlKata.Execution statement at the start of my source code, but again, this can not found. This is baffling, because I can see it clearly in the source tree in GitHub (https://github.com/sqlkata/querybuilder/tree/master/SqlKata.Execution).

The only difference between my code and yours is that I'm using Npgsql to connect to a Postgres database, rather than to an SQL server, but I wouldn't have thought this was relevant.

Can anyone suggest why QueryFactory and SqlKata.Execution don't appear to be in the SqlKata package I've installed?

**Comment by austinwilcox** [comment]
Did you install both packages with Nuget? I had the same problem, but as soon as I installed SqlKata, and SqlKata.Execution everything was found and works flawlessly.

**Comment by ahmad-moussawi** [comment]
Closing due to no response, feel free to reopen for any further feedback.
