### ISSUE TITLE
SqlServerCompiler compiling AsInsert with @p1 @p2 instead of real values

### ISSUE THREAD

**Issue by g33kz0rd** [sqlkata/querybuilder#367]
My code

`var query = SqlQueryCompiler.Compile(new Query("User").AsInsert(user));
var compiler = new SqlServerCompiler();
var compiledQuery = compiler.Compile(query).Sql;`

Result

`INSERT INTO [User] ([UserId], [FirstName], [LastName], [Email], [Password]) VALUES (@p0, @p1, @p2, @p3, @p4)`

What am I missing? In the playground on the web instead of @p0, @p1, @p2, @p3, @p4 it would fill it with the property values.

Thanks!

**Comment by g33kz0rd** [comment]
![image](https://user-images.githubusercontent.com/1015697/80537474-847cac80-897a-11ea-8b59-cc72a16f97d8.png)

Added expected behaviour from the site playground.

Thanks again!

**Comment by ahmad-moussawi** [comment]
The correct way to execute the query in ADO.net is to use parameters binding, which is explained in the documentation section https://sqlkata.com/docs#compile-only-example
So I see no issues here, 
I will close this for now, if you have any further feedback feel free to reopen.
