### ISSUE TITLE
Unable to provide explicit precedence on combinations such as UNION and INTERSECT

### ISSUE THREAD

**Issue by alexmg** [sqlkata/querybuilder#369]
It does not seem to be possible to be explicit about the precedence when applying more than one combination.

In the example below, without the additional parentheses the `INTERSECT` will take precedence over the `UNION`.

```tsql
(SELECT 1

UNION

SELECT 2)

INTERSECT

SELECT 2
```

Is there a way to workaround this issue and add parentheses as needed to enforce the desired precedence?

**Comment by rafael-queiroz-cko** [comment]
I'm having the same issue

**Comment by ahmad-moussawi** [comment]
Not 100% identical but with subqueries you can achieve the same result 

```cs
var query = 
new Query().From(
    new Query("A").Union(new Query("B")).As("U1")
).Intersect(new Query("C"));
```

[Union and Intersect example](https://sqlkata.com/playground?code=var%20query%20%3D%20new%20Query(%22Player%22).AsInsert(new%20%7B%0A%20%20%20%20Id%20%3D%20%221%22%2C%0A%20%20%20%20Values%20%3D%20%22%7B1%2C2%2C3%7D%22%0A%7D)%3B)
