### ISSUE TITLE
Insert & update with Sql Function

### ISSUE THREAD

**Issue by nikunjratanpara** [sqlkata/querybuilder#370]
Hi

First of all thanks for this great Query Builder. This really make life simple for all .net developers who like to create query by themselves. 

I have new feature request to add support for executing sql functions, user defined functions or sequnce in case of some databases. Which I couldn't found.

I have Function or sequence in database and I want to execute it with insert / update statement. I am looking for below final query for postgres database

**Insert into Tenant (id,name) 
  values (nextval('TenantIdNumber'), 'Test')**

Let me know If I can help you further

Thanks

**Comment by ahmad-moussawi** [comment]
@nikunjratanpara thank you for your feedback, 
does the `UnsafeLiteral` works in this situation 
[Unsafe Literal Example on Playground](https://sqlkata.com/playground/pgsql?code=var%20query%20%3D%20new%20Query(%22Users%22).AsInsert(new%20%7B%0A%20%20%20%20Name%20%3D%20%22Name%22%2C%0A%20%20%20%20Seq%20%3D%20Expressions.UnsafeLiteral(%22nextval(TenantIdNumber)%22)%0A%7D)%3B)

**Comment by nikunjratanpara** [comment]
@ahmad-moussawi 

Thanks for quick reply. 
Yes, This shoud work let me try and update.
I can't find any documentatio on this. That might help users.
Thanks again.

**Comment by ahmad-moussawi** [comment]
Yes actually it's not documented yet, and available only in the latest prerelease.

**Comment by nikunjratanpara** [comment]
Yes It works but for that I need to create seperate entities for create as in most cases properties will be of numeric types Or anonymous types can be used.
Get Outlook for Android



On Sat, May 9, 2020 at 3:20 PM +0530, "Ahmad Moussawi" <notifications@github.com> wrote:















Yes actually it's not documented yet, and available only in the latest prerelease.
