### ISSUE TITLE
Can i ignore some propertys with 'InsertAs'

### ISSUE THREAD

**Issue by absid89** [sqlkata/querybuilder#374]
Can i in sqlkata ignore some propertys with 'InsertAs'?
something like [NotMapped] in EF, so that the compiler skips unnecessary properties when there are a lot of them
thanks for any help

**Comment by nikunjratanpara** [comment]
You can use [Ignore] attribute to skip object property.
https://github.com/sqlkata/querybuilder/blob/master/QueryBuilder/IgnoreAttribute.cs

Please refer below link for version from which [Ignore] attribute available.
https://github.com/sqlkata/querybuilder/issues/284
