### ISSUE TITLE
SqlKata.Execution fails Windows Store Certification 

### ISSUE THREAD

**Issue by jeansusgodney** [sqlkata/querybuilder#381]
I just deployed my UWP app and didn't pass the store certification, because apparently sqlkata.execution calls SNI.DLL that is not supported by Windows 10 SDK. Does anyone have solution for this?  

> Error Found: The supported APIs test detected the following errors:
> API IsTokenRestricted in advapi32.dll is not supported for this application type. sni.dll calls this API.
> Impact if not fixed: Using an API that is not part of the Windows SDK for Microsoft Store apps violates the Microsoft Store certification requirements.

**Comment by ceastwood** [comment]
@jeansusgodney I believe this is actually your program causing this. 

SqlKata.Execution only depends on dapper-- which is connection provider agnostic. Please review this github issue for Microsoft.Data.SqlClient (which I suspect you are using versus System.Data.SqlClient)

https://github.com/dotnet/SqlClient/issues/356

**Comment by jeansusgodney** [comment]
@ceastwood  hi there thanks for taking your time answering the question. 

In fact we only use Microsoft.Data.Sqlite instead the one from System.Data, but our app still fails the certification.

Below you find the libraries  that we use and the result of the certification test. 

<img width="367" alt="Bildschirmfoto 2020-05-25 um 10 18 20" src="https://user-images.githubusercontent.com/23475916/82793581-68810380-9e71-11ea-8a30-670b9b467fa8.png">

<img width="1386" alt="Bildschirmfoto 2020-05-25 um 10 18 53" src="https://user-images.githubusercontent.com/23475916/82793579-67e86d00-9e71-11ea-845e-0d0f5706b76d.png">

**Comment by ceastwood** [comment]
@jeansusgodney 

Can you provide either the github repo url or show me the contents of your App1.csproj?

I think it's the same issue just the Sqllite library.
