### ISSUE TITLE
Insert, Update and Delete Documentation contains typo

### ISSUE THREAD

**Issue by WeLikeAich** [sqlkata/querybuilder#382]
Documentation at https://sqlkata.com/docs/update contains a typo in its Insert Example.

The object presented in the fluent code contains "Title", however the generated SQL contains "Name"

```
var query = new Query("Books").AsInsert(new {
    Title = "Toyota Kata",
    CreatedAt = new DateTime(2009, 8, 4),
    Author = "Mike Rother"
});
```

`INSERT INTO [Books] ([Name], [CreatedAt], [Author]) VALUES ('Toyota Kata', '2009-08-04 00:00:00', 'Mike Rother')`

**Comment by ahmad-moussawi** [comment]
Thank you for reporting, do you mind submitting a PR in the https://github.com/sqlkata/docs repo?
