### ISSUE TITLE
HAVING clause with COUNT(*) not generating correct sql

### ISSUE THREAD

**Issue by dions** [sqlkata/querybuilder#387]
I am using Azure SQL and have constructed the following query as per the SqlKata documentation:

var query = new Query().From(commentsCount).Having("Count", ">", 100);

which generates 

SELECT [PostId], count(1) as Count FROM [Comments] GROUP BY [PostId]) HAVING [Count] > 100

SQL is not happy with this and raises the error, "Invalid column name 'Count'". 

SQL wants the having clause to be "HAVING count(1) > 100"

I suppose I could got raw to move forward, but is there an issue in that incompatible SQL is being generated?

**Comment by ahmad-moussawi** [comment]
The example you provided produce the following sql query and not as you have posted.

```sql
SELECT * FROM (
    SELECT [PostId], count(1) as Count
    FROM [Comments]
    GROUP BY [PostId]
  )
HAVING
  [Count] > 100
```
check this example on the playground [here (having example)](https://sqlkata.com/playground?code=var%20commentsCount%20%3D%20new%20Query(%22Comments%22).Select(%22PostId%22).SelectRaw(%22count(1)%20as%20Count%22).GroupBy(%22PostId%22)%3B%0A%0Avar%20query%20%3D%20new%20Query().From(commentsCount).Having(%22Count%22%2C%20%22%3E%22%2C%20100)%3B)

So the `Count` column is defined in the subquery, which is totally valid,
in other cases you can use the `HavingRaw` method as you have suggested.
So I don't think there an issue here, I will close for now, if you have any further feedback please feel free to reopen it.
