### ISSUE TITLE
Problems with Insert name of variables

### ISSUE THREAD

**Issue by neiesc** [sqlkata/querybuilder#388]
```csharp
var compiler = new SqliteCompiler();
var query = new Query("TodoList").AsInsert(new {
    Name = todoList.Name
});
SqlResult result = compiler.Compile(query);

Console.WriteLine(result.Sql);
```

I'm get `INSERT INTO "TodoList" ("Name") VALUES (@p0)` insted of `INSERT INTO "TodoList" ("Name") VALUES ('teste')`, or better `INSERT INTO "TodoList" ("Name") VALUES (@Name)` because i'm using dapper with SqlKata

**Comment by neiesc** [comment]
https://github.com/sqlkata/querybuilder/issues/367

**Comment by ahmad-moussawi** [comment]
@neiesc  sorry but didn't get the issue yet, could you explain more.


This is the expected behavior, as per the documentation
https://sqlkata.com/docs#compile-only-example.

However if you plan to use dapper, it's better to use the SqlKata.Execution package

**Comment by neiesc** [comment]
In Sqlkata I only intend to use query builder, not execution.
