### ISSUE TITLE
How can I get resultset from stored procedure?

### ISSUE THREAD

**Issue by mgh9** [sqlkata/querybuilder#389]
Here is my procedure in sql server:

```
CREATE PROCEDURE [AUD].[Get] 
    -- Add the parameters for the stored procedure here
AS
BEGIN
    SET NOCOUNT ON;

    SELECT col1, col2 FROM AUD.MyTable
END
```
How can I return the result from this procedure? I can't find any helps in the docs

**Comment by ahmad-moussawi** [comment]
Using the `db.Select("exec [AUD].[Get]")` should do the trick.
Check the Execute Raw Statements in the docs for more info
https://sqlkata.com/docs/execution/fetching-records#execute-raw-statements
