### ISSUE TITLE
Suggestion -  Separate Project Responsibilities

### ISSUE THREAD

**Issue by fulviocanducci** [sqlkata/querybuilder#39]
# Separate Project Responsibilities

I was looking at your new code and realized that now has a file named Query.Execute, it would not be better to make a project and use SqlKata only to generate SQL, for me it is mixing the project, that is, each project makes one one thing generates SQL the other uses SQL to write to the bank and so on?

File: https://github.com/sqlkata/querybuilder/blob/query_execution/QueryBuilder/Query.Execute.cs

I'm saying this because of **AsInert** and **Insert** and so on _because_ if not your class that generates SQL is also resolving the Bank's share would the responsibility increase?

# Comments 

- https://github.com/sqlkata/querybuilder/pull/32#issuecomment-347449675
- https://github.com/sqlkata/querybuilder/pull/32#issuecomment-347665653
- https://github.com/sqlkata/querybuilder/pull/32#issuecomment-347681736

**Comment by ahmad-moussawi** [comment]
@fulviocanducci thanks for your feedback, yes I agree, this was the feedback of @ceastwood and @csantero also, for this reason the branch was not merged and I will cancel it.

**Comment by fulviocanducci** [comment]
@ahmad-moussawi tkanks
