### ISSUE TITLE
Creating a base model

### ISSUE THREAD

**Issue by netbounty** [sqlkata/querybuilder#394]
Hey, how can I create a base model, connected with database like in Laravel? So telling the base model through a example model like User which table to use and connect automatically. Do you have any ideas?

**Comment by ahmad-moussawi** [comment]
@netbounty SqlKata currently act as just an SQL query builder, so it doesn't provide any mapping between SQL and objects (like ORM do or Laravel Eloquent in specific), but you can write your own on top of it.

**Comment by netbounty** [comment]
Thank you. With which class could I create a base class the best way? XQuery?

**Comment by netbounty** [comment]
XQuery or QueryFactory?

**Comment by ahmad-moussawi** [comment]
@netbounty I really didn't get your question, but as a comparison with Laravel, Laravel provides a shared DB instance (here it is a QueryFactory) and uses this for db interactions, so there is no direct relation between the models and the shared db instance.
