### ISSUE TITLE
UUID_TO_BIN(UUID()) as value when inserting a record

### ISSUE THREAD

**Issue by ansarizafar** [sqlkata/querybuilder#397]
Thanks for the amazing project . I wanted to know is it possible to use UUID_TO_BIN(UUID()) as value when inserting a record?

My second question is why AsInsert() is not Async and why it can't accept transaction?

**Comment by ahmad-moussawi** [comment]
Hello @ansarizafar, for the first question you can use the `UnsafeLiteral` expression, check this example on the playground
[Unsafe Literal Example](https://sqlkata.com/playground?code=using%20static%20SqlKata.Expressions%3B%0A%0Avar%20query%20%3D%20new%20Query(%22Table%22).AsInsert(new%20%7B%0A%20%20%20%20Id%20%3D%20UnsafeLiteral(%22UUID_TO_BIN(UUID())%22)%2C%0A%20%20%20%20Name%20%3D%20%22Another%20value%20here%22%0A%7D)%3B)

The `AsInsert` does not execute the query, it just informs the compiler that this query is an INSERT query, 
to execute the query you have to use the `.Insert()` method from the `SqlKata.Execution` package.

The `Insert()` method call the `AsInsert()` method under the hood.

**Comment by ansarizafar** [comment]
@ahmad-moussawi Thanks for the help. I think UnsafeLiteral is missing from the documentation.

I am coming from EF core, So far I really like SqlKata. Two features will make SqlKata a right choice for any project Multimapping https://github.com/sqlkata/querybuilder/pull/253 and CancelationToken https://www.c-sharpcorner.com/article/asp-net-mvc5-asynchronous-controllers-cancellation-token/

**Comment by ahmad-moussawi** [comment]
Thanks @ansarizafar I will take your feedback into consider.
