### ISSUE TITLE
How to concatenate strings with sqlkata? 

### ISSUE THREAD

**Issue by jeansusgodney** [sqlkata/querybuilder#399]
I am trying to write this kind of query
`SELECT * FROM tbl WHERE id || id2  IN (SELECT column1 || column2  FROM tbl2 WHERE tbl = 'tbl1')`

```
Query query = new Query("tbl2")
                    .Select("column1 || column2 ")
                    .Where("tbl", "tbl1");

return new Query("tbl").WhereIn("id || id2", query):

```

But they don't return any result

**Comment by ahmad-moussawi** [comment]
Using `SelectRaw` can help in this case,
Something like this [Example on Playground](https://sqlkata.com/playground/oracle?code=var%20inner%20%3D%20new%20Query(%22tbl%22).SelectRaw(%22id%20%7C%7C%20id2%20as%20concat_id%22)%3B%0A%0Avar%20query%20%3D%20new%20Query().From(inner%2C%20%22inner%22).WhereIn(%0A%20%20%20%20%22concat_id%22%2C%20%0A%20%20%20%20new%20Query(%22tbl2%22)%0A%20%20%20%20.SelectRaw(%22column1%20%7C%7C%20column2%20as%20col%22)%0A%20%20%20%20.Where(%22tbl%22%2C%20%22tbl1%22)%0A))

```cs
var inner = new Query("tbl").SelectRaw("id || id2 as concat_id");

var query = new Query().From(inner, "inner").WhereIn(
    "concat_id", 
    new Query("tbl2")
    .SelectRaw("column1 || column2 as col")
    .Where("tbl", "tbl1")
)
```

will produce 
```sql
SELECT
  *
FROM
  (
    SELECT
      id || id2 as concat_id
    FROM
      "tbl"
  ) "inner"
WHERE
  "concat_id" IN (
    SELECT
      column1 || column2 as col
    FROM
      "tbl2"
    WHERE
      "tbl" = 'tbl1'
  )
```

**Comment by ahmad-moussawi** [comment]
@jeansusgodney I will close this for now, if you have any feedback feel free to reopen it
