### ISSUE TITLE
could you provider some tips about combining dynamic conditions in where(func()), especially meaning 'or'

### ISSUE THREAD

**Issue by wddpct** [sqlkata/querybuilder#4]
sorry for my pooring english skill. thank you.

I got the following trouble. I build a sqlbuilder service for my domain bussinessw with your sqlkata,and whatever the  tables or properties I want to join and search in the postgresql are depending on the viewpage form's dynamic condition, such as adding a extra input text or operator(if you have heard of i2b2,a medical service,I do the same things. ). 

so, the form may have serveral groups('组' in chinese),it is 'and' relation between those groups. and in a specific group, there were several conditions, it is 'or' relation between those condition.

![image](https://user-images.githubusercontent.com/8480318/27467176-ac932510-5812-11e7-8f0e-5dc75f948180.png)

between the group, I could use 'foreach' and your fluent api to continually adding the where method.but in a specific group, I can't guarantee the count of 'or' condition,so ……

```
query.From("Countries")
    .Where(q => 
        q.Where("Population", "<", 100)
         .OrWhere("Population", ">", 200) // i can't guarantee the count.
    )
```
so , could you provider some tips, thanks any way.if you do not understand my poor english, i am sorry

**Comment by ahmad-moussawi** [comment]
Something like:
```cs
class Group {
 public List<Condition> Conditions {get; set;}
}

class Condition {
 public string Field {get; set;}
 public string Operator {get; set;} 
 public object Value {get; set;}  
}

var query = new Query("Countries");

foreach(Group group in groups) 
{
   query.Where(q => {
      foreach(Condition c in group.Conditions)
      {
         q.OrWhere(c.Field, c.Operator, c.Value);
      }
   });
}

```

**Comment by ahmad-moussawi** [comment]
I will close this for now, feel free to reopen if something is not clear

**Comment by rs199483** [comment]
@ahmad-moussawi I need to create groups like you have above but your code will not compile.
.NetFiddle [here](https://dotnetfiddle.net/HUfsih)

> Compilation error (line 37, col 18): Not all code paths return a value in lambda expression of type 'System.Func<SqlKata.Query,SqlKata.Query>'
>Compilation error (line 37, col 18): Cannot convert lambda expression to type 'object' because it is not a delegate type

**Expected output:**

`SELECT * FROM [Countries] WHERE ([Group1Field1] = @p0 OR [Group1Field2] > @p1 OR [Group1Field3] < @p2 OR [Group1Field4] = @p3) OR( [Group2Field1] = @p4 OR [Group2Field2] >= @p5 OR [Group2Field3] <= @p6)`

**Comment by ahmad-moussawi** [comment]
@rs199483 thanks for the update, yes this is outdated now, I will update the original answer

**Comment by rs199483** [comment]
I think this should work:


            var query = new Query("Countries");
		
		foreach (Group group in groups)
		{
			query.OrWhere(q => {
			foreach (Condition c in group.Conditions)
			{
				q.OrWhere(c.Field, c.Operator, c.Value);
			}
			return q;
		
			});
			
		}
