### ISSUE TITLE
Join On with and

### ISSUE THREAD

**Issue by generik0** [sqlkata/querybuilder#40]
Hi

Is it possible to have and AND with the ONs in a join?

i.e:
FROM            Foo INNER JOIN
                         Bar ON Foo.XId = Bar.XId AND Foo.YId = Bar.YId 

There is an "OrOn" but how to do the AndOr?

**Comment by generik0** [comment]
I guess it is just new Join("table").On("foo.x","bar.x").On("foo.y","bar.y")

**Comment by ahmad-moussawi** [comment]
Yes exactly
