### ISSUE TITLE
QUERY UPDATE WITH INNER JOIN [MYSQL]

### ISSUE THREAD

**Issue by srburton** [sqlkata/querybuilder#405]
Hello I have a query with inner join that works, I would like to know if you can reproduce it with SqlKata, I tried it in many ways and I was not successful.

My SQL 
```sql
UPDATE  activity_watch as act_wtch 
INNER JOIN activity as act ON act_wtch.activity_id = act.id
SET act_wtch.activity_watch_type_id = 3
WHERE act_wtch.activity_friend_id = 1 AND 
      act.user_id = 57;
```

**Comment by ahmad-moussawi** [comment]
No Actually there is no support for this at the moment, I will close it here it's related to #182 and #16
