### ISSUE TITLE
curly brackets being replaced by square brackets

### ISSUE THREAD

**Issue by thedarkvessle** [sqlkata/querybuilder#407]
when runnning the following code in c# 
new SqlServer2012Compiler().Compile(new Query().FromRaw("select '{}')"))
the returned value is []
does this have something to do with parameters?

**Comment by ahmad-moussawi** [comment]
By default, SqlKata uses the `{}` and `[]` to identify tables and columns identifiers in the raw expressions.

```cs
new Query("table").WhereRaw("[col] = 1")
```
this will get translated to (MySql)
```sql
SELECT * from `table` where `col` = 1
```

To avoid this, you can escape the characters 

```cs
var query = new Query().FromRaw(@"select '\{\}')");
```

check example [here](https://sqlkata.com/playground?code=var%20query%20%3D%20new%20Query().FromRaw(%40%22select%20'%5C%7B%5C%7D')%22)%3B)

**Comment by thedarkvessle** [comment]
thank you very much
