### ISSUE TITLE
Suggest Splitting into multiple projects

### ISSUE THREAD

**Issue by abbasmhd** [sqlkata/querybuilder#408]
Hi @ahmad-moussawi,
To reduce the code base complexity, I suggest creating a separate project or repo for the different RDMS, 
instead of jamming everything in one project and try to support them all,

I suggest you create a project for SQL Server another for MySQL, etc...
 - SqlKata.SqlServer
 - SqlKata.MySql
 - SqlKata.Oracle
 - etc...

and that will allow for easily extend on some RDMS specific syntax, Such as Cross Apply specific for SqlServer.

Please let me know if you need help with that.

**Comment by ahmad-moussawi** [comment]
@abbasmhd I don't really see any added value for this at the moment.
anyway thank you for your suggestion.
