### ISSUE TITLE
Use Where DateTime without miliseconds 

### ISSUE THREAD

**Issue by Shurpop** [sqlkata/querybuilder#409]
Hello,

There is any possibility to filter DateTime without milliseconds? 

Some DateTime fields of our sql server database contain milliseconds: 2013-10-17 17:59:29.360 

But inputs doesn't know about the milliseconds: 2013-10-17 17:59:29

There is any possibility to filter only with a format of smalldatetime ( 'yyyy-MM-dd HH:mm:ss' ) without using WhereRaw ¿?

Thanks for the help.

And very good job with the library!

**Comment by ahmad-moussawi** [comment]
You can create your own extension something like 
```cs
public Query WhereDateSecond(this Query query, string column, DateTime date)
{
  return query.Where(q => {
    return q.Where(column, ">=", date).Where(column, "<", date.AddSeconds(1));
  })
}
```
This will consider everything between this interval

**Comment by ahmad-moussawi** [comment]
@Shurpop does this work for you?

**Comment by Shurpop** [comment]
Yes! It worked for me. Thanks!
