### ISSUE TITLE
Missing Method Exception

### ISSUE THREAD

**Issue by madben2000** [sqlkata/querybuilder#410]
After upgrading to Version 2.2.0 I get System.MissingMethodException:

Method not found: 'Void SqlKata.Execution.QueryFactory..ctor(System.Data.IDbConnection, SqlKata.Compilers.Compiler, Int32)'.

I also read this with this Humanizer package, but downgrade to 2.6.2 did not work for me. But I need latest SqlKata version because of transactions.

Any idea?

**Comment by LenSoft-Softwares** [comment]
Hi!
I have the same issue when using 2.2.0
```
System.IO.FileLoadException
  HResult=0x80131040

Inner Exception 1:
FileLoadException: The "Humanizer, Version=2.8.0.0, Culture=neutral, PublicKeyToken = 979442b78dfc278e" file or section, or one of its dependencies is not loadable. The definition of a hit assembly is not the same as the section reference. Exception HRESULT value: 0x80131040
```
What can we do now?

**Comment by ahmad-moussawi** [comment]
I really believe that forcing Huminazer 2.6.2 will solve the issue,
@madben2000 could you try clearing the Nuget cache then restore the packages again?.

**Comment by ahmad-moussawi** [comment]
duplicate of #435
