### ISSUE TITLE
WHERE values come up as @p0, @p1 etc. in every query (in Unity)

### ISSUE THREAD

**Issue by MaxwellDexter** [sqlkata/querybuilder#416]
Hi I'm using SqlKata `v2.2.0` (no execution package) in Unity `2019.3.14f1` on a Mac. I have the 'Api Compatibility Level' configured at `.NET 4.x`.
Whenever I try and compile a query with a `WHERE` statement it doesn't inject the values into the query when I retrieve it as an SQL string.
Using the same(ish) code from the default playground scenario:
```
MySqlCompiler compiler = new MySqlCompiler();
var query = new Query("Users")
        .Where("Name", "Sami")
        .Where(q =>
            q.Where("Country", "Lebanon")
            .OrWhere("Country", "France")
        );
print(compiler.Compile(query).Sql);
```
I get the result:
`SELECT * FROM "Users" WHERE "Name" = @p0 AND ("Country" = @p1 OR "Country" = @p2)`

I'm using the SQLite compiler but it also happens for the others:
SQLServer: `SELECT * FROM [Users] WHERE [Name] = @p0 AND ([Country] = @p1 OR [Country] = @p2)`
MySQL: `SELECT * FROM 'Users' WHERE 'Name' = @p0 AND ('Country' = @p1 OR 'Country' = @p2)`

I've tried this on other queries and get a similar result:
`SELECT * FROM "ConsumableData" INNER JOIN "ItemData" ON "ConsumableData"."ID" = "ItemData"."ID" WHERE "ConsumableData"."ID" = @p0`

`RawSql` works, all of the `@pX`s come up as `?`. I'd rather be able to use the package like it's intended however.
Any thoughts on this?

**Comment by MaxwellDexter** [comment]
This is apparently expected behaviour.

**Comment by ahmad-moussawi** [comment]
the `SqlResult.ToString()` is what you expect, but this is extremely dangerous since it will open the doors for SQL injection.

**Comment by MaxwellDexter** [comment]
Is there a way I can generate the SQL string with the values in the string rather than `@p0`? Or do I have to use the `NamedBindings` property to map them?
