### ISSUE TITLE
Row as Dictionary<string, object> via GetDictionaryAsync

### ISSUE THREAD

**Issue by pavelvondrasek** [sqlkata/querybuilder#418]
Hi,

I'm beginner with SqlKata. I'm very happy that found tool which allows me to create low-level SQL queries but my project needs dynamic results too. Now I've problem with `GetDictionaryAsync`:

```csharp
var query = _db
   .Query("cms.contents")
   .SelectRaw("values->'name' as name")
   .Where("type", "product");

var dictionary = await _db.GetDictionaryAsync(query);
```

Now dictionary is null :(
But if I use sync overload `GetDictionary` all works fine. I think that something is wrong with async overload.

**Comment by ahmad-moussawi** [comment]
@pavelvondrasek , Could you share your environment details (os, .net runtime, and SqlKata version used)?

**Comment by pavelvondrasek** [comment]
Yes, of course.

I'm on macos Catalina on Postgres 12 which is on remote server with Debian.
Using .NET Core SDK 3.1.402, SqlKata 2.2 and Npgsql 4.1.5

**Comment by ahmad-moussawi** [comment]
I've identified the issue and fixed in the nightly build, you can get it from https://www.myget.org/feed/sqlkata/package/nuget/SqlKata

Related PR: #419

**Comment by pavelvondrasek** [comment]
Thank you for your kindliness and great support! 💯 ❤️
