### ISSUE TITLE
WhereDate has some weird behaviour

### ISSUE THREAD

**Issue by fairking** [sqlkata/querybuilder#422]
SQLKata v2.2.0
Oracle 11g

I was trying to build a query against Oracle and encountered a problem. The given query is not working as expected (Error: ORA-01722: invalid number) The `MyDate` is TIMESTAMP.

![image](https://user-images.githubusercontent.com/13495631/95724648-89a28f00-0c6e-11eb-9fa4-b5efc46f3c4b.png)

I cannot understand why SQLKata converts the datetime into a Char instead just compare like the example bellow:

```
SELECT * FROM "Users"
WHERE "Name" = 'Sami'
  AND (
   MyDate <= '2020-10-12 08:35:59'
    OR "Country" = 'France'
  )
```

Does the method `WhereDate` suppose to compare **dates without time**? If it does why the SQL query in **MSSQL** looks like this:

![image](https://user-images.githubusercontent.com/13495631/95725833-0e41dd00-0c70-11eb-8b22-e780dec01220.png)

instead of this?

```
SELECT * FROM  [Users]
WHERE [Name] = 'Sami'
  AND (
    CAST([MyDate] AS DATE) <= '2020-10-12' -- No time
    OR [Country] = 'France'
  )
```

**Comment by fairking** [comment]
My solution was to use `Where` instead. But I guess the `WhereDate` is for date only comparison without time which is still not correct I think.

![image](https://user-images.githubusercontent.com/13495631/95732381-988e3f00-0c78-11eb-90b6-b2f09af672c5.png)

**Comment by ahmad-moussawi** [comment]
@fairking the `WhereDate` assumes that you pass a valid date (without a time), and it casts the target column as date for the comparison, here in the case of Oracle it does an extra job which is casting also the value, and this will be removed in future versions.


so it's the developer's responsibility to pass a valid date.

if you have any suggestions for improvement please let me know.

**Comment by fairking** [comment]
Alright. I see what you mean. I should always cast to date to give the right result. 
![image](https://user-images.githubusercontent.com/13495631/96841289-83b56680-1443-11eb-86c7-2798ca1da814.png)


Closing the ticket then.
