### ISSUE TITLE
Column name like 'Qty as Litre' is treated alias name

### ISSUE THREAD

**Issue by jaiganeshs** [sqlkata/querybuilder#427]
We have a table where the column name is "Qty as Litre". When using this column in insert,update queries it is interpreted as alias name, thus breaking the query as [Qty] as [Litre]. This is breaking the query. Is there a way to solve this?

```
var insertQuery = new Query("Table01").AsInsert(new Dictionary<string, object> { { "Int as Field01", 1 }, { "Long as Field01", 1 } });
sqlResult = compiler.Compile(insertQuery);
Console.WriteLine($"Insert Query: {Environment.NewLine}{sqlResult.Sql}");

Generated Output:
INSERT INTO [Table01] ([Int] AS [Field01], [Long] AS [Field01]) VALUES (@p0, @p1)

```

**Comment by ahmad-moussawi** [comment]
The only solution in your case is to override the needed compiler and override the `Wrap` method https://github.com/sqlkata/querybuilder/blob/master/QueryBuilder/Compilers/Compiler.cs#L800

```cs
public class CustomSqlServerCompiler: SqlServerCompiler 
{
  public override string Wrap(string value)
  {
    // do your own logic here
  }
}
```

**Comment by jaiganeshs** [comment]
@ahmad-moussawi thank you.
