### ISSUE TITLE
Curly Brackets compiled into Square Brackets: Request to disable column identifier

### ISSUE THREAD

**Issue by EyreC** [sqlkata/querybuilder#430]
This works:

```     
var query = new Query("tableName");
query.Select("id").WhereNot("title", "[{}]")
```

And yields:
`SELECT id FROM tableName WHERE title != '[{}]'`

However, curly braces in the SelectRaw or WhereRaw get compiled into square brackets:
```
var whereRawQuery = new Query("tableName");
query.Select("id").WhereRaw("title != '[{}]')
```

This compiles into:
`SELECT id FROM tableName WHERE title != '[[]]'`

Equivalently the following also occurs:
```
Query selectBracket = new Query("tableName"); 
selectBracket.SelectRaw("id, (select id, title from otherTable where title != '[{}]' for json path) ");
```

This compiles into:
`SELECT id (select id, title from otherTable where title != '[[]]' for json path) FROM tableName`

Note the '[{}]' is now '[[]]'.

My guess is that the has something to do with how SqlKata identifies columns.If this is the case, would it be possible to optionally disable this text replacement?

I am trying to persuade my organisation to use SqlKata more extensively, but we'd likely still need to make use of the .Raw functions in SqlKata while things get ported over.

**Comment by ahmad-moussawi** [comment]
You should escape it with \ something like this should work
```
[\{\}]
```

**Comment by EyreC** [comment]
The backslash is not valid escape syntax for the curly brace in C# - I get a compile error attempting to use it. The escape sequence for a curly place is to duplicate it like this:
`[{{}}]`
Usually I'd do this if I was using a string literal and the curly braces were reserved for specifying variables. However this just gets compiled into 
`[[[]]]`

Are you able to escape the curly brace @ahmad-moussawi ? If so, where and how do you do so?

**Comment by ahmad-moussawi** [comment]
Yes check this #407 similar to your case.
and here a live example
[Escape curly braces in Raw Expression](https://sqlkata.com/playground/sqlserver?code=var%20query%20%3D%20new%20Query(%22tbl%22).WhereRaw(%40%22%5Bescaped%5D%20!%3D%20'%5C%7B%5C%7D'%20and%20%5Bdescription%5D%20%3D%20%7Bnon%20escaped%7D%22)%3B)

**Comment by EyreC** [comment]
I've managed to do that, thank you @ahmad-moussawi
