### ISSUE TITLE
aspnet core di container error

### ISSUE THREAD

**Issue by godshades** [sqlkata/querybuilder#432]
Hi, I follow this setting https://sqlkata.com/docs/execution/setup#aspnet-core-di-container
But visual studio display error

'IServiceCollection' does not contain a definition for 'Add' and the best extension method overload 'ConfigurationExtensions.Add<QueryFactory>(IConfigurationBuilder, Action<QueryFactory>)' requires a receiver of type 'IConfigurationBuilder'

**Comment by chrisgate** [comment]
services.AddTransient<QueryFactory>(e =>
            {
               
                var connStr = configuration.GetConnectionString("PostgresConnection");
                var connection = new NpgsqlConnection(connStr);

                var compiler = new PostgresCompiler();
                return new QueryFactory(connection, compiler)
                {
                    // Log the compiled query to the console
                    //Logger = compiled =>
                    //{
                    //    Console.WriteLine(compiled.ToString());
                    //}

                    Logger = compiled =>
                    {
                        logger.LogInformation(compiled.RawSql);
                        System.Diagnostics.Debug.WriteLine(compiled.ToString());
                    }
                };

            });

**Comment by chrisgate** [comment]
@godshades u can close this if this met ur need.

**Comment by godshades** [comment]
> @godshades u can close this if this met ur need.

thank you
