### ISSUE TITLE
SqlKata's Humanizer.Core version is incompatible with later versions (affecting compatibility with .NET 5 EF and other assemblies)

### ISSUE THREAD

**Issue by jwstadler** [sqlkata/querybuilder#435]
I am working on a project that includes SqlKata and EF Core and during our upgrade to .NET 5, we have encountered an issue related to an incompatibility in versions of Humanizer. After upgrading, I am encountering the following error when I attempt to execute a query:

```
System.MissingMethodException: Method not found: 'System.String Humanizer.InflectorExtensions.Singularize(System.String, Boolean)'.
   at SqlKata.Execution.QueryFactory.handleIncludes[T](Query query, IEnumerable`1 result)
   at SqlKata.Execution.QueryFactory.Get[T](Query query, IDbTransaction transaction, Nullable`1 timeout) in C:\Projects\querybuilder\SqlKata.Execution\QueryFactory.cs:line 85
   at SqlKata.Execution.QueryExtensions.Get[T](Query query, IDbTransaction transaction, Nullable`1 timeout) in C:\Projects\querybuilder\SqlKata.Execution\Query.Extensions.cs:line 12
   at SqlKata.Execution.QueryExtensions.Get(Query query, IDbTransaction transaction, Nullable`1 timeout) in C:\Projects\querybuilder\SqlKata.Execution\Query.Extensions.cs:line 22
  ...
```

It appears that [Microsoft.EntityFrameworkCore.Design](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Design) requires Humanizer.Core >= 2.8.26. while [SqlKata.Execution](https://www.nuget.org/packages/SqlKata.Execution/) requires Humanizer.Core >= 2.6.2

Humanizer.Core broke version compatibility between these two versions (see https://github.com/Humanizr/Humanizer/issues/1013) so the 2.6.2 version that SqlKata was built against is not compatible with the version used by Microsoft.EntityFrameworkCore.Design. When the 2.8.26 version is selected, the above exception is thrown. 

Updating SqlKata locally to the latest version of Humanizer appears to resolve the issue.

**Comment by FabrizioSalis** [comment]
I created this fork, which solves the issue, by changing the .NET reference and upgrading the nuget packages: 
https://github.com/FabrizioSalis/querybuilder

**Comment by mgh9** [comment]
I had the same problem and had to downgrade to 1.1.7 both SqlKata and SqlKata.Execution

**Comment by aboah** [comment]
I wish this issue on SqlKata's Humanizer.Core is tackled as immediately as can be possible

**Comment by ahmad-moussawi** [comment]
This PR #443 should solve the issue, it's now merged and you can try the latest package from MyGet, if the issue get solved I will publish it in NuGet

**Comment by stew-dev-github** [comment]
The MyGet package is for SqlKata rather than SqlKata.Execution which is what holds the dependency on Humanizer.Core, any chance we could get a MyGet for SqlKata.Excecution or an updated NuGet

**Comment by mrodrigues95** [comment]
Any update on this? I'm forced to use 1.1.7 on both SqlKata and SqlKata.Execution until this is resolved.

**Comment by ahmad-moussawi** [comment]
I think this should be resolved now, the latest release https://www.nuget.org/packages/SqlKata/2.3.2 depends on the latest version of Humanizer
