### ISSUE TITLE
[SQLServer] insert bool value

### ISSUE THREAD

**Issue by stefaniaolivares** [sqlkata/querybuilder#437]
Hi! I'm having trouble with inserting bool values ​​in sql server. The compiler translate bool with true or false instead of 1 or 0. How can I solve this issue?

`var query = new Query(Table).AsInsert(model);
var sql = SqlServerCompiler().Compile(query).ToString();`

The value of the sql variable is 
INSERT INTO [Table] ([IsRunning], [IsEnabled]) VALUES (false, true)

Thanks!!

**Comment by ahmad-moussawi** [comment]
@stefaniaolivares have you tried to execute this directly in the Database?
The `ToString()` representation is not 100% similar to what get executed

**Comment by stefaniaolivares** [comment]
Yes I tried but the query not working, maybe I'm doing something wrong.

**Comment by mzolonk** [comment]
Your .ToString() seem to be converting the the object and not the contents of it.

 Insert does work, you need to make sure that each value is either a string or 0/1

tested the insert with this code.

```
CREATE TABLE dbo.SomeTable(IsRunning BIT, IsEnabled BIT)
GO

INSERT dbo.SomeTable(IsRunning, IsEnabled)
VALUES('TRUE', 'FALSE')
GO

INSERT dbo.SomeTable(IsRunning, IsEnabled)
VALUES(0, 1)
GO
```

**Comment by ahmad-moussawi** [comment]
#503 
#510
