### ISSUE TITLE
WhereConains fails when when object is guid and contains {}

### ISSUE THREAD

**Issue by srenrd** [sqlkata/querybuilder#440]
WhereConains fails when when object is guid and contains {}, e.g. {65F52295-439B-4D3D-A0E3-67563EBC514C}

var myGuid = Guid.Parse({65F52295-439B-4D3D-A0E3-67563EBC514C});
var licenseTransactionLog = new Query("CMP_LicenseTransactionLog")
                .Select("CMP_Log_GUID")
                .Where("CMP_LTL_Type", "Saved order to DB")
                .WhereContains("CMP_LTL_Data", myGuid);
Error: System.ArgumentException: 'Expecting a non nullable string'

To fix this i have to use .ToString() on the guid.

So this code is working as intended:
var myGuid = Guid.Parse({65F52295-439B-4D3D-A0E3-67563EBC514C});
var licenseTransactionLog = new Query("CMP_LicenseTransactionLog")
                .Select("CMP_Log_GUID")
                .Where("CMP_LTL_Type", "Saved order to DB")
                .WhereContains("CMP_LTL_Data", myGuid.ToString());

This doesn't seem logical for me, did i find a bug or is it working as intended?

**Comment by ahmad-moussawi** [comment]
This is the expected behavior, since it expects a string and you are passing a Guid
