### ISSUE TITLE
Make all Compiler Compile methods protected virtual 

### ISSUE THREAD

**Issue by b-twis** [sqlkata/querybuilder#449]
Hi,

In the Compiler.cs file all methods except 2 are marked as protected virtual and thus allow override in a custom Compiler. 
This makes it impossible to complete implementation of a custom compiler class.

private SqlResult CompileUpdateQuery(Query query)

private SqlResult CompileDeleteQuery(Query query)

Would it be possible to get this updated and published to nuget as it is blocking implementation of extensions to the SQLServer compiler I would like in my project. 

Thanks,
Basil

**Comment by b-twis** [comment]
Thank you for the quick PR acceptance. Would it be possible to publish it to nuget also?

**Comment by ahmad-moussawi** [comment]
@b-twis a Nuget package was published few days ago
