### ISSUE TITLE
SqlKata.Execution

### ISSUE THREAD

**Issue by ceastwood** [sqlkata/querybuilder#45]
@ahmad-moussawi 

I personally feel like the execution library should be more inline with the format/interfaces that Dapper follow since that is going to be the de-facto execution handler here.  

Also, it makes me nervous with all of the unchecked casting to XQuery; I can see people and probably myself forgetting and passing a raw Query object in for the InvalidCastException often.

Please take a moment to review the [query-execution-2 branch](https://github.com/sqlkata/querybuilder/tree/query-execution-2). What I have in there isn't set in stone yet; I'd be open to input but wanted to get something up we could look at.

Notes: 
_a) TargetFrameworks have been extended:_

1. QueryBuilder: netstandard1.3/2.0, and net45
2. QueryBuilder.Tests: netcoreapp2.0;net462
3. QueryBuilder.SqlServer.Tests: netcoreapp2.0;net462
4. QueryBuilder.Execution (both): netstandard2.0, net452/462

b) I followed a very Newtonsoft.Json-esque approach to configuration. Right now the only setting is the compiler, but there will probably be others going forward. I figure the standard use-case would be a global setting object but to allow for specialized requests; so all of the extension methods have a parameter for alternative settings. Right now, if settings aren't set, defaults to SqlServerCompiler but we can change that behavior no problem.

c) There are more methods we are going to call on Dapper; the ones I have so far in Execution2.Async.cs were auto-generated from the Dapper source by a parser I started writing using Roslyn. There are a bunch more calls we can facade-- I just need a little time to spend on learning Roslyn better ;D I think it's worth while to have a tool to generate the calls for everything we don't have to do manually.

c) I didn't spend much effort yet on refactoring test resources to share accross database test libraries; SqlServer.Tests will probably change for the better.

**Comment by ceastwood** [comment]
Also please note that the SqlServer tests require a local sqlserver install. Haven't quite worked that into CI yet either.

**Comment by ceastwood** [comment]
So there were some mistakes made ;) xUnit is a little different. But as of now:

-Only sqlserver tests, i'll try to go and scaffold out postgres and mysql + setup the engines in appveyor
-Added testSettings.dev.json to .gitignore so we can have local non appveyor connection strings ;D
-Fixed an error in my ways and removed my GetAwaiter().GetResult() that was deadlocking my xunit tests. updated xunit (that uses roslyn now to syntax check out tests lol)

I found some tests DeepJoin / CteAndBindings that fail, they didn't have the fact attribute applied and some assert(s) that were the wrong direction.

I'll try to commit some stuff later but it looks like xunit is still paralellizing some tests causing the db ones to fail.

**Comment by ahmad-moussawi** [comment]
Hi Thanks for the efforts :), actually I didn't have the time to review what you have applied, 

Could you explain more what do you mean exactly by following Dapper format ?

For the XQuery casting, actually we will use the factory pattern, so developers will not fall into this problem, anyway we can enhance it, maybe by throwing a valid exception.

a) TargetFrameworks have been extended: Thanks this is a necessity 
b) Since we will use the factory pattern, we can skip this
c) Thanks, let me know how can I help

**Comment by ceastwood** [comment]
@ahmad-moussawi 
That's why I had published some unit tests to show the api format, but by the dapper format, I mean the way its' API is interacted with. 

For example: (given a local variable called 'conn')
`var dClass = await conn.SingleAsync<SomeClass>("SELECT TOP(1) * FROM [table]");`

I believe the execution API should also map directly on IDbConnection. Example using SqlKata.Execution2:
`var query = new Query("table").SelectRaw("*").Limit(1);`
..
`var dClass = await conn.SingleAsync(query);`

The implementation I provided is also factory-esque pattern as well, I will try to explain some below and I'm going to try and push up a few more unit tests later to show the different variations.

Firstly, before I explain; SqlKata.Execution currently accepts a parameter of Query (and not XQuery) to which is then blindly cast which I feel is bad form considering it completely subverts **all** compile time checks. Throwing an exception isn't making things better because the failure would only happen at **runtime** and also not very helpful. There the only recourse is to change all public methods to accept XQuery for that particular implementation (including the extension methods). Because this is perfectly valid in that implementation:
```
var query = new Query("TABLE").Select("Integer").First()
(throws InvalidCastException)
```


**On to the explanation;**
The compilation of a Query to a SqlResult itself should be done by a factory while having nothing to with execution, and that is what I have implemented in my branch.
> note: QueryBuilder.cs, QueryBuilderSettings.cs, QueryBuilderExtensions.cs

We provide the ability for a global default settings object for ease of use, while providing an overload that accepts an explicit settings object so that end-users can customize the compilation.
> example: 95% of the app is destined for SqlServer, but the remaining 5% are calls into postgres and mysql separately or some other proportion.

The settings object used by the factory can be extended, this means that end-users can subclass and use their own settings object or write extensions methods ontop of the settings object, allowing for them or us to further build extensions directly on-top of SqlKata.

**As for execution**
- There are quite a few distinct dapper calls, all of which are useful. Why write them by hand?
- Some of the more useful methods require parameters like transaction, and timeout which yours have left out. Default parameters means we don't need to duplicate many overloads.
- 
```
//SqlKata.Execution
public static T First<T>(this Query query)
{

    var xQuery = (XQuery)query;

    var compiled = xQuery.Compiler.Compile(query.Limit(1));

    return xQuery.Connection.QueryFirst<T>(compiled.Sql, compiled.Bindings);

}
//SqlKata.Execution2
public static Task<T> QueryFirstAsync<T>(this IDbConnection cnn, Query query, QueryBuilderSettings settings = null, IDbTransaction transaction = null, int? commandTimeout = null, CommandType? commandType = null)
{
    var result = query.Build(settings);
    return cnn.QueryFirstAsync<T>(result.Sql, result.Bindings, transaction, commandTimeout, commandType);
}
```

**Comment by ahmad-moussawi** [comment]
Hi, I really believe that letting the query to manage the execution by itself is more easier than using an external class to manage this

```cs
var users = factory.Create("Users").Get();
```
instead of 

```cs
var query = new Query("Users");
var users = connection.Query(query);
```

since in the latest the developer should always care about the connection, while the goal of SqlKata is to take the developer away as much as possible from dealing with low level API, thus it's not coupled with Dapper's API.

We tend for the approach to configure once and use everywhere, for example DI containers, factory patterns and so on.

For the casting exception, I agree with you, but currently this is the only way, I think clear documentation can solve this issue.
