### ISSUE TITLE
Multiple Or condition

### ISSUE THREAD

**Issue by godshades** [sqlkata/querybuilder#452]
Hi, can someone give me example for this sql

where ((A = 0 AND B =0) OR (C=0 AND D=0))

**Comment by ahmad-moussawi** [comment]
Checkout the Nested conditions https://sqlkata.com/docs/where#nested-conditions-and-grouping
```cs
var query = new Query("Posts").Where(q =>
    q.Where("A", 0).Where("B", 0)
).OrWhere(q =>
    q.Where("C", 0).Where("D", 0)
)
```
or check it live on the playground https://sqlkata.com/playground?code=var%20query%20%3D%20new%20Query(%22Posts%22).Where(q%20%3D%3E%0A%20%20%20%20q.Where(%22A%22%2C%200).Where(%22B%22%2C%200)%0A).OrWhere(q%20%3D%3E%0A%20%20%20%20q.Where(%22C%22%2C%200).Where(%22D%22%2C%200)%0A

**Comment by godshades** [comment]
thank you so much
