### ISSUE TITLE
'last_insert_rowid' is not a recognized built-in function name.

### ISSUE THREAD

**Issue by lesair** [sqlkata/querybuilder#455]
When trying to use the InsertGetIdAsync method with an Azure SQL Database, this exception is thrown:

'last_insert_rowid' is not a recognized built-in function name.

It appears that the Azure SQL Database does not have built-in the 'last_insert_rowid' function.

**Comment by ahmad-moussawi** [comment]
You are using the wrong compiler (MySql) I think the SqlServerCompiler is the correct one in this case.

**Comment by lesair** [comment]
@ahmad-moussawi You're right, my bad. Cancelling this issue now.

**Comment by lesair** [comment]
Not a bug.
