### ISSUE TITLE
ColumnAttribute is not mapping columns to strong type property.

### ISSUE THREAD

**Issue by lesair** [sqlkata/querybuilder#457]
I have my POCO strong type defined like this:

```
public class Fruit
{
  [Key("Fruit_Id")] [Ignore] public string FruitId { get; set; }
  [Column("Full_Name")] public string FullName { get; set; }
}

```
But the column names mappings are not working when fetching rows:
`IEnumerable<Fruit> fruits = db.Query("Fruit").Get<Fruit>();`

I get the rows but the class properties whose names differ from the table columns are not filled, if I rename my class properties names then the mapping is done correctly, so apparently the ColumnAttribute I am using is useless.

Regards.

**Comment by zerofairnight** [comment]
This library uses Dapper under the hood, and Dapper does not support attribute mapping.

For your specific use case, try with:
```cs
Dapper.DefaultTypeMap.MatchNamesWithUnderscores = true;
```

The column attribute you referring is used for inserting and updating only.

**Comment by lesair** [comment]
Thank you @zerofairnight
