### ISSUE TITLE
Include And Define Extension Methods Not Working

### ISSUE THREAD

**Issue by aboah** [sqlkata/querybuilder#460]
var users = r.Query("Project").Include("Contributors", q => q.From("Contributors"));

Running this query in my project generates the below error:
Error	CS1061	**'Query' does not contain a definition for 'Include' and no accessible extension method 'Include'**

**The Same Error is generated when one applies the Define Extension method**

var query1 = new Query("Products")
                .Select("ProductId")
                .Define("@product", "Coffee")
                .WhereEnds("ProductName", Variable("@product"));

Please what can I do to get these extension methods working

**Comment by ahmad-moussawi** [comment]
@aboah could you please report what version are you using?
the Define method is listed in the main Query class so no extensions import needed
https://github.com/sqlkata/querybuilder/blob/master/QueryBuilder/Query.cs#L325

**Comment by ahmad-moussawi** [comment]
Closing due to no response
