### ISSUE TITLE
Question: Can I use SqlKata.Execution AND Dapper ?

### ISSUE THREAD

**Issue by m4ss1m0g** [sqlkata/querybuilder#464]
Can I use SqlKata.Execution AND Dapper?

I have some code that already using Dapper, can I mix in the same assembly Dapper and SqlKata.Execution? 
In this case which version uses SqlKata.Execution, the pre-installed with SqlKata.Execution or mine?

**Comment by ahmad-moussawi** [comment]
AFAK, you can't install, directly or through library dependency, different versions of Dapper (or any other library), so if you want to use Dapper directly you have to install the same version installed with SqlKata.Execution package
