### ISSUE TITLE
[Bug] nested t-sql selects with limit do not compile / resolve correctly.

### ISSUE THREAD

**Issue by generik0** [sqlkata/querybuilder#47]
Hi
Great app.
If i have a nested select with a limit for t-sql  the TOP 1 is resolving as " , ", not as TOP (1).

I will pull request the test as proof.,

**Comment by ahmad-moussawi** [comment]
Hi Thanks for the feedback, do you have a PR to fix it? otherwise I will look into it the soonest :)

**Comment by generik0** [comment]
I will try to find time...
We will see who has time first ;-)

**Comment by generik0** [comment]
Please look at pull request for bug/47.
Should be fixed now

**Comment by ahmad-moussawi** [comment]
@generik0, mm I always had the hidden fear of Enumerables, I have to review the whole compiler parts that use it, anyway thanks for the update, I will look into it and get back to you

**Comment by generik0** [comment]
I understand.
I use ICollection most places. Exactly because of the same.

I do use R# and this normally tells of there is an issue with the ienumerable.

But you had both a .any() and getting the collection = double run...

**Comment by generik0** [comment]
But you are goibg to accept the pull returer right? So i get the cobtributer label?

**Comment by ahmad-moussawi** [comment]
Yes off course, nice catch ! 👍
