### ISSUE TITLE
WITH(INDEX)

### ISSUE THREAD

**Issue by generik0** [sqlkata/querybuilder#478]
Hi, is it possble to select from tables with indexes (msql)

eg. 
`SELECT *  FROM [foobar-db] WITH(INDEX([NonClusteredIndex-20210510-211406]))`

I dont think the WithRar work like this

**Comment by ahmad-moussawi** [comment]
You have to use here the `FromRaw` here.

Check https://sqlkata.com/playground?code=var%20query%20%3D%20new%20Query().FromRaw(%22%5Bfoobar-db%5D%20WITH(INDEX(%5BNonClusteredIndex-20210510-211406%5D))%22)%0A%20%20%20%20

**Comment by generik0** [comment]
Hi.
Yea, thanks I found it.
One prob though, can't do it with the join though.
I can join with a query that has a fromraw, however this makes the join become an inner query.

So I guess we also need a JoinRaw

**Comment by ahmad-moussawi** [comment]
Yes you are right, JoinRaw is not available at this moment, #475
