### ISSUE TITLE
Release cycle

### ISSUE THREAD

**Issue by yankyhgoflow** [sqlkata/querybuilder#479]
I'm pleased that I was able to help out an solving issue #476, just wondering how your release cycle goes as in to when I can expect to see this fix in the nuget package.
Thanks

_Originally posted by @yankyhgoflow in https://github.com/sqlkata/querybuilder/issues/476#issuecomment-838415575_

**Comment by ahmad-moussawi** [comment]
Thank you for the contribution, currently there is no fixed release cycle, but mainly it's twice per year, Jan and June.
for the time being you can install the from the nightly build feed.
https://github.com/sqlkata/querybuilder/packages/671007

**Comment by yankyhgoflow** [comment]
Ahmad, the link you shared just points to the latest production release, do you have a pre-release package which I can use?

This is a bug currently affecting my code (I install SqlKata using Nuget) and I will really appreciate if I can use the package along with this new fix if possible.

**Comment by yankyhgoflow** [comment]
@ahmad-moussawi Thanks for the new release!

We updated our package references to fully enjoy the new code!

Thanks for this great project!
