### ISSUE TITLE
Wrong file version in 2.3.2 NuGet package

### ISSUE THREAD

**Issue by Sharparam** [sqlkata/querybuilder#484]
It seems the file version on SqlKata.dll is set incorrectly in the 2.3.2 release. The version on the file is 1.0.0 rather than 2.3.2.

This seems to cause issues when applications try to resolve version 2.3.2, instead resolving to the previous 2.2.0 release, which then leads to a `FileNotFoundException` because the system was unable to find 2.3.2 because of the mismatched file version on the DLL.

Screenshot of the "Details" page on the SqlKata.dll from the 2.3.2 NuGet package:
![image](https://user-images.githubusercontent.com/551094/119637144-a5c9f980-be15-11eb-8289-6ffd02cf338c.png)

Screenshot of the "Details" page on the SqlKata.dll from the 2.2.0 NuGet package (notice how the version is set correctly):
![image](https://user-images.githubusercontent.com/551094/119637238-be3a1400-be15-11eb-91a1-d4fd907db11b.png)

**Comment by Sharparam** [comment]
The file versions seems to be correct in the latest versions on NuGet now, closing this issue.

**Comment by ahmad-moussawi** [comment]
Thanks @Sharparam, it was an issue from the CI pipeline, I've pushed a fix, but didn't get the time to validate it, so thanks for confirming.
