### ISSUE TITLE
Atomic Increment?

### ISSUE THREAD

**Issue by adhip94** [sqlkata/querybuilder#488]
Anyone has tried atomic increment? For example is it possible to write the below query using SQLKata querybuilder:

```sql
update mytable
set readcount = readcount + 1 
where myid = '123456'
```

**Comment by ahmad-moussawi** [comment]
@adhip94 why you have closed this?

**Comment by adhip94** [comment]
I didnt get any reply from anyone, and it was urgent since 1 week had passed, hence after discussing with a colleague I got a solution that worked.

```c#
var query = new Query("mytable")
  .Where("myid", "123456")
  .AsUpdate(new {
    readcount = new UnsafeLiteral("readcount  + 1"),
  });
```

Also FYI, when I run the above query in the SQLKata Playgrounds page, I get this.
![image](https://user-images.githubusercontent.com/20703483/121235340-6211ce00-c8b2-11eb-86f0-9de60144985e.png)

**Comment by ahmad-moussawi** [comment]
This feature is now supported in 2.3.4 see #490 #489
