### ISSUE TITLE
IBM AS/400 DB2 Support?

### ISSUE THREAD

**Issue by Spuddish** [sqlkata/querybuilder#491]
Hello there,

Are there any plans to add a DB2 compiler? Or by any chance has anyone worked on an unofficial implementation?

Thanks,

- Patrick

**Comment by ahmad-moussawi** [comment]
Currently there is no plan to add support for DB2, or any other vendor, our focus is to clean the issues, and provide relevant features.
However we encourage the community to add new compilers in their own packages.
