### ISSUE TITLE
What is happening to all these releases!

### ISSUE THREAD

**Issue by chrisgate** [sqlkata/querybuilder#493]
What is happening to all these releases!

**Comment by ahmad-moussawi** [comment]
What do you mean?

**Comment by chrisgate** [comment]
Test release.........3.XX while we are in 2.XX.

What does test release mean?

Release Note??

**Comment by shaunsales** [comment]
There's an issue with the NuGet release version numbering of `SqlKata.Execution`;

```
3.2.3 | 1,155 | 19 days ago
2.3.7 | 484 | 8 days ago
```

It jumps from 2.3.7 to 3.2.3, and depends on `SqlKata` 3.2.3, which does not exist in NuGet.

**Comment by azhe403** [comment]
Execution required 3.2.3
![image](https://user-images.githubusercontent.com/17938038/122667567-9f912800-d1dd-11eb-8795-5c18aa7d9323.png)

And latest package is 2.3.7
![image](https://user-images.githubusercontent.com/17938038/122667515-69ec3f00-d1dd-11eb-9af4-7ed1276dbf58.png)

**Comment by ahmad-moussawi** [comment]
Yes the version 3.2.3 was released by mistake while we are testing the CI/CD pipeline, and I've requested to unlist it from NuGet.
However it can still be installed if referenced directly, I strongly recommend to ignore the version and not use it in your projects.
