### ISSUE TITLE
Breaking change introduced in v2.2.3

### ISSUE THREAD

**Issue by Sharparam** [sqlkata/querybuilder#500]
A breaking change in the signature of `Query.AsInsert` was introduced in version 2.2.3.

Signature that existed in v2.2.0:

https://github.com/sqlkata/querybuilder/blob/v2.2.0/QueryBuilder/Query.Insert.cs#L43

```csharp
public Query AsInsert(IReadOnlyDictionary<string, object> data, bool returnId = false)
```

How it looks in v2.2.3:

https://github.com/sqlkata/querybuilder/blob/v2.2.3/QueryBuilder/Query.Insert.cs#L43

```csharp
public Query AsInsert(IEnumerable<KeyValuePair<string, object>> values, bool returnId = false)
```

This causes a `MethodMissingException` when a library has built with v2.2.0 and then a downstream project pulls in that project but uses SqlKata v2.2.3 (or newer).

**Comment by ahmad-moussawi** [comment]
Oops, let me investigate this more
