### ISSUE TITLE
Boolean Conditions in Where Clause

### ISSUE THREAD

**Issue by adhip94** [sqlkata/querybuilder#503]
When using the Where clause like this:
```
var query = new Query("table").Select("*").Where("column", "=", true)
```
This gives an output as shown below for SQL Server
``` sql
SELECT
  *
FROM
  [table]
WHERE
  [column] = true
```

For SQL Server since boolean is not supported we need to use bit 0/1.

If I use `.WhereTrue("column")` it works fine.

Not sure if in above scenario it needs to be fixed?

**Comment by ahmad-moussawi** [comment]
#437 
#510
