### ISSUE TITLE
while having multiple selects, auto merge duplicate columns instead of repetition.

### ISSUE THREAD

**Issue by tijujohn83** [sqlkata/querybuilder#505]

**Comment by ahmad-moussawi** [comment]
As a general rule, we avoid manipulating implicitly the query when not necessary, since there maybe some cases where the user want to select the same column twice for some reason.
So I don't see this will help too much.
Thanks for the suggestion anyway :)

**Comment by tijujohn83** [comment]
duplicate columns without alias is an error in oracle.
