### ISSUE TITLE
`FILTER` clause in `SELECT` clause

### ISSUE THREAD

**Issue by yankyhgoflow** [sqlkata/querybuilder#507]
In SQL we can add a `FILTER` clause to an aggregate `SELECT` clause, i.e.

```sql
SELECT [item], SUM([price]) AS [total], SUM([price]) FILTER ( WHERE [date] >= '2021-01-01' ) AS [sales2020]
FROM [orders]
GROUP BY [item]
```

It would be a huge help if SqlKata can support passing `WHERE` clauses with their bindings to a `SELECT` clause.

**Comment by generik0** [comment]
WhereRaw? Can you not do it with that?

**Comment by yankyhgoflow** [comment]
`WhereRaw` works on the overall query level, I am referring to the `FILTER` clause available on aggregate expressions [postgres docs](https://www.postgresql.org/docs/10/sql-expressions.html#SYNTAX-AGGREGATES)

**Comment by ahmad-moussawi** [comment]
Support added will be available in the next release
