### ISSUE TITLE
Make WrapTable method in AbstractCompiler virtual

### ISSUE THREAD

**Issue by SaltyDH** [sqlkata/querybuilder#51]
I'd like to create a compiler subclass to deal with our table naming conventions. We have period (.) characters in some database table names. This gets incorrectly split.

I'd like to provide additional logic on how SqlKata splits the table names in this situation. If the WrapTable method is virtual, I can override and provide my additional logic. Alternatively, allowing escape characters in the split operations of Wrap() however that felt like a performance penalty for something that probably isn't common.

**Comment by SaltyDH** [comment]
Same thing happens with fields so making the WrapTable method virtual won't be enough. Making the underlying Wrap method virtual might be the better option.

**Comment by ahmad-moussawi** [comment]
Could you provide a pull request for this ?

**Comment by ahmad-moussawi** [comment]
Closing since not valid anymore
