### ISSUE TITLE
Join Many to Many Relationship

### ISSUE THREAD

**Issue by zahra6688** [sqlkata/querybuilder#511]
Hi @ahmad-moussawi, 
I'm currently using sqlkata for implementing a report builder. In some cases, I need to join tables with many to many relationships. I tried to join tables in the way like below but it throws exceptions:

```
var Chimneys = db.Query("Chimney as C")
                .Join("IndustrialUnit as U", "U.Id", "C.IndustrialUnitId")
                .LeftJoin("InspectionReport as P", "P.IndustrialUnitId", "U.Id")
                .Join("dbo.[InspectionReport-EnvironmentalComplaint]", "P.Id", "InspectionReportId")
                .Join("EnvironmentalComplaint as E", "E.Id", "EnvironmentalComplaintId")
                .Select("U.Code as UCode", "C.Code as CCode") 
```
dbo.[InspectionReport-EnvironmentalComplaint] is the intermediate table between "InspectionReport" and "EnvironmentalComplaint". how could this type of join be handled?

**Comment by ahmad-moussawi** [comment]
@zahra6688 what is the exception you are getting?

Another note, no need to wrap this table `[InspectionReport-EnvironmentalComplaint]` with `[]`
check https://sqlkata.com/playground?code=var%20query%20%3D%20new%20Query(%22Chimney%20as%20C%22).Join(%22dbo.InspectionReport-EnvironmentalComplaint%22%2C%20%22P.Id%22%2C%20%22InspectionReportId%22)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20

**Comment by zahra6688** [comment]
thank you, that was my fault. I passed the name of the table incorrectly. 
I have another question. the query result is IEnumerable of Dynamic, and I need to export the result to excel. So it sounds difficult to export data to excel in this way. is there any other way instead of getting results in IEnumerable type?

**Comment by ahmad-moussawi** [comment]
There is no direct export to excel, but you can easily achieve this by enumerating the result,
I will close this ticket for now, if you face any issue feel free to open a new one.
