### ISSUE TITLE
Need help to build sqlkata query without using "SelectRaw" and "WhereRaw" functions

### ISSUE THREAD

**Issue by xayaraj** [sqlkata/querybuilder#514]
Need help to build sqlkata query without using "SelectRaw" and "WhereRaw" functions for the sql script below. The difficulty that I found is to not using sql "Date_Add" function. I am somewhat new to sqlkata library. My goal is to master this sql builder framework. Need some guidance. Thanks.

select ShipCountry, avg(Freight) as AverageFreight from northwind.orders
where OrderDate >= Date_Add((select max(orderdate) from northwind.orders), interval -12 month)
group by ShipCountry order by AverageFreight desc limit 3;

**Comment by fairking** [comment]
Long time ago I had the same question: https://github.com/sqlkata/querybuilder/issues/359
I had to write all of those helpers by myself.

**Comment by xayaraj** [comment]
Wow. This should be a good starting point for me. Thank you for your help. Appreciate that.
