### ISSUE TITLE
Realise it is on the roadmap but executing stored procedures would really make this a useful library....

### ISSUE THREAD

**Issue by natiki** [sqlkata/querybuilder#52]
Hi,

Looks like a great library. But it needs stored procedure support.

**Comment by ahmad-moussawi** [comment]
Hi, do you have any suggestion on what needed exactly ?

**Comment by natiki** [comment]
Hi @ahmad-moussawi,

 - Support for both SP's that don't return results, do return results, return multiple datasets as part of their results
- Ability to easily compose a stored proc call which mainly comprises adding parameters and values so something like:

```c#
var fastCarsStoredProc = new StoredProc("usp_FastCars")
    .Param("Param1", 120)
    .Param("Param2", 120, dirOut)   //Enum for directionality of params
```

Perhaps taking some insights from https://github.com/StackExchange/Dapper#stored-procedures

**Comment by ahmad-moussawi** [comment]
Now you can execute stored procedure using the `QueryFactory.Statement` method

```cs
db.Statement("exec procname param1");
```

**Comment by natiki** [comment]
@ahmad-moussawi Ummmm that will work, but is basic string replace ;-). So you are planning to add proper support for Stored Procs?

**Comment by ahmad-moussawi** [comment]
@natiki, sorry my experience with Stored Procedure is limited, can you lists the features that you want to be added ? if yes do you a PR for them ?

**Comment by natiki** [comment]
@ahmad-moussawi see https://github.com/sqlkata/querybuilder/issues/52#issuecomment-365190820 and my suggestion to use the Dapper approach for the API.

**Comment by natiki** [comment]
@ahmad-moussawi This really needs to be added back as a feature..... Being able to execute stored procedures, functions is a must have to make this library useful ;-)

**Comment by ahmad-moussawi** [comment]
@natiki, thanks for your feedback, but currently it's not on the priority list, I will keep it in the BackLog for now

**Comment by natiki** [comment]
How is it on the backlog when this case is closed? :-)

**Comment by chadkuehn** [comment]
Listed in the [docs](https://sqlkata.com/docs/execution/fetching-records#execute-raw-statements) now.
