### ISSUE TITLE
Visual Studio nuget: Licence HTTP 404 Not found

### ISSUE THREAD

**Issue by strarsis** [sqlkata/querybuilder#521]
When trying to open the license in Visual Studio (nuget), the URL [`https://github.com/sqlkata/querybuilder/licence`](https://github.com/sqlkata/querybuilder/licence) is opened in browser, for which nothing is found (HTTP 404).

**Comment by JordanMarr** [comment]
https://github.com/sqlkata/querybuilder/blob/master/LICENSE

**Comment by ahmad-moussawi** [comment]
Thanks for reporting, we now use the MIT expression instead.
