### ISSUE TITLE
WhereRaw is not really raw?

### ISSUE THREAD

**Issue by spiralw** [sqlkata/querybuilder#528]
I have the following SQL (postgres) query in Dapper:
```cs
await conn.QueryAsync(
    "delete from group_members where id = any(@Groups)",
    new { Groups = groups.Select(g => g.Id).ToArray() });
```
in SqlKata I tried to write it like this:
```cs
var query = new Query("group_members").AsDelete()
    .WhereRaw($"group_id = any(?)", groups.Select(g => Id).ToArray()));
```
but this generates invalid SQL: `DELETE FROM "group_members" WHERE group_id = any($1,$2)`. (I am not sure why it doesn't support arrays when Dapper does, but that is not the point of this issue).

I tried rewriting the SqlKata query like this:
```cs
var query = new Query("group_members").AsDelete()
    .WhereRaw($"group_id = any(array[?])", groups.Select(g => Id).ToArray()));
```
This generates a different invalid query: `DELETE FROM "group_members" WHERE group_id = any(array"@p0,@p1")`

I don't understand why this happens. Why is `[square brackets]` being changed to `"quotation marks"`? The documentation seems to say square brackets is column syntax in SQL Server, so I tried adding a `ForPostgreSql` to specify the SQL dialect i'm writing in, but that didn't change the result.

**Comment by ahmad-moussawi** [comment]
Hi, related to #407

**Comment by spiralw** [comment]
oh, I see. thank you
