### ISSUE TITLE
Question about converting Offset to accept long instead of int

### ISSUE THREAD

**Issue by atdimitrov** [sqlkata/querybuilder#532]
Hello.

I have a use case where I have to generate select query with offset bigger that `int.MaxValue`. As said in https://github.com/sqlkata/querybuilder/issues/298 `int` is sufficient for almost all cases, but not all. While I mostly agree with that statement for `Limit`, because it is rather rare for someone to attempt to read over 2 billion rows at once, the case is rather different when it comes to `Offset`.

Apart from the slightly higher memory usage, I don't see any disadvantages to making this API take `long` instead of `int`. Of course I'm don't have domain knowledge about the library, so I may be missing something. Do you, guys, see anything that would make such a change unfeasable or undesirable?

**Comment by ahmad-moussawi** [comment]
Feature add #608 thanks for your feedback, will be available in the next major release due to breaking change
