### ISSUE TITLE
How can we use T_HAZIRMETIN table name and column name in QueryBuilder. without using nameof.

### ISSUE THREAD

**Issue by mummyildiz** [sqlkata/querybuilder#533]
public class T_HAZIRMETIN
	{
		public string TID { get; set; }
		public string TANAHTAR { get; set; }	
	}  

************************************************

                var q = db.Query(nameof(DbTables.Entities.T_HAZIRMETIN))
                             .Where(nameof(DbTables.Entities.T_HAZIRMETIN.TID), ">", 0)
                             .WhereIn(nameof(DbTables.Entities.T_HAZIRMETIN.TID), new[] { 1, 2 })
                             .OrderByDesc(nameof(DbTables.Entities.T_HAZIRMETIN.TID))
                            .Select(nameof(DbTables.Entities.T_HAZIRMETIN.TID), nameof(DbTables.Entities.T_HAZIRMETIN.TANAHTAR));

                var data =q.GetAsync<DbTables.Entities.T_HAZIRMETIN>();
                dgData.DataSource = data.Result.ToList();

How can we use T_HAZIRMETIN table name and column name in QueryBuilder.
without using nameof.

**Comment by ahmad-moussawi** [comment]
@mummyildiz sorry but didn't get the issue here, I think Stackoverflow is better for such questions.
I will close this now, feel free to comment for further details.
