### ISSUE TITLE
Plans for commands?

### ISSUE THREAD

**Issue by jerry1970** [sqlkata/querybuilder#538]
With both the SQL Server and PortsgreSQL engines in a project, using SqlKata is great, because it means only building a query once and compiling it to whichever DB engine is being used.

But besides the queries, we're creating (mostly temporary) tables and commands like `truncate`. With the current version we still need to build two queries.

Are there any plans to include those in SqlKata as well?
Or additional packages that do this, or a fork? (GOing through 362 forked projects is taking a while.)

Thanks!

**Comment by ahmad-moussawi** [comment]
@jerry1970 no actually there is no plan for that, but maybe you can create Extension methods for your use cases,
Don't know about other forks, but if you find something interesting share it here for max benefit.
I will close this one, feel free to reopen, or discuss this further here.
