### ISSUE TITLE
ERROR when fire twice SqlServerCompiler().Compile(query)

### ISSUE THREAD

**Issue by JordiPerello** [sqlkata/querybuilder#54]
When I try to convert my Paginated **Query** object to string

In this case, if my object **Query** contains **SKIP** or **OFFSET**   and   **TAKE** or **LIMIT**
```
var query = new Query()
				.Select("Id", "Name")
				.From("MyTable")
				.OrderBy("Name")
				.Limit(20)
				.Offset(1);
```

When I try convert to string
`SqlServerCompiler compiler = new SqlServerCompiler();
string myQuery = compiler.Compile(query).ToString();`

When I invoke a **compiler(Query)** the first time, the result is
`SELECT TOP (20) [Id], [Name] FROM [MyTable] ORDER BY [Name]`
**IT'S OK**

And if I need Invoke for second time the same Query, the result is
`SELECT , [Id], [Name] FROM [MyTable] ORDER BY [Name]`
**IT'S WRONG** The **TOP (20)** are missing and put a comma at this place

**Comment by ahmad-moussawi** [comment]
Thanks for reporting this, currently the SqlServer update the current query in order to perform the outer query for the pagination, for the moment you can clone your query before compiling it

```cs
var sql = compiler.Compile(query.Clone()).ToString();
```

**Comment by JordiPerello** [comment]
Is what I do now, I'll wait for a version to come out solving this, just to have a cleaner code

Thanks in advance

Saludos,

Jordi Perelló Martínez


________________________________
De: Ahmad Moussawi <notifications@github.com>
Enviado: lunes, 19 de febrero de 2018 15:45
Para: sqlkata/querybuilder
Cc: JordiPerello; Author
Asunto: Re: [sqlkata/querybuilder] ERROR when fire twice SqlServerCompiler().Compile(query) (#54)


Thanks for reporting this, currently the SqlServer update the current query in order to perform the outer query for the pagination, for the moment you can clone your query before compiling it

var sql = compiler.Compile(query.Clone()).ToString();

**Comment by ceastwood** [comment]
@JordiPerello 

This was fixed somewhere that I had trouble tracking down. Added a quick unit test and is passing. PR #58 
Also just sent v1.0.0-beta-450 to myget.

**Comment by ceastwood** [comment]
Well, it supposedly deployed but I don't see 450 on nuget yet
