### ISSUE TITLE
WhereContains and friends for PostgresSQL are suboptimal

### ISSUE THREAD

**Issue by mindcrash** [sqlkata/querybuilder#540]
Currently the following SQL is generated

```sql
LOWER(column) LIKE '%value%'
```

However, this is causing enormous performance issues in PostgreSQL on larger number of rows, even when a GIN or GIST index is applied.

A more performant way to generate this condition would be:

```sql
column ILIKE '%value%'
```

**Comment by ahmad-moussawi** [comment]
Could you push a PR for it?

**Comment by ahmad-moussawi** [comment]
PR merged, thanks for reporting
https://github.com/sqlkata/querybuilder/pull/544
