### ISSUE TITLE
SQL Server Legacy Pagination enabled by default

### ISSUE THREAD

**Issue by Wulfheart** [sqlkata/querybuilder#545]
Hello,

the docs state the following:

![image](https://user-images.githubusercontent.com/25671390/145680567-e6938068-0659-4728-818a-9481a3fa410d.png)

However, in [SqlServerCompiler.cs]( https://github.com/sqlkata/querybuilder/blob/87b4947c40fb45d53dff9fc41d7d14219e31ac96/QueryBuilder/Compilers/SqlServerCompiler.cs#L15) `public bool UseLegacyPagination` is set to true by default. Per the docs this should not happen. I am going to address this in a PR.

Best,
Alex

**Comment by ahmad-moussawi** [comment]
PR merged, thanks
