### ISSUE TITLE
Arithmetic overflow error converting numeric to data type numeric

### ISSUE THREAD

**Issue by gunagururaja** [sqlkata/querybuilder#550]
SqlException (0x80131904): Arithmetic overflow error converting numeric to data type numeric.

Code: 

**Issue : TotalExperience is a Numeric(3,2) field. please help.**

 using (TransactionScope scope = new TransactionScope())
            {
                int affected = db.Query("Candidate").Insert(

                    new
                    {
                        
                     
                        TotalExperience = model.TotalExperience
                   
                    }

                    );

                scope.Complete();
            }

**Comment by ahmad-moussawi** [comment]
I don't think this is related to Sqlkata, most probably you are passing a number greater than the field size
