### ISSUE TITLE
QueryFactory IDisposable?

### ISSUE THREAD

**Issue by generik0** [sqlkata/querybuilder#551]
Memory/ dbconnection leak when using QueryFactory. Why is QueryFactory disposable when passing the bConnection, I
understand if the passing the connection string, but when passing the connection, the owner of the connection should be responsible for passing it, no?

On the document i see an example:

https://sqlkata.com/docs/execution/fetching-records

var db = new QueryFactory(connection, new SqlServerCompiler());

Are we sure the current implementation is correct? Or should the documentation be corrected?
I made a PR to add using statements to the doco.
Don't know what to do about the query factory

**Comment by rsr-maersk** [comment]
HI @ahmad-moussawi , are you sure SqlKata.Execution.QueryExtensions isn't giving a memory leak, you are newing the QueryFactory on each call, never disposing.. But QueryFactory is IDisposable, I think you should be disposing the CreateQueryFactory otherwise you will the conection leaks lie we did...

**Comment by ahmad-moussawi** [comment]
@generik0 talking in this manner is not acceptable,
If you have a comment or feedback, you have one of two options:
 - Ask politely and provide valuable feedback, or
 - Help and contribute with a solution
 other than that I am obliged to ignore your requests

**Comment by generik0** [comment]
Sorry, I don't agree I was being rude. I added no adjectives or anything. I made a simple statement.
But I will edit to comply..

**Comment by generik0** [comment]
Please note @ahmad-moussawi 

The question about the memory leak above is on the extensions is very relevant. 
What is disposing the QueryFactory? It is IDisposable. Will the GC dispose it?

It didn't for us, when we needed it, but here we kept it in a field until the scope was over.

I know the example with the DI regression will dispose it.

**Comment by ahmad-moussawi** [comment]
@generik0 do you have a reproducible scenario, so it help point out the issue easily?

**Comment by generik0** [comment]
Yes. I will add some integration tests you your sln (fork). What project would you like me to call it?
Sql.Kata.IntegrationTests?
