### ISSUE TITLE
SqlKata.Execution problem on nvarchar or unicode characters on update and insert

### ISSUE THREAD

**Issue by mojtaba-yekta** [sqlkata/querybuilder#560]
Hi,
I used this code to update a Unicode (nvarchar) field in the database. but instead of Unicode characters, it saves the question mark (like this: ????? ????) into the database.

public void updateUser(int userId,string unicodeName){
	var q = DbQueryFactory.Query("Users").Where("Id", userId)
			.AsUpdate(new
			{
				Fullname = unicodeName,
				LastModifiedBy = userId,
				LastUpdate = DateTime.Now,
			});
			
	var compiler = new SqlServerCompiler();
	string queryStr = compiler.Compile(q).ToString();
	return DbQueryFactory.Statement(queryStr);
}

**Comment by ahmad-moussawi** [comment]
Hi @mojtaba-yekta, you should not use the result of `ToString()` directly to execute your query.
You should use the `SqlResult.Sql` instead, and pass the binding, 
or use the `db.Query("Table").Insert({...})` syntax
