### ISSUE TITLE
Allow using shorthand notiations in the Query function when defining names of tables

### ISSUE THREAD

**Issue by absundr** [sqlkata/querybuilder#568]
## Problem area

`Query("TableName")` does not accept shorthand notations to reference the table. This can be painful when you have a lot many columns and you're performing a join with another table which clashing columns.

In this scenario, you are required to prefix the entire TableName to the column, likes so 

`Query("TableName").Select("TableName.Column")`

You can see how this would be painful in writing columns in the hundreds. 

## Suggested fix

Allow the Query object to accept a shorthand accessor for the table name which can be used to prefix the required columns.

Like so,

`Query("TableName tb).Select("tb.Column")`

This will make things so much easier.

**Comment by ahmad-moussawi** [comment]
You can do it by writing 
```cs
var query = new Query("TableName as tb").Select("tb.Column")
```
check [this example](https://sqlkata.com/playground?code=var%20query%20%3D%20new%20Query(%22TableName%20as%20tb%22).Select(%22tb.Column%22)%3B)

in addition you can expand the selection to avoid repeating the table name many time

```cs
var query = new Query("TableName as tb").Select("tb.{ColumnA, ColumnB, ColumnC}");
```
This will output the following SQL

```sql
SELECT [tb].[ColumnA], [tb].[ColumnB], [tb].[ColumnC] FROM [TableName] AS [tb]
```

**Comment by absundr** [comment]
I wasn't aware this could be done. It's super helpful. I'm wondering why it doesn't say anywhere in the documentation.

Thanks btw

**Comment by ahmad-moussawi** [comment]
Yes the docs is outdated now.
