### ISSUE TITLE
Release plans?

### ISSUE THREAD

**Issue by mnsrulz** [sqlkata/querybuilder#576]
Not an issue, but wondering what's the plan for releasing the enhancements included so far in the main branch? I saw you mentioned #479 that it's twice a year.. is it?

**Comment by viveks7** [comment]
+1 on this. The library hasn't been updated this year & both of the mentioned release windows are over. We could find some issues which are in merged status but due to absence of release not being able to use the fixes @ahmad-moussawi

**Comment by bsivanov** [comment]
I just came here to evaluate the project. More than one year without a release seems concerning, not that it means that there are problems with the project for sure.

**Comment by biju-ps** [comment]
+1 
I am using Pg , releasing #544 will very much useful

**Comment by mnsrulz** [comment]
@ahmad-moussawi any inputs on this?

**Comment by ahmad-moussawi** [comment]
We've shipped the latest release now v.2.3.9, and we've added the releases log to the website.
check https://sqlkata.com/release/v2.3.8
and https://sqlkata.com/release/v2.3.9

I think we can close this now, but feel free to reopen if something is missing.
Thanks all for your input and feedback here.
