### ISSUE TITLE
System.Data.SqlClient.SqlException: 'Incorrect syntax near '`'.'

### ISSUE THREAD

**Issue by talley** [sqlkata/querybuilder#578]
public List<Users2> GetUsers()
        {
             SqlConnection sqlcon = new SqlConnection(CONN_STR);
             var compiler = new MySqlCompiler();
            var db = new QueryFactory(sqlcon, compiler);

            var users = db.Query("Users2").Get<Users2>(); //error occurred here

            return users.ToList();
        }

**Comment by digitaldirk** [comment]
I believe you need to change your compiler type depending on what you are using. In my case I changed **MySqlCompiler** to **SqlServerCompiler**.

```public List<Users2> GetUsers()
    {
         SqlConnection sqlcon = new SqlConnection(CONN_STR);
         var compiler = new SqlServerCompiler();
         var db = new QueryFactory(sqlcon, compiler);
         var users = db.Query("Users2").Get<Users2>(); //error occurred here
        return users.ToList();
    }
```

**Comment by ahmad-moussawi** [comment]
as per @digitaldirk your connection and compiler should match, 
you are using SqlConnection (for SqlServer) and using MySqlCompiler (for MySql)

SqlConnection -> SqlServerCompiler
MySqlConnection -> MySqlCompiler

**Comment by talley** [comment]
Thank you. I don`t know how i missed this.
