### ISSUE TITLE
Query.Not() doesn't apply to WhereRaw

### ISSUE THREAD

**Issue by SunnyC17** [sqlkata/querybuilder#598]
When I am using Not(), the WhereRaw clause is not negated. I have to use WhereRaw instead of Where in my use case so would there be a fix to this issue? Suggestions for work-around will also be appreciated. 
``` 
var query = new Query("Posts").Not();
query = query.WhereRaw("lower(Title) = ?", "sql");
```
returns 
```
SELECT
  *
FROM
  [Posts]
WHERE
  lower(Title) = 'sql'
```

**Comment by ahmad-moussawi** [comment]
Yes this intended, and should be mentioned in the doc, why not negating directly your expression?
as a workaround you can nest your condition with
```
`WhereNot(q => q.WhereRaw("A = B"))
```

check https://sqlkata.com/playground?code=%2F%2F%20a%20variable%20with%20the%20name%20'query'%20and%20of%20type%20'Query'%20should%20be%20exposed%0Avar%20query%20%3D%20new%20Query(%22Users%22)%0A%20%20%20%20.Where(%22Name%22%2C%20%22John%22)%0A%20%20%20%20.WhereNot(q%20%3D%3E%20q.WhereRaw(%22A%20%3D%20B%22

**Comment by SunnyC17** [comment]
Thanks for the workaround, the issue at my end has been resolved.
