### ISSUE TITLE
Chunk throws exception on second page

### ISSUE THREAD

**Issue by rocksthehouse** [sqlkata/querybuilder#61]
I am using 1.0.0-beta-458 and with the following simple code I get an exception when it tries to return the second page of results:

```
var query = new Query("dbo.MyTable");

var db = new QueryFactory(connection, new SqlServerCompiler());

db.Query(query).Chunk(2, (rows, page) =>
{
});
```

It appears to be down to the code which adds the fake raw SQL clause (there is a comment about this in the code) which works for the first page as it includes a TOP clause. However, the second page query doesn't include this and so the generated SQL is invalid (there is a comma before the * in the second select):

`SELECT * FROM (SELECT , *, ROW_NUMBER() OVER (ORDER BY (SELECT 0)) AS [row_num] FROM [dbo].[MyTable]) AS [subquery] WHERE [row_num] BETWEEN @p0 AND @p1`

**Comment by rocksthehouse** [comment]
In SqlServerCompiler if I add an else block to the `if (limitOffset != null && limitOffset.HasLimit() && !limitOffset.HasOffset()) {}` block and remove the clause at index 0 if the clause component was the fake one that was added previously then it fixes it for me.

But I'm not sure what the correct logic is to determine whether it is safe to remove it. Just removing it in the else if the clause is a RawColumn with component = "select", Expression="" and Binding with limit in it probably not selective enough.

**Comment by ahmad-moussawi** [comment]
Thanks for reporting it's similar to #54, the latest nuget package address a fix for this issue,
SqlKata.1.0.0-beta-459 (on myget)
