### ISSUE TITLE
SqlKata generating query with unfulfilled parameters

### ISSUE THREAD

**Issue by TeamGameRevolution** [sqlkata/querybuilder#62]
I have the following `Dictionary<string, object>` called datensaetze:

Key | Value
----|------
categoryID | 5
customergroupID | 1

Compiling this into a query:

```
                    var query = new Query(quelle.Tabelle).AsInsert(datensaetze);
                    var compiler = new MySqlCompiler();
                    var qStr = compiler.Compile(query).Sql;
```

results in the following query:

```
INSERT INTO `s_categories_avoid_customergroups` (`categoryID`, `customergroupID`) VALUES (@p0, @p1)
```

which is not executable. I can't use the QueryFactory, because I need the SQL string logged in a log file and possibly edited (see #60 )

**Comment by TeamGameRevolution** [comment]
I just saw, that the RawSql parameter contains `INSERT INTO `s_categories_avoid_customergroups` (`categoryID`, `customergroupID`) VALUES (?, ?)`, though I'm still confused as to why, since I'm passing the dictionary, expecting the wildcards to be replaced with the actual values I set.

**Comment by ahmad-moussawi** [comment]
This what is called parameters bindings, which is recommended to execute queries, for debugging purposes you can use the `compiler.Compile(query).ToString()`

Check https://stackoverflow.com/a/4712113/1104402 for more info

**Comment by ahmad-moussawi** [comment]
thanks for your suggestion, but including the values directly in the generated sql open the door for unsecure/un-efficient code, this is why I am against this approach
