### ISSUE TITLE
How can I generic `where column>1+column1`?

### ISSUE THREAD

**Issue by Cricle** [sqlkata/querybuilder#636]
I try to use `Where` but only can simple unary expression.

**Comment by kenzouno1** [comment]
With `expression` you need use `Raw` method (WhereRaw,HavingRaw,OrderByRaw....)

**Comment by ahmad-moussawi** [comment]
as @kenzouno1 said, using `.WhereRaw()` is the best in this case.
Do this answer your question?

**Comment by Cricle** [comment]
Thanks.
