### ISSUE TITLE
Result of the query with multiple carriage return line feed  is truncated

### ISSUE THREAD

**Issue by Alex-Doms** [sqlkata/querybuilder#642]
Hello, i'm having this issue with SQLKATA with Orcale :
In my database, i have this kind of column --> Varchar2(4000)
with data like this 
"TEST[CR][LF]TEST1[CR][LF]TEST2"

But in my query result, from a select instruction, i have this : 
"TEST[CR][LF]"

So my data seems to be truncate, but i don't see where i can change this.
Is it in the complier ? 
Thanks for your help!

**Comment by Alex-Doms** [comment]
Hi Ahmad, Thanks for your help here my sample code : 
```
QueryResult result = new QueryResult();
query = select.GetQuery();
SqlResult sqlResult = QFContexte.Compiler.Compile(query);
IEnumerable<dynamic> v = QFContexte.FromQuery(query).Get(Transaction);
```

**Comment by ahmad-moussawi** [comment]
From the given code, it's not clear to me, what part is causing this issue, but I suggest running a raw string SQL with dapper, and see if the issue persist
