### ISSUE TITLE
Documentation on Writing a Compiler

### ISSUE THREAD

**Issue by lawrence-vo** [sqlkata/querybuilder#648]
Is there any documentation or guides on how to write a compiler?

I would like to use SqlKata to generate queries for Snowflake. I've noticed that there is an implementation in this [repo](https://github.com/UiPath/querybuilder), but it is not up to date with this main branch.

**Comment by ahmad-moussawi** [comment]
You can check the existing compilers; I'd recommend starting with the `SQliteCompiler`.

In short, you have to override the base `Compiler` class and use it.
