### ISSUE TITLE
Value Expressions

### ISSUE THREAD

**Issue by davisylvestre** [sqlkata/querybuilder#670]
I would like to know if it is possible to build the queries below.
I left an example in SQL Server and another in SQLite.
I'm not familiar with the other database drivers.
The records would come from a list `List<T>`

_PS: sorry for any English mistakes, it's not my native language_

**SQLite**
```sql
WITH emp_master (emp_id, first_name, last_name, salary) AS(
  VALUES (1,"Honey","Patel",10100),
         (2,"Shweta","Jariwala", 19300),
         (3,"Vinay","Jariwala", 35100)
)
SELECT *
  FROM emp_master;
```

**SQL Server**
```sql
SELECT *
  FROM (VALUES (1,"Honey","Patel",10100),
               (2,"Shweta","Jariwala", 19300),
               (3,"Vinay","Jariwala", 35100)) emp_master (emp_id, first_name, last_name, salary);
```

**Comment by ahmad-moussawi** [comment]
I think you are looking for https://sqlkata.com/release/v2.3.8#ad-hoc-inline-table
