### ISSUE TITLE
--Oracle11g does not support, "OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY "

### ISSUE THREAD

**Issue by mummyildiz** [sqlkata/querybuilder#672]
SELECT t.* FROM personel  t
WHERE t.t_sicilno is not null
ORDER BY (SELECT 0 FROM DUAL) 

--Oracle11g does not support
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY 

can we change it for oracle version?

**Comment by ahmad-moussawi** [comment]
You are looking for `UseLegacyPagination`.

```
var oracleCompiler = new OracleCompiler { UseLegacyPagination = true };
```
