### ISSUE TITLE
PERF: PaginateAsync uses Count(*) to count number of rows

### ISSUE THREAD

**Issue by binoypatel** [sqlkata/querybuilder#682]
Hi there,

Thanks for your great work. I am new to this library and using it first time in my project. I found that when I am using the following code:
`var result = await _db.Query("Customers")`
`            .OrderBy("Id")`
`            .Select("Id", "Name", "Tag")`
`            .PaginateAsync(`
`                1,`
`                10`
`            )`
`            .ConfigureAwait(false);`

In the log, I can see that it uses 
`SELECT COUNT(*) AS [count] FROM [Customers]`

Would it be possible to change to COUNT(1) instead of COUNT(*)?

Kind regards,
Binoy

**Comment by nielslucas** [comment]
Why would you need this? I did a 1 minute research (sorry, to lazy to do more) and found this:

https://stackoverflow.com/questions/1221559/count-vs-count1-sql-server

The answere: _There is no difference._ 

For the record, not trying to attack you, just curious for the 'why'. Its always a good practise to supply a 'why' to a feature request.

**Comment by binoypatel** [comment]
Yes, you are right, both are the same and not require any change. Thanks for your quick findings.



________________________________
