### ISSUE TITLE
Release a netstandard compatible version

### ISSUE THREAD

**Issue by jonjomckay** [sqlkata/querybuilder#7]
We'd like to use this library in a `netstandard1.3` project, but the latest version on Nuget only supports `netcoreapp1.0`. Would it be possible to release another beta version with the `netstandard` support in the master branch?

**Comment by ahmad-moussawi** [comment]
@jonjomckay, sure a new version will be released soon, to support `netstandard1.3` and `netstandard2.0`

**Comment by ahmad-moussawi** [comment]
The latest [release](https://www.nuget.org/packages/SqlKata) now supports `netstandard1.3`, so I will close for now, please reopen if you have any other concerns

**Comment by jonjomckay** [comment]
Awesome, thanks @ahmad-moussawi!
