### ISSUE TITLE
Support DDL Queries 

### ISSUE THREAD

**Issue by jeffrey-igaw** [sqlkata/querybuilder#77]
Hi, i think this is really i want, about building flexible query.

But could you provide ddl query interface in future or can i contribute for that?

Below example is maybe expected that is my want to use ;)
```csharp
var createTableQuery = new Query(connection)
   .CreateTable("table_name")
   .WithField("id", Field.long)
   .WithField("field_name", Field.Int)
   .WithField("field_name_2", Field.Varchar, 100)
   .WithForeignKey("fk_id", "target_table", Field.Int)
   .WithPkConstant("id" /* or with multiple columns" */);
````

thanks for your work!

**Comment by ahmad-moussawi** [comment]
Thanks Jeff, currently there is no near plan to support this, since my priorities are to release a stable version soon, then supporting Sqlite, SqlServer 2012+ and Oracle Compilers,
Off course your contribution is welcomed, we may discuss the api a bit if you decided that 👍

**Comment by ahmad-moussawi** [comment]
closing for now, feel free to reopen this later
