### ISSUE TITLE
Bindings are stateful

### ISSUE THREAD

**Issue by zhiwei-nu** [sqlkata/querybuilder#82]
As the title states, Bindings is stateful for `QueryFactory`. I'm using it like so:
```
            var rows = new[]
            {
                new object[] {Guid.NewGuid(), -10.0, 40},
            };
            var columns = new[] {"id", "lat", "lng"};
            // This is okay
            _db.Query(_tableName).Insert(columns, rows);
            _db.Query(_tableName).First<Node>();
```
this fails because after `Insert`, the `Bindings` for the `PostgresCompiler` / `SqlResult` has the bindings set to the row values, which causes `First` to fail, as the `LIMIT` clause gets an unexpected parameter (the UUID in this case).

I am unsure whether this i intended, but the proper usage right now for me is to reinstantiate the `PostgresCompiler` and `QueryFactory` every time

**Comment by ahmad-moussawi** [comment]
Yes you are right, this was caused by recent update, what version are you using ?

**Comment by zhiwei-nu** [comment]
@ahmad-moussawi I'm using `1.0.0-eta-484`

**Comment by ahmad-moussawi** [comment]
related to #80, could you check the version beta-510 and confirm ?

**Comment by zhiwei-nu** [comment]
@ahmad-moussawi i don't see it in nuget, is it already out there?

**Comment by ahmad-moussawi** [comment]
it's hosted in myget for now,
check https://sqlkata.com/docs#add-sqlkata-myget-feed-to-your-project

**Comment by zhiwei-nu** [comment]
@ahmad-moussawi seems like that works :+1:
