### ISSUE TITLE
how to join multiple where cluses together in sqlkata?

### ISSUE THREAD

**Issue by navid-dada** [sqlkata/querybuilder#85]
I am using SqlKata to creating dynamic SQL queries. I have a list of conditions which are generated according to my business rules those are stored in my database. this is my code sample:

```
var list = new List<Query>();
foreach(var rule in rules){
       var q = new Query()
          .Where(x=> x.Where("Price", "<", rule.Price).OrWhere("GoodsType", "=", rule.Type));
        list.Add(q);
  }
```

now I want to join this list item together. but none of Where function extensions overload doesn't accept Query type parameters. Is there any way to join this where clauses together?

**Comment by ahmad-moussawi** [comment]
Please don't use issues tracker for questions, I will follow your question on StackOverflow
