### ISSUE TITLE
is there any way to create outer apply commend? 

### ISSUE THREAD

**Issue by navid-dada** [sqlkata/querybuilder#86]
I need some advance feature of SQL inside sqlkata such as outer apply of IIF expression inside the projection.
is there any way to create such query inside sqlkata?

**Comment by ahmad-moussawi** [comment]
Currently the only way to do it is by using the `query.SelectRaw("IIF(condition, 'a', 'b')")`

**Comment by ahmad-moussawi** [comment]
you can follow this feature on #104
