### ISSUE TITLE
.NET 4.5 support

### ISSUE THREAD

**Issue by Hazzamanic** [sqlkata/querybuilder#89]
Hey,

Loving this project and hopefully want to use it in a few things at work. Unfortunately we are stuck on .NET 4.5 right now and I see that the latest versions now require .NET 4.5.1, from release 1.0.0-beta-441 and up. Is there a reason the latest versions require 4.5.1? I don't really want to get stuck on an old beta release haha

**Comment by Azhe403** [comment]
up, jejak

**Comment by ceastwood** [comment]
Looks like all net fx support was removed in one of today's commits.

I will make a couple commits to return net45 support in QueryBuilder.

SqlKata.Execution will require at minimum netfx >= net451 because of [Dapper](https://www.nuget.org/packages/Dapper/)

**Comment by ceastwood** [comment]
@ahmad-moussawi
I think multi-targeting netstandard1.0 +net45 is a good move so that netfx users don't need to pull down and reference NETStandard.Library

**Comment by ahmad-moussawi** [comment]
Yes currently the **QueryBuilder** is supported on `netstandard1.0` so it will works on `>= net45`, while the **SqlKata.Execution** requires `>= netstandard1.3` because of **Dapper** as @ceastwood mentioned above
