### ISSUE TITLE
[Table] with (nolock)

### ISSUE THREAD

**Issue by Sicos1977** [sqlkata/querybuilder#90]
How do I do a [Table] with (nolock) hint?

`var query = new Query("Posts").Select("Id", "Title")`

will be
`SELECT [Id], [Title] FROM [Posts]`

but I want it to be
`SELECT [Id], [Title] FROM [Posts] WITH (nolock)`

**Comment by ahmad-moussawi** [comment]
currently there is no direct method to handle this, but you can use the `FromRaw` method 

```cs
new Query().FromRaw("[Posts] WITH (nolock)").Select("Id", "Title");
```

**Comment by Sicos1977** [comment]
Thanks

**Comment by BalajiDharmaraj** [comment]
How can i add table hint for each join?
var query = new Query().FromRaw("Users with (nolock)")
                .Join("Authors", "Authors.Id", "Posts.AuthorId")
                .Where("Id", 1)
                .Where("Status", "Active");
will be
SELECT * FROM Users with (nolock)
INNER JOIN [Authors] ON [Authors].[Id] = [Posts].[AuthorId]
WHERE [Id] = 1 AND [Status] = 'Active'

but I want it to be
SELECT * FROM Users with (nolock)
INNER JOIN [Authors]  **with (nolock)** ON [Authors].[Id] = [Posts].[AuthorId]
WHERE [Id] = 1 AND [Status] = 'Active'
