### ISSUE TITLE
Nested selects with limit do not bind parameters correctly

### ISSUE THREAD

**Issue by PejmanNik** [sqlkata/querybuilder#91]
Nested selects with limit do not bind parameters correctly in SQL Server

Because of this code:

https://github.com/sqlkata/querybuilder/blob/455b729d816784805f3bb18810dffb2cebd4a439/QueryBuilder/Compilers/SqlServerCompiler.cs#L100

Nested Select Limit parameter move to the first position of binding parameters list and is wrong.

Before fix and make PR I need to now your strategy for this matter
Thank you

**Comment by PejmanNik** [comment]
Yes Sure. Working on it.
Thank You

**Comment by PejmanNik** [comment]
Hi @ahmad-moussawi 
Can I help with this problem?

**Comment by ahmad-moussawi** [comment]
Issue is solved now in the latest beta version, thanks for reporting

**Comment by PejmanNik** [comment]
Thank you, Ahmad. Great work!
