### ISSUE TITLE
InsertOrUpdate Support

### ISSUE THREAD

**Issue by Sicos1977** [sqlkata/querybuilder#93]
Hi,

Is it possible to do something like this with sqlKata?

```
IF EXISTS
(
    SELECT  1
    FROM    [Example]
    WHERE   Id = @Id
)
BEGIN

    UPDATE  [Example]
    SET     [ChangedDate] = GETDATE(),
            [Example1]    = @Example1
    WHERE   [Id]          = @Id

END
ELSE
BEGIN

    INSERT INTO [Example]
    (
        [ChangedDate],
        [Example1],
    )
    Values
    (
        GETDATE(),
        @Example1
    )

END
```

**Comment by Sicos1977** [comment]
I like your project. I cloned it and doing some code cleanup and adding comment.

**Comment by ahmad-moussawi** [comment]
Hi Thanks for your warm feedback, for your case no there is no direct way to achieve that, raw statements may be useful for this case 
https://github.com/sqlkata/querybuilder/issues/94

Side note: be aware that your provided query can lead to reading phantom data.

**Comment by ahmad-moussawi** [comment]
yes sure

**Comment by Sicos1977** [comment]
Also a small question why are you using lower case for some methods?
For example the  getOr() and getNot() methods? These should normally start with a uppercase G.

Do you mind if a do some code cleanup to conform to Microsoft coding rules and put that in a pull request?

**Comment by ahmad-moussawi** [comment]
Actually I didn't find a clear documentation how to name protected variables :/, I am new to c# world :),
so go ahead if it's not aligned with C# coding guideline

**Comment by Sicos1977** [comment]
It looks like you are coming from the Java world. I did send you a Pull request with support for hints and some code cleanup... more will follow. It will take me some days to cleanup everything :-). But never mind you did a fantastic job with this library.

**Comment by ahmad-moussawi** [comment]
closing, tracking this feature on #103
