### ISSUE TITLE
Support Raw Statements

### ISSUE THREAD

**Issue by ahmad-moussawi** [sqlkata/querybuilder#94]
Ability to execute raw statements:

current proposal:
```cs
var users = db.Select("SELECT * FROM Users"); -- select data
var affected = db.Update("UPDATE Table set A = ?", new [] {1}); -- to update data
var deleted = db.Delete("DELETE FROM Table"); -- to delete from table
db.Statement("exec StoredProcedure ? ?", new [] {1, 2}); -- execute any other kind of queries
```

**Comment by ahmad-moussawi** [comment]
Added API:
db.Statement("exec ..."); // to update and execute
db.Select("SELECT * FROM A"); // to select data
db.Select<User>("SELECT * FROM Users");

**Comment by weituotian** [comment]
@ahmad-moussawi 
is there a doc? what `db.Select("SELECT * FROM A")` return?

**Comment by ahmad-moussawi** [comment]
I mean by `users` a list of **dynamic**, and specifically `IEnumerable<dynamic>`,
off course you can use the generic overload to return `IEnumerable<T>`.

I will update this in the doc, do you min open an issue under https://github.com/sqlkata/docs
