### ISSUE TITLE
Add way to get inserted auto increment id

### ISSUE THREAD

**Issue by JakeAlmer** [sqlkata/querybuilder#99]
Far as I can tell there is no way to get the inserted auto increment id when using `AsInsert()`. This seems like a pretty common use case, am I missing a way to do this?

Something equivalent to using `SCOPE_IDENTITY()` in sql server for example.

**Comment by ahmad-moussawi** [comment]
Actually there is a plan to add it, but there are some complex scenarios that cannot be easily supported, for example batch insert on MySql.

**Comment by MelroyBritto** [comment]
firstly thanks for **SQLKATA, YOU ROCK!!**

I was also facing the same issue, after insert I wanted the ID returned so i did something like this ( I apologize if it's not the best approach and would appreciate your guidance)

```
 //Create the Insert Query object
var query = db.Query(tableName).AsInsert(objWithoutPrimaryKey);

SqlResult compiledQuery = comp.Compile(query);
                
//Inject the Identity in the Compiled Query SQL object
var sql = compiledQuery.Sql + "; SELECT @@IDENTITY as ID;";
                
//Name Binding house the values that the insert query needs 
var IdentityKey = db.Select(sql, compiledQuery.NamedBindings).FirstOrDefault().ID;
```

**Comment by ahmad-moussawi** [comment]
Now this feature is available in the version 1.1.0, thanks for all your feedbacks 
https://sqlkata.com/docs/execution/update#insert-one-record-and-get-the-inserted-id

**Comment by JakeAlmer** [comment]
awesome work, though I do have reservations about using `@@IDENTITY` vs `SCOPE_IDENTITY()` in the sql server implementation.
https://github.com/sqlkata/querybuilder/commit/5945fd9a7ef643cf87510711bad8f7feea13f0ee#r30625069

**Comment by ahmad-moussawi** [comment]
@JakeAlmer you are right, patched in 1.1.2  thanks!

**Comment by MelroyBritto** [comment]
Awesome!!!!  Thanks a lot guys...

**Comment by dannyheardairelogic** [comment]
I'm getting an error when using this on postgres: '"55000: lastval is not yet defined in this session"'
No issues with the insert query

**Comment by nielslucas** [comment]
How to get the last 'id' if the key is not 'id' but for example 'ProjectID' ?
